SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('IT-21', 'fi', 'Piemonte'),
('IT-23', 'fi', 'Aostanlaakso'),
('IT-25', 'fi', 'Lombardia'),
('IT-32', 'fi', 'Etelä-Tiroli'),
('IT-34', 'fi', 'Veneto'),
('IT-36', 'fi', 'Friuli-Venezia Giulia'),
('IT-42', 'fi', 'Liguria'),
('IT-45', 'fi', 'Emilia-Romagna'),
('IT-52', 'fi', 'Toscana'),
('IT-55', 'fi', 'Umbria'),
('IT-57', 'fi', 'Marche'),
('IT-62', 'fi', 'Latium'),
('IT-65', 'fi', 'Abruzzo'),
('IT-67', 'fi', 'Molise'),
('IT-72', 'fi', 'Campania'),
('IT-75', 'fi', 'Apulia'),
('IT-77', 'fi', 'Basilicata'),
('IT-78', 'fi', 'Calabria'),
('IT-82', 'fi', 'Sisilia'),
('IT-88', 'fi', 'Sardinia'),
('IT-AG', 'fi', 'Agrigento'),
('IT-AL', 'fi', 'Alessandria'),
('IT-AN', 'fi', 'Ancona'),
('IT-AP', 'fi', 'Ascoli Piceno'),
('IT-AQ', 'fi', 'L''Aquila'),
('IT-AR', 'fi', 'Arezzo'),
('IT-AT', 'fi', 'Asti'),
('IT-AV', 'fi', 'Avellino'),
('IT-BA', 'fi', 'Bari'),
('IT-BG', 'fi', 'Bergamo'),
('IT-BI', 'fi', 'Biella'),
('IT-BL', 'fi', 'Belluno'),
('IT-BN', 'fi', 'Benevento'),
('IT-BO', 'fi', 'Bologna'),
('IT-BR', 'fi', 'Brindisi'),
('IT-BS', 'fi', 'Brescia'),
('IT-BT', 'fi', 'Barletta-Andria-Trani'),
('IT-BZ', 'fi', 'Bolzano'),
('IT-CA', 'fi', 'Cagliari'),
('IT-CB', 'fi', 'Campobasso'),
('IT-CE', 'fi', 'Caserta'),
('IT-CH', 'fi', 'Chieti'),
('IT-CL', 'fi', 'Caltanissetta'),
('IT-CN', 'fi', 'Cuneo'),
('IT-CO', 'fi', 'Como'),
('IT-CR', 'fi', 'Cremona'),
('IT-CS', 'fi', 'Cosenza'),
('IT-CT', 'fi', 'Catania'),
('IT-CZ', 'fi', 'Catanzaro'),
('IT-EN', 'fi', 'Enna'),
('IT-FC', 'fi', 'Forlì-Cesena'),
('IT-FE', 'fi', 'Ferrara'),
('IT-FG', 'fi', 'Foggia'),
('IT-FI', 'fi', 'Firenze'),
('IT-FM', 'fi', 'Fermo'),
('IT-FR', 'fi', 'Frosinone'),
('IT-GE', 'fi', 'Genova'),
('IT-GO', 'fi', 'Gorizia'),
('IT-GR', 'fi', 'Grosseto'),
('IT-IM', 'fi', 'Imperia'),
('IT-IS', 'fi', 'Isernia'),
('IT-KR', 'fi', 'Crotone'),
('IT-LC', 'fi', 'Lecco'),
('IT-LE', 'fi', 'Lecce'),
('IT-LI', 'fi', 'Livorno'),
('IT-LO', 'fi', 'Lodi'),
('IT-LT', 'fi', 'Latina'),
('IT-LU', 'fi', 'Lucca'),
('IT-MB', 'fi', 'Monza ja Brianza'),
('IT-MC', 'fi', 'Macerata'),
('IT-ME', 'fi', 'Messina'),
('IT-MI', 'fi', 'Milano'),
('IT-MN', 'fi', 'Mantova'),
('IT-MO', 'fi', 'Modena'),
('IT-MS', 'fi', 'Massa-Carrara'),
('IT-MT', 'fi', 'Matera'),
('IT-NA', 'fi', 'Napoli'),
('IT-NO', 'fi', 'Novara'),
('IT-NU', 'fi', 'Nuoro'),
('IT-OR', 'fi', 'Oristano'),
('IT-PA', 'fi', 'Palermo'),
('IT-PC', 'fi', 'Piacenza'),
('IT-PD', 'fi', 'Padova'),
('IT-PE', 'fi', 'Pescara'),
('IT-PG', 'fi', 'Perugia'),
('IT-PI', 'fi', 'Pisa'),
('IT-PN', 'fi', 'Pordenone'),
('IT-PO', 'fi', 'Prato'),
('IT-PR', 'fi', 'Parman'),
('IT-PT', 'fi', 'Pistoia'),
('IT-PU', 'fi', 'Pesaro ja Urbino'),
('IT-PV', 'fi', 'Pavia'),
('IT-PZ', 'fi', 'Potenza'),
('IT-RA', 'fi', 'Ravenna'),
('IT-RC', 'fi', 'Reggio Calabria'),
('IT-RE', 'fi', 'Reggio Emilia'),
('IT-RG', 'fi', 'Ragusa'),
('IT-RI', 'fi', 'Rieti'),
('IT-RM', 'fi', 'Roma'),
('IT-RN', 'fi', 'Rimini'),
('IT-RO', 'fi', 'Rovigo'),
('IT-SA', 'fi', 'Salerno'),
('IT-SI', 'fi', 'Siena'),
('IT-SO', 'fi', 'Sondrio'),
('IT-SP', 'fi', 'La Spezia'),
('IT-SR', 'fi', 'Sirakusa'),
('IT-SS', 'fi', 'Sassari'),
('IT-SU', 'fi', 'Sud Sardegna'),
('IT-SV', 'fi', 'Savona'),
('IT-TA', 'fi', 'Taranto'),
('IT-TE', 'fi', 'Teramo'),
('IT-TN', 'fi', 'Trento'),
('IT-TO', 'fi', 'Torino'),
('IT-TP', 'fi', 'Trapani'),
('IT-TR', 'fi', 'Terni'),
('IT-TS', 'fi', 'Trieste'),
('IT-TV', 'fi', 'Treviso'),
('IT-UD', 'fi', 'Udine'),
('IT-VA', 'fi', 'Varese'),
('IT-VB', 'fi', 'Verbano-Cusio-Ossola'),
('IT-VC', 'fi', 'Vercelli'),
('IT-VE', 'fi', 'Venezia'),
('IT-VI', 'fi', 'Vicenza'),
('IT-VR', 'fi', 'Verona'),
('IT-VT', 'fi', 'Viterbo'),
('IT-VV', 'fi', 'Vibo Valentia');

SET FOREIGN_KEY_CHECKS=1;
