SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('EE-130', 'et', 'Alutaguse'),
('EE-141', 'et', 'Anija'),
('EE-142', 'et', 'Antsla'),
('EE-171', 'et', 'Elva'),
('EE-184', 'et', 'Haapsalu'),
('EE-191', 'et', 'Haljala'),
('EE-198', 'et', 'Harku'),
('EE-205', 'et', 'Hiiumaa'),
('EE-214', 'et', 'Häädemeeste'),
('EE-245', 'et', 'Jõelähtme'),
('EE-247', 'et', 'Jõgeva'),
('EE-251', 'et', 'Jõhvi'),
('EE-255', 'et', 'Järva'),
('EE-272', 'et', 'Kadrina'),
('EE-283', 'et', 'Kambja'),
('EE-284', 'et', 'Kanepi'),
('EE-291', 'et', 'Kastre'),
('EE-293', 'et', 'Kehtna'),
('EE-296', 'et', 'Keila'),
('EE-303', 'et', 'Kihnu'),
('EE-305', 'et', 'Kiili'),
('EE-317', 'et', 'Kohila'),
('EE-321', 'et', 'Kohtla-Järve'),
('EE-338', 'et', 'Kose'),
('EE-353', 'et', 'Kuusalu'),
('EE-37', 'et', 'Harju maakond'),
('EE-39', 'et', 'Hiiu maakond'),
('EE-424', 'et', 'Loksa'),
('EE-430', 'et', 'Lääneranna'),
('EE-431', 'et', 'Lääne-Harju'),
('EE-432', 'et', 'Luunja'),
('EE-441', 'et', 'Lääne-Nigula'),
('EE-442', 'et', 'Lüganuse'),
('EE-446', 'et', 'Maardu'),
('EE-45', 'et', 'Ida-Viru maakond'),
('EE-478', 'et', 'Muhu'),
('EE-480', 'et', 'Mulgi'),
('EE-486', 'et', 'Mustvee'),
('EE-50', 'et', 'Jõgeva maakond'),
('EE-503', 'et', 'Märjamaa'),
('EE-511', 'et', 'Narva'),
('EE-514', 'et', 'Narva-Jõesuu'),
('EE-52', 'et', 'Järva maakond'),
('EE-528', 'et', 'Nõo'),
('EE-557', 'et', 'Otepää'),
('EE-56', 'et', 'Lääne maakond'),
('EE-567', 'et', 'Paide'),
('EE-586', 'et', 'Peipsiääre'),
('EE-60', 'et', 'Lääne-Viru maakond'),
('EE-615', 'et', 'Põhja-Sakala'),
('EE-618', 'et', 'Põltsamaa'),
('EE-622', 'et', 'Põlva'),
('EE-624', 'et', 'Pärnu'),
('EE-638', 'et', 'Põhja-Pärnumaa'),
('EE-64', 'et', 'Põlva maakond'),
('EE-651', 'et', 'Raasiku'),
('EE-653', 'et', 'Rae'),
('EE-661', 'et', 'Rakvere'),
('EE-663', 'et', 'Rakvere'),
('EE-668', 'et', 'Rapla'),
('EE-68', 'et', 'Pärnu maakond'),
('EE-689', 'et', 'Ruhnu'),
('EE-698', 'et', 'Rõuge'),
('EE-708', 'et', 'Räpina'),
('EE-71', 'et', 'Rapla maakond'),
('EE-712', 'et', 'Saarde'),
('EE-714', 'et', 'Saaremaa'),
('EE-719', 'et', 'Saku'),
('EE-726', 'et', 'Saue'),
('EE-732', 'et', 'Setomaa'),
('EE-735', 'et', 'Sillamäe'),
('EE-74', 'et', 'Saare maakond'),
('EE-784', 'et', 'Tallinn'),
('EE-79', 'et', 'Tartu maakond'),
('EE-792', 'et', 'Tapa'),
('EE-793', 'et', 'Tartu'),
('EE-796', 'et', 'Tartu'),
('EE-803', 'et', 'Toila'),
('EE-809', 'et', 'Tori'),
('EE-81', 'et', 'Valga maakond'),
('EE-824', 'et', 'Tõrva'),
('EE-834', 'et', 'Türi'),
('EE-84', 'et', 'Viljandi maakond'),
('EE-855', 'et', 'Valga'),
('EE-87', 'et', 'Võru maakond'),
('EE-890', 'et', 'Viimsi'),
('EE-897', 'et', 'Viljandi'),
('EE-899', 'et', 'Viljandi'),
('EE-901', 'et', 'Vinni'),
('EE-903', 'et', 'Viru-Nigula'),
('EE-907', 'et', 'Vormsi'),
('EE-917', 'et', 'Võru'),
('EE-919', 'et', 'Võru'),
('EE-928', 'et', 'Väike-Maarja');

SET FOREIGN_KEY_CHECKS=1;
