SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('PH-00', 'tl', 'Pambansang Punong Rehiyon'),
('PH-01', 'tl', 'Ilocos (Rehiyon I)'),
('PH-02', 'tl', 'Lambak ng Cagayan (Rehiyon II)'),
('PH-03', 'tl', 'Gitnang Luzon (Rehiyon III)'),
('PH-05', 'tl', 'Bicol (Rehiyon V)'),
('PH-06', 'tl', 'Kanlurang Visayas (Rehiyon VI)'),
('PH-07', 'tl', 'Gitnang Visayas (Rehiyon VII)'),
('PH-08', 'tl', 'Silangang Visayas (Rehiyon VIII)'),
('PH-09', 'tl', 'Zamboanga Peninsula (Rehiyon IX)'),
('PH-10', 'tl', 'Hilagang Mindanao (Rehiyon X)'),
('PH-11', 'tl', 'Davao (Rehiyon XI)'),
('PH-12', 'tl', 'Soccsksargen (Rehiyon XII)'),
('PH-13', 'tl', 'Caraga (Rehiyon XIII)'),
('PH-14', 'tl', 'Autonomous Region in Muslim Mindanao (ARMM)'),
('PH-15', 'tl', 'Cordillera Administrative Region (CAR)'),
('PH-40', 'tl', 'Calabarzon (Rehiyon IV-A)'),
('PH-41', 'tl', 'Mimaropa (Rehiyon IV-B)'),
('PH-ABR', 'tl', 'Ilocos'),
('PH-AGN', 'tl', 'Lambak ng Cagayan'),
('PH-AGS', 'tl', 'Gitnang Luzon'),
('PH-AKL', 'tl', 'Aklan'),
('PH-ALB', 'tl', 'Bicol'),
('PH-ANT', 'tl', 'Kanlurang Visayas'),
('PH-APA', 'tl', 'Apayao'),
('PH-AUR', 'tl', 'Aurora'),
('PH-BAN', 'tl', 'Gitnang Visayas'),
('PH-BAS', 'tl', 'Basilan'),
('PH-BEN', 'tl', 'Hilagang Mindanao'),
('PH-BIL', 'tl', 'Biliran'),
('PH-BOH', 'tl', 'Davao'),
('PH-BTG', 'tl', 'Tangway ng Zamboanga'),
('PH-BTN', 'tl', 'Silangang Visayas'),
('PH-BUK', 'tl', 'Soccsksargen'),
('PH-BUL', 'tl', 'Caraga'),
('PH-CAG', 'tl', 'Autonomous na Rehiyon sa Muslim Mindanao'),
('PH-CAM', 'tl', 'Camiguin'),
('PH-CAN', 'tl', 'Cordillera Administrative Region'),
('PH-CAP', 'tl', 'Capiz'),
('PH-CAS', 'tl', 'Camarines Sur'),
('PH-CAT', 'tl', 'Catanduanes'),
('PH-CAV', 'tl', 'Cavite'),
('PH-CEB', 'tl', 'Cebu'),
('PH-COM', 'tl', 'Davao de Oro'),
('PH-DAO', 'tl', 'Davao Oriental'),
('PH-DAS', 'tl', 'Davao del Sur'),
('PH-DAV', 'tl', 'Davao del Norte'),
('PH-DIN', 'tl', 'Dinagat Islands'),
('PH-DVO', 'tl', 'Davao Occidental'),
('PH-EAS', 'tl', 'Silangang Samar'),
('PH-GUI', 'tl', 'Guimaras'),
('PH-IFU', 'tl', 'Ifugao'),
('PH-ILI', 'tl', 'Iloilo'),
('PH-ILN', 'tl', 'Ilocos Norte'),
('PH-ILS', 'tl', 'Ilocos Sur'),
('PH-ISA', 'tl', 'Isabela'),
('PH-KAL', 'tl', 'Kalinga'),
('PH-LAG', 'tl', 'Laguna'),
('PH-LAN', 'tl', 'Lanao del Norte'),
('PH-LAS', 'tl', 'Lanao del Sur'),
('PH-LEY', 'tl', 'Leyte'),
('PH-LUN', 'tl', 'La Union'),
('PH-MAD', 'tl', 'Marinduque'),
('PH-MAS', 'tl', 'Masbate'),
('PH-MDC', 'tl', 'Calabarzon'),
('PH-MDR', 'tl', 'Mimaropa'),
('PH-MGN', 'tl', 'Maguindanao del Norte'),
('PH-MGS', 'tl', 'Maguindanao del Sur'),
('PH-MOU', 'tl', 'Mountain Province'),
('PH-MSC', 'tl', 'Misamis Occidental'),
('PH-MSR', 'tl', 'Misamis Oriental'),
('PH-NCO', 'tl', 'Cotabato'),
('PH-NEC', 'tl', 'Negros Occidental'),
('PH-NER', 'tl', 'Negros Oriental'),
('PH-NSA', 'tl', 'Hilagang Samar'),
('PH-NUE', 'tl', 'Nueva Ecija'),
('PH-NUV', 'tl', 'Nueva Vizcaya'),
('PH-PAM', 'tl', 'Pampanga'),
('PH-PAN', 'tl', 'Pangasinan'),
('PH-PLW', 'tl', 'Palawan'),
('PH-QUE', 'tl', 'Quezon'),
('PH-QUI', 'tl', 'Quirino'),
('PH-RIZ', 'tl', 'Rizal'),
('PH-ROM', 'tl', 'Romblon'),
('PH-SAR', 'tl', 'Sarangani'),
('PH-SCO', 'tl', 'South Cotabato'),
('PH-SIG', 'tl', 'Siquijor'),
('PH-SLE', 'tl', 'Southern Leyte'),
('PH-SLU', 'tl', 'Sulu'),
('PH-SOR', 'tl', 'Sorsogon'),
('PH-SUK', 'tl', 'Sultan Kudarat'),
('PH-SUN', 'tl', 'Surigao del Norte'),
('PH-SUR', 'tl', 'Surigao del Sur'),
('PH-TAR', 'tl', 'Tarlac'),
('PH-TAW', 'tl', 'Tawi-Tawi'),
('PH-WSA', 'tl', 'Samar'),
('PH-ZAN', 'tl', 'Zamboanga del Norte'),
('PH-ZAS', 'tl', 'Zamboanga del Sur'),
('PH-ZMB', 'tl', 'Zambales'),
('PH-ZSI', 'tl', 'Zamboanga Sibugay');

SET FOREIGN_KEY_CHECKS=1;
