SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('MT-01', 'sw', 'Attard'),
('MT-02', 'sw', 'Balzan'),
('MT-03', 'sw', 'Birgu'),
('MT-04', 'sw', 'Birkirkara'),
('MT-05', 'sw', 'Birzebbuga'),
('MT-06', 'sw', 'Bormla'),
('MT-07', 'sw', 'Dingli'),
('MT-08', 'sw', 'Fgura'),
('MT-09', 'sw', 'Floriana'),
('MT-10', 'sw', 'Fontana'),
('MT-11', 'sw', 'Gudja'),
('MT-12', 'sw', 'Gzira'),
('MT-13', 'sw', 'Ghajnsielem'),
('MT-14', 'sw', 'L-Gharb'),
('MT-15', 'sw', 'Hal Gharghur'),
('MT-16', 'sw', 'Ghasri'),
('MT-17', 'sw', 'Ghaxaq'),
('MT-18', 'sw', 'Hamrun'),
('MT-19', 'sw', 'L-Iklin'),
('MT-20', 'sw', 'Senglea'),
('MT-21', 'sw', 'Kalkara'),
('MT-22', 'sw', 'Kercem'),
('MT-23', 'sw', 'Kirkop'),
('MT-24', 'sw', 'Lija'),
('MT-25', 'sw', 'Luqa'),
('MT-26', 'sw', 'Marsa'),
('MT-27', 'sw', 'Marsaskala'),
('MT-28', 'sw', 'Marsaxlokk'),
('MT-29', 'sw', 'Imdina'),
('MT-30', 'sw', 'Mellieha'),
('MT-31', 'sw', 'Imgarr'),
('MT-32', 'sw', 'Mosta'),
('MT-33', 'sw', 'Imqabba'),
('MT-34', 'sw', 'Imsida'),
('MT-35', 'sw', 'Mtarfa'),
('MT-36', 'sw', 'Munxar'),
('MT-37', 'sw', 'Nadur'),
('MT-38', 'sw', 'Naxxar'),
('MT-39', 'sw', 'Paola'),
('MT-40', 'sw', 'Pembroke'),
('MT-41', 'sw', 'Pieta'),
('MT-42', 'sw', 'Qala'),
('MT-43', 'sw', 'Qormi'),
('MT-44', 'sw', 'Qrendi'),
('MT-45', 'sw', 'Victoria'),
('MT-46', 'sw', 'Rabat'),
('MT-47', 'sw', 'Safi'),
('MT-48', 'sw', 'Saint Julian'),
('MT-49', 'sw', 'Saint John'),
('MT-50', 'sw', 'Saint Lawrence'),
('MT-51', 'sw', 'Saint Paul''s Bay'),
('MT-52', 'sw', 'Sannat'),
('MT-53', 'sw', 'Saint Lucia'),
('MT-54', 'sw', 'Saint Venera'),
('MT-55', 'sw', 'Siggiewi'),
('MT-56', 'sw', 'Sliema'),
('MT-57', 'sw', 'Swieqi'),
('MT-58', 'sw', 'Tarxien'),
('MT-59', 'sw', 'Ta'' Xbiex'),
('MT-60', 'sw', 'Valletta'),
('MT-61', 'sw', 'Xaghra'),
('MT-62', 'sw', 'Xewkija'),
('MT-63', 'sw', 'Xghajra'),
('MT-64', 'sw', 'Zabbar'),
('MT-65', 'sw', 'Iz-Zebbug'),
('MT-66', 'sw', 'Zebbug'),
('MT-67', 'sw', 'Zejtun'),
('MT-68', 'sw', 'Zurrieq');

SET FOREIGN_KEY_CHECKS=1;
