SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('MT-01', 'sq', 'Attard'),
('MT-02', 'sq', 'Balzan'),
('MT-03', 'sq', 'Birgu'),
('MT-04', 'sq', 'Birkirkara'),
('MT-05', 'sq', 'Birzebbuga'),
('MT-06', 'sq', 'Bormla'),
('MT-07', 'sq', 'Dingli'),
('MT-08', 'sq', 'Fgura'),
('MT-09', 'sq', 'Il-Furjana'),
('MT-10', 'sq', 'Fontana'),
('MT-11', 'sq', 'Gudja'),
('MT-12', 'sq', 'Gzira'),
('MT-13', 'sq', 'Ghajnsielem'),
('MT-14', 'sq', 'L-Gharb'),
('MT-15', 'sq', 'Hal Gharghur'),
('MT-16', 'sq', 'Ghasri'),
('MT-17', 'sq', 'Ghaxaq'),
('MT-18', 'sq', 'Hamrun'),
('MT-19', 'sq', 'L-Iklin'),
('MT-20', 'sq', 'L-Isla'),
('MT-21', 'sq', 'Kalkara'),
('MT-22', 'sq', 'Kercem'),
('MT-23', 'sq', 'Kirkop'),
('MT-24', 'sq', 'Lija'),
('MT-25', 'sq', 'Luqa'),
('MT-26', 'sq', 'Marsa'),
('MT-27', 'sq', 'Marsaskala'),
('MT-28', 'sq', 'Marsaxlokk'),
('MT-29', 'sq', 'Imdina'),
('MT-30', 'sq', 'Mellieha'),
('MT-31', 'sq', 'Imgarr'),
('MT-32', 'sq', 'Mosta'),
('MT-33', 'sq', 'Imqabba'),
('MT-34', 'sq', 'Imsida'),
('MT-35', 'sq', 'Imtarfa'),
('MT-36', 'sq', 'Munxar'),
('MT-37', 'sq', 'Nadur'),
('MT-38', 'sq', 'Naxxar'),
('MT-39', 'sq', 'Paola'),
('MT-40', 'sq', 'Pembroke'),
('MT-41', 'sq', 'Pieta'),
('MT-42', 'sq', 'Qala'),
('MT-43', 'sq', 'Qormi'),
('MT-44', 'sq', 'Qrendi'),
('MT-45', 'sq', 'Victoria'),
('MT-46', 'sq', 'Rabat'),
('MT-47', 'sq', 'Safi'),
('MT-48', 'sq', 'Shën Julianit'),
('MT-49', 'sq', 'San Gwann'),
('MT-50', 'sq', 'Shën Lorenci'),
('MT-51', 'sq', 'Gjiri i Shën Palit'),
('MT-52', 'sq', 'Sannat'),
('MT-53', 'sq', 'Santa Lucija'),
('MT-54', 'sq', 'Santa Venera'),
('MT-55', 'sq', 'Siggiewi'),
('MT-56', 'sq', 'Sliema'),
('MT-57', 'sq', 'Swieqi'),
('MT-58', 'sq', 'Tarxien'),
('MT-59', 'sq', 'Ta'' Xbiex'),
('MT-60', 'sq', 'Valeta'),
('MT-61', 'sq', 'Xaghra'),
('MT-62', 'sq', 'Xewkija'),
('MT-63', 'sq', 'Xghajra'),
('MT-64', 'sq', 'Zabbar'),
('MT-65', 'sq', 'Iz-Zebbug'),
('MT-66', 'sq', 'Zebbug'),
('MT-67', 'sq', 'Zejtun'),
('MT-68', 'sq', 'Zurrieq');

SET FOREIGN_KEY_CHECKS=1;
