SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('MD-AN', 'tl', 'Anenii Noi'),
('MD-BA', 'tl', 'Balti'),
('MD-BD', 'tl', 'Bender'),
('MD-BR', 'tl', 'Briceni'),
('MD-BS', 'tl', 'Basarabeasca'),
('MD-CA', 'tl', 'Raionul Cahul'),
('MD-CL', 'tl', 'Raionul Calarasi'),
('MD-CM', 'tl', 'Cimislia'),
('MD-CR', 'tl', 'Criuleni'),
('MD-CS', 'tl', 'Raionul Causeni'),
('MD-CT', 'tl', 'Cantemir'),
('MD-CU', 'tl', 'Munisipalidad ng Chișinău'),
('MD-DO', 'tl', 'Donduseni'),
('MD-DR', 'tl', 'Raionul Drochia'),
('MD-DU', 'tl', 'Raionul Dubasari'),
('MD-ED', 'tl', 'Raionul Edinet'),
('MD-FA', 'tl', 'Falesti'),
('MD-FL', 'tl', 'Floresti'),
('MD-GA', 'tl', 'Gagauzia'),
('MD-GL', 'tl', 'Glodeni'),
('MD-HI', 'tl', 'Hincesti'),
('MD-IA', 'tl', 'Ialoveni'),
('MD-LE', 'tl', 'Leova'),
('MD-NI', 'tl', 'Nisporeni'),
('MD-OC', 'tl', 'Raionul Ocnita'),
('MD-OR', 'tl', 'Orhei'),
('MD-RE', 'tl', 'Rezina'),
('MD-RI', 'tl', 'Riscani'),
('MD-SD', 'tl', 'Soldanesti'),
('MD-SI', 'tl', 'Singerei'),
('MD-SN', 'tl', 'Administrative-Territorial Units ng Kaliwang Bangko ng Dniester'),
('MD-SO', 'tl', 'Raionul Soroca'),
('MD-ST', 'tl', 'Raionul Straseni'),
('MD-SV', 'tl', 'Raionul Stefan Voda'),
('MD-TA', 'tl', 'Taraclia'),
('MD-TE', 'tl', 'Telenesti'),
('MD-UN', 'tl', 'Raionul Ungheni');

SET FOREIGN_KEY_CHECKS=1;
