SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('DO-01', 'es', 'Distrito de Santo Domingo'),
('DO-02', 'es', 'Provincia Azua'),
('DO-03', 'es', 'Bahoruco'),
('DO-04', 'es', 'Barahona'),
('DO-05', 'es', 'Provincia Dajabón'),
('DO-06', 'es', 'Duarte'),
('DO-07', 'es', 'Provincia Elías Piña'),
('DO-08', 'es', 'Provincia El Seibo'),
('DO-09', 'es', 'Espaillat'),
('DO-10', 'es', 'Independencia'),
('DO-11', 'es', 'La Altagracia'),
('DO-12', 'es', 'La Romana'),
('DO-13', 'es', 'Provincia La Vega'),
('DO-14', 'es', 'María Trinidad Sánchez'),
('DO-15', 'es', 'Monte Cristi'),
('DO-16', 'es', 'Pedernales'),
('DO-17', 'es', 'Provincia Peravia'),
('DO-18', 'es', 'Puerto Plata'),
('DO-19', 'es', 'Hermanas Mirabal'),
('DO-20', 'es', 'Distrito de Samana'),
('DO-21', 'es', 'Provincia San Cristóbal'),
('DO-22', 'es', 'Provincia San Juan'),
('DO-23', 'es', 'San Pedro de Macorís'),
('DO-24', 'es', 'Sánchez Ramírez'),
('DO-25', 'es', 'Provincia Santiago'),
('DO-26', 'es', 'Provincia Santiago Rodríguez'),
('DO-27', 'es', 'Valverde'),
('DO-28', 'es', 'Provincia Monseñor Nouel'),
('DO-29', 'es', 'Monte Plata'),
('DO-30', 'es', 'Hato Mayor'),
('DO-31', 'es', 'San José de Ocoa'),
('DO-32', 'es', 'Provincia Santo Domingo'),
('DO-33', 'es', 'Cibao Nordeste'),
('DO-34', 'es', 'Cibao Noroeste'),
('DO-35', 'es', 'Cibao Norte'),
('DO-36', 'es', 'Cibao Sur'),
('DO-37', 'es', 'El Valle'),
('DO-38', 'es', 'Enriquillo'),
('DO-39', 'es', 'Higuamó'),
('DO-40', 'es', 'Ozama'),
('DO-41', 'es', 'Valdesia'),
('DO-42', 'es', 'Yuma');

SET FOREIGN_KEY_CHECKS=1;
