SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_countries_altnames` (`key`, `language_key`, `name`) VALUES
('CI', 'aa', 'Cote d''Ivoire'),
('CI', 'am', 'ኮትዲቯር'),
('CI', 'ar', 'ساحل العاج'),
('CI', 'az', 'Kotd’ivuar'),
('CI', 'be', 'Кот-д’Івуар'),
('CI', 'bg', 'Кот д’Ивоар'),
('CI', 'bn', 'কোট ডি‘আইভোর'),
('CI', 'bs', 'Obala Slonovače'),
('CI', 'ca', 'Côte d’Ivoire'),
('CI', 'cs', 'Pobřeží slonoviny'),
('CI', 'da', 'Elfenbenskysten'),
('CI', 'de', 'Côte d’Ivoire'),
('CI', 'dv', 'އައިވަރީ ކޯސްޓު'),
('CI', 'dz', 'ཀོ་ཊེ་ ཌི་ཨི་ཝོ་རེ'),
('CI', 'el', 'Ακτή Ελεφαντοστού'),
('CI', 'en', 'Côte d’Ivoire'),
('CI', 'es', 'Côte d’Ivoire'),
('CI', 'et', 'Elevandiluurannik'),
('CI', 'fa', 'ساحل عاج'),
('CI', 'fi', 'Norsunluurannikko'),
('CI', 'fo', 'Fílabeinsstrondin'),
('CI', 'fr', 'Côte d’Ivoire'),
('CI', 'he', 'חוף השנהב'),
('CI', 'hr', 'Obala Bjelokosti'),
('CI', 'ht', 'Côte d’Ivoire'),
('CI', 'hu', 'Elefántcsontpart'),
('CI', 'hy', 'Կոտ դ՚Իվուար'),
('CI', 'id', 'Côte d’Ivoire'),
('CI', 'is', 'Fílabeinsströndin'),
('CI', 'it', 'Costa d’Avorio'),
('CI', 'ja', 'コートジボワール'),
('CI', 'ka', 'კოტ-დივუარი'),
('CI', 'kk', 'Кот-д’Ивуар'),
('CI', 'kl', 'Cote d''Ivoire'),
('CI', 'km', 'កូតឌីវ័រ'),
('CI', 'ko', '코트디부아르'),
('CI', 'ky', 'Кот-д’Ивуар'),
('CI', 'la', 'Litus Eburneum'),
('CI', 'lb', 'Côte d’Ivoire'),
('CI', 'lt', 'Dramblio Kaulo Krantas'),
('CI', 'lv', 'Kotdivuāra'),
('CI', 'mh', 'Cote d''Ivoire'),
('CI', 'mk', 'Брегот на Слоновата Коска'),
('CI', 'mn', 'Кот-д’Ивуар'),
('CI', 'ms', 'Cote d’Ivoire'),
('CI', 'mt', 'il-Kosta tal-Avorju'),
('CI', 'my', 'ကို့တ် ဒီဗွာ'),
('CI', 'ne', 'कोट दिभोर'),
('CI', 'nl', 'Ivoorkust'),
('CI', 'no', 'Elfenbenskysten'),
('CI', 'ny', 'Cote d''Ivoire'),
('CI', 'pl', 'Côte d’Ivoire'),
('CI', 'pt', 'Costa do Marfim'),
('CI', 'ro', 'Côte d’Ivoire'),
('CI', 'ru', 'Кот-д’Ивуар'),
('CI', 'rw', 'Kote Divuwari'),
('CI', 'si', 'කෝට් දි අයිවරි'),
('CI', 'sk', 'Pobrežie Slonoviny'),
('CI', 'sl', 'Slonokoščena obala'),
('CI', 'sm', 'Côte d''Ivoire'),
('CI', 'so', 'Ayfori Koost'),
('CI', 'sq', 'Côte d’Ivoire'),
('CI', 'sr', 'Обала Слоноваче (Кот д’Ивоар)'),
('CI', 'sv', 'Elfenbenskusten'),
('CI', 'sw', 'Cote d’Ivoire'),
('CI', 'tg', 'Кот-д’Ивуар'),
('CI', 'th', 'โกตดิวัวร์'),
('CI', 'tk', 'Kot-d’Iwuar'),
('CI', 'tl', 'Côte d’Ivoire'),
('CI', 'to', 'Matafonua ʻAivolī'),
('CI', 'tr', 'Côte d’Ivoire'),
('CI', 'uk', 'Кот-дʼІвуар'),
('CI', 'ur', 'کوٹ ڈی آئیوری'),
('CI', 'uz', 'Kot-d’Ivuar'),
('CI', 'vi', 'Côte d’Ivoire'),
('CI', 'zh', '科特迪瓦'),
('CI', 'zu', 'i-Côte d’Ivoire');

SET FOREIGN_KEY_CHECKS=1;
