SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('SI-001', 'so', 'Magaalada Ajdovščina'),
('SI-002', 'so', NULL),
('SI-003', 'so', 'Bled'),
('SI-004', 'so', 'Bohinj Degmada'),
('SI-005', 'so', 'Borovnica'),
('SI-006', 'so', NULL),
('SI-007', 'so', NULL),
('SI-008', 'so', NULL),
('SI-009', 'so', NULL),
('SI-010', 'so', NULL),
('SI-011', 'so', NULL),
('SI-012', 'so', 'Cerklje na Gorenjskem'),
('SI-013', 'so', NULL),
('SI-014', 'so', 'Cerkno'),
('SI-015', 'so', NULL),
('SI-016', 'so', 'Crna na Koroskem Degmada'),
('SI-017', 'so', 'Magaalada Crnomelj'),
('SI-018', 'so', 'Destrnik'),
('SI-019', 'so', NULL),
('SI-020', 'so', NULL),
('SI-021', 'so', 'Degmada Dobrova-Polhov Gradec'),
('SI-022', 'so', 'Dol pri Ljubljani Degmada'),
('SI-023', 'so', NULL),
('SI-024', 'so', 'Dornava'),
('SI-025', 'so', NULL),
('SI-026', 'so', NULL),
('SI-027', 'so', 'Obcina Gorenja vas-Poljane Degmada'),
('SI-028', 'so', NULL),
('SI-029', 'so', NULL),
('SI-030', 'so', 'Degmada Gornji Grad'),
('SI-031', 'so', 'Degmada Gornji Petrovci'),
('SI-032', 'so', NULL),
('SI-033', 'so', 'Degmada Salovci'),
('SI-034', 'so', 'Magaalada Hrastnik'),
('SI-035', 'so', NULL),
('SI-036', 'so', 'Idrija'),
('SI-037', 'so', 'Ig Degmada'),
('SI-038', 'so', 'Ilirska Bistrica'),
('SI-039', 'so', 'Degmada Ivancna Gorica'),
('SI-040', 'so', 'Izola-Isola'),
('SI-041', 'so', NULL),
('SI-042', 'so', NULL),
('SI-043', 'so', NULL),
('SI-044', 'so', 'Kanal ob Soci Degmada'),
('SI-045', 'so', NULL),
('SI-046', 'so', 'Kobarid Degmada'),
('SI-047', 'so', NULL),
('SI-048', 'so', NULL),
('SI-049', 'so', NULL),
('SI-050', 'so', 'Koper-Capodistria'),
('SI-051', 'so', NULL),
('SI-052', 'so', NULL),
('SI-053', 'so', 'Kranjska Gora'),
('SI-054', 'so', NULL),
('SI-055', 'so', NULL),
('SI-056', 'so', NULL),
('SI-057', 'so', 'Magaalada Laško'),
('SI-058', 'so', NULL),
('SI-059', 'so', 'Lendava-Lendva'),
('SI-060', 'so', NULL),
('SI-061', 'so', 'Ljubljana'),
('SI-062', 'so', NULL),
('SI-063', 'so', 'Ljutomer'),
('SI-064', 'so', 'Logatec'),
('SI-065', 'so', 'Loska Dolina Degmada'),
('SI-066', 'so', NULL),
('SI-067', 'so', NULL),
('SI-068', 'so', 'Lukovica'),
('SI-069', 'so', NULL),
('SI-070', 'so', 'Magaalada Maribor'),
('SI-071', 'so', NULL),
('SI-072', 'so', NULL),
('SI-073', 'so', 'Metlika'),
('SI-074', 'so', NULL),
('SI-075', 'so', 'Degmada Miren-Kostanjevica'),
('SI-076', 'so', 'Mislinja'),
('SI-077', 'so', NULL),
('SI-078', 'so', 'Moravske Toplice'),
('SI-079', 'so', NULL),
('SI-080', 'so', NULL),
('SI-081', 'so', NULL),
('SI-082', 'so', NULL),
('SI-083', 'so', NULL),
('SI-084', 'so', NULL),
('SI-085', 'so', NULL),
('SI-086', 'so', NULL),
('SI-087', 'so', NULL),
('SI-088', 'so', NULL),
('SI-089', 'so', 'Pesnica'),
('SI-090', 'so', 'Piran-Pirano'),
('SI-091', 'so', 'Pivka'),
('SI-092', 'so', NULL),
('SI-093', 'so', 'Podvelka'),
('SI-094', 'so', 'Postojna'),
('SI-095', 'so', NULL),
('SI-096', 'so', 'Ptuj'),
('SI-097', 'so', NULL),
('SI-098', 'so', NULL),
('SI-099', 'so', 'Radece Degmada'),
('SI-100', 'so', NULL),
('SI-101', 'so', 'Radlje ob Dravi'),
('SI-102', 'so', 'Radovljica'),
('SI-103', 'so', NULL),
('SI-104', 'so', NULL),
('SI-105', 'so', NULL),
('SI-106', 'so', NULL),
('SI-107', 'so', NULL),
('SI-108', 'so', 'Ruse Degmada'),
('SI-109', 'so', NULL),
('SI-110', 'so', 'Magaalada Sevnica'),
('SI-111', 'so', NULL),
('SI-112', 'so', 'Degmada Slovenj Gradec'),
('SI-113', 'so', 'Slovenska Bistrica'),
('SI-114', 'so', 'Slovenska Konjice'),
('SI-115', 'so', NULL),
('SI-116', 'so', 'Degmada Sveti Jurij ob Scavnici'),
('SI-117', 'so', NULL),
('SI-118', 'so', NULL),
('SI-119', 'so', NULL),
('SI-120', 'so', 'Sentjur'),
('SI-121', 'so', NULL),
('SI-122', 'so', 'Skofja Loka'),
('SI-123', 'so', 'Degmada Skofljica'),
('SI-124', 'so', NULL),
('SI-125', 'so', NULL),
('SI-126', 'so', NULL),
('SI-127', 'so', NULL),
('SI-128', 'so', NULL),
('SI-129', 'so', NULL),
('SI-130', 'so', 'Trebnje'),
('SI-131', 'so', NULL),
('SI-132', 'so', NULL),
('SI-133', 'so', NULL),
('SI-134', 'so', NULL),
('SI-135', 'so', NULL),
('SI-136', 'so', NULL),
('SI-137', 'so', NULL),
('SI-138', 'so', NULL),
('SI-139', 'so', NULL),
('SI-140', 'so', NULL),
('SI-141', 'so', NULL),
('SI-142', 'so', 'Magaalada Zagorje ob Savi'),
('SI-143', 'so', NULL),
('SI-144', 'so', 'Zrece Degmada'),
('SI-146', 'so', 'Zelezniki Degmada'),
('SI-147', 'so', NULL),
('SI-148', 'so', NULL),
('SI-149', 'so', 'Degmada Bistrica ob Sotli'),
('SI-150', 'so', NULL),
('SI-151', 'so', NULL),
('SI-152', 'so', NULL),
('SI-153', 'so', NULL),
('SI-154', 'so', NULL),
('SI-155', 'so', 'Dobrna'),
('SI-156', 'so', NULL),
('SI-157', 'so', 'Dolenjske Toplice'),
('SI-158', 'so', 'Grad'),
('SI-159', 'so', 'Hajdina'),
('SI-160', 'so', NULL),
('SI-161', 'so', NULL),
('SI-162', 'so', NULL),
('SI-163', 'so', NULL),
('SI-164', 'so', 'Komenda'),
('SI-165', 'so', NULL),
('SI-166', 'so', NULL),
('SI-167', 'so', 'Degmada Lovrenc na Pohorju'),
('SI-168', 'so', NULL),
('SI-169', 'so', NULL),
('SI-170', 'so', 'Mirna Pec Municipality'),
('SI-171', 'so', 'Oplotnica Municipality'),
('SI-172', 'so', NULL),
('SI-173', 'so', NULL),
('SI-174', 'so', 'Prebold'),
('SI-175', 'so', 'Prevalje'),
('SI-176', 'so', NULL),
('SI-177', 'so', NULL),
('SI-178', 'so', 'Degmada Selnica ob Dravi'),
('SI-179', 'so', NULL),
('SI-180', 'so', 'Solcava Degmada'),
('SI-181', 'so', 'Sveta Ana Municipality'),
('SI-182', 'so', 'Obcina Sveti Andraz v Slovenskih goricah'),
('SI-183', 'so', NULL),
('SI-184', 'so', NULL),
('SI-185', 'so', NULL),
('SI-186', 'so', NULL),
('SI-187', 'so', NULL),
('SI-188', 'so', NULL),
('SI-189', 'so', NULL),
('SI-190', 'so', NULL),
('SI-191', 'so', NULL),
('SI-192', 'so', NULL),
('SI-193', 'so', NULL),
('SI-194', 'so', NULL),
('SI-195', 'so', 'Obcina Apache'),
('SI-196', 'so', NULL),
('SI-197', 'so', 'Degmada Kostanjevica na Krki'),
('SI-198', 'so', NULL),
('SI-199', 'so', 'Mokronog-Trebelno Municipality'),
('SI-200', 'so', 'Obcina Poljcane'),
('SI-201', 'so', 'Rence-Vogrsko'),
('SI-202', 'so', 'Obcina Sredisce ob Dravi'),
('SI-203', 'so', 'Obcina Straza'),
('SI-204', 'so', 'Obcina Sveta Trojica v Slovenskih goricah'),
('SI-205', 'so', 'Obcina Sveti Tomaz'),
('SI-206', 'so', NULL),
('SI-207', 'so', 'Gorje'),
('SI-208', 'so', 'Log-Dragomer'),
('SI-209', 'so', 'Obcina Recica ob Savinji'),
('SI-210', 'so', 'Obcina Sveti Jurij v Slovenskih goricah'),
('SI-211', 'so', 'Sentrupert'),
('SI-212', 'so', 'Mirna'),
('SI-213', 'so', 'Ankaran Municipality');

SET FOREIGN_KEY_CHECKS=1;
