SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_countries_altnames` (`key`, `language_key`, `name`) VALUES
('AG', 'aa', 'Antigua and Barbuda'),
('AG', 'am', 'አንቲጓ እና ባርቡዳ'),
('AG', 'ar', 'أنتيغوا وبربودا'),
('AG', 'az', 'Antiqua və Barbuda'),
('AG', 'be', 'Антыгуа і Барбуда'),
('AG', 'bg', 'Антигуа и Барбуда'),
('AG', 'bn', 'অ্যান্টিগুয়া ও বারবুডা'),
('AG', 'bs', 'Antigva i Barbuda'),
('AG', 'ca', 'Antigua i Barbuda'),
('AG', 'cs', 'Antigua a Barbuda'),
('AG', 'da', 'Antigua og Barbuda'),
('AG', 'de', 'Antigua und Barbuda'),
('AG', 'dv', 'އެންޓިގުއާ އަދި ބާބިއުޑާ'),
('AG', 'dz', 'ཨན་ཊི་གུ་ཝ་ ཨེནཌ་ བྷར་བྷུ་ཌ'),
('AG', 'el', 'Αντίγκουα και Μπαρμπούντα'),
('AG', 'en', 'Antigua and Barbuda'),
('AG', 'es', 'Antigua y Barbuda'),
('AG', 'et', 'Antigua ja Barbuda'),
('AG', 'fa', 'آنتیگوا و باربودا'),
('AG', 'fi', 'Antigua ja Barbuda'),
('AG', 'fo', 'Antigua & Barbuda'),
('AG', 'fr', 'Antigua-et-Barbuda'),
('AG', 'he', 'אנטיגואה וברבודה'),
('AG', 'hr', 'Antigva i Barbuda'),
('AG', 'ht', 'Antigua-et-Barbuda'),
('AG', 'hu', 'Antigua és Barbuda'),
('AG', 'hy', 'Անտիգուա և Բարբուդա'),
('AG', 'id', 'Antigua dan Barbuda'),
('AG', 'is', 'Antígva og Barbúda'),
('AG', 'it', 'Antigua e Barbuda'),
('AG', 'ja', 'アンティグア・バーブーダ'),
('AG', 'ka', 'ანტიგუა და ბარბუდა'),
('AG', 'kk', 'Антигуа және Барбуда'),
('AG', 'kl', 'Antigua aamma Barbuda'),
('AG', 'km', 'អង់ទីហ្គា និង បាប៊ុយដា'),
('AG', 'ko', '앤티가 바부다'),
('AG', 'ky', 'Антигуа жана Барбуда'),
('AG', 'la', 'Antiqua et Barbuda'),
('AG', 'lb', 'Antigua a Barbuda'),
('AG', 'lt', 'Antigva ir Barbuda'),
('AG', 'lv', 'Antigva un Barbuda'),
('AG', 'mh', 'Antigua and Barbuda'),
('AG', 'mk', 'Антига и Барбуда'),
('AG', 'mn', 'Антигуа ба Барбуда'),
('AG', 'ms', 'Antigua dan Barbuda'),
('AG', 'mt', 'Antigua u Barbuda'),
('AG', 'my', 'အန်တီဂွါနှင့် ဘာဘူဒါ'),
('AG', 'ne', 'एन्टिगुआ र बारबुडा'),
('AG', 'nl', 'Antigua en Barbuda'),
('AG', 'no', 'Antigua og Barbuda'),
('AG', 'ny', 'Antigua and Barbuda'),
('AG', 'pl', 'Antigua i Barbuda'),
('AG', 'pt', 'Antígua e Barbuda'),
('AG', 'ro', 'Antigua și Barbuda'),
('AG', 'ru', 'Антигуа и Барбуда'),
('AG', 'rw', 'Antigwa na Baribuda'),
('AG', 'si', 'ඇන්ටිගුවා සහ බාබියුඩාව'),
('AG', 'sk', 'Antigua a Barbuda'),
('AG', 'sl', 'Antigva in Barbuda'),
('AG', 'sm', 'Antigua ma Barbuda'),
('AG', 'so', 'Antigua & Barbuuda'),
('AG', 'sq', 'Antigua e Barbuda'),
('AG', 'sr', 'Антигва и Барбуда'),
('AG', 'sv', 'Antigua och Barbuda'),
('AG', 'sw', 'Antigua na Barbuda'),
('AG', 'tg', 'Антигуа ва Барбуда'),
('AG', 'th', 'แอนติกาและบาร์บูดา'),
('AG', 'tk', 'Antigua we Barbuda'),
('AG', 'tl', 'Antigua at Barbuda'),
('AG', 'to', 'Anitikua mo Palaputa'),
('AG', 'tr', 'Antigua ve Barbuda'),
('AG', 'uk', 'Антигуа і Барбуда'),
('AG', 'ur', 'انٹیگوا اور باربودا'),
('AG', 'uz', 'Antigua va Barbuda'),
('AG', 'vi', 'Antigua và Barbuda'),
('AG', 'zh', '安提瓜和巴布达'),
('AG', 'zu', 'i-Antigua ne-Barbuda');

SET FOREIGN_KEY_CHECKS=1;
