SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('EE-130', 'ro', 'Alutaguse'),
('EE-141', 'ro', 'Anija'),
('EE-142', 'ro', 'Antsla'),
('EE-171', 'ro', 'Elva'),
('EE-184', 'ro', 'Haapsalu'),
('EE-191', 'ro', 'Haljala'),
('EE-198', 'ro', 'Harku'),
('EE-205', 'ro', 'Hiiumaa'),
('EE-214', 'ro', 'Häädemeeste'),
('EE-245', 'ro', 'Jõelähtme'),
('EE-247', 'ro', 'Jõgeva'),
('EE-251', 'ro', 'Jõhvi'),
('EE-255', 'ro', 'Järva'),
('EE-272', 'ro', 'Kadrina'),
('EE-283', 'ro', 'Kambja'),
('EE-284', 'ro', 'Kanepi'),
('EE-291', 'ro', 'Kastre'),
('EE-293', 'ro', 'Kehtna'),
('EE-296', 'ro', 'Keila'),
('EE-303', 'ro', 'Kihnu'),
('EE-305', 'ro', 'Kiili'),
('EE-317', 'ro', 'Kohila'),
('EE-321', 'ro', 'Kohtla-Järve'),
('EE-338', 'ro', 'Kose'),
('EE-353', 'ro', 'Kuusalu'),
('EE-37', 'ro', 'Regiunea Harju'),
('EE-39', 'ro', 'Regiunea Hiiu'),
('EE-424', 'ro', 'Loksa'),
('EE-430', 'ro', 'Lääneranna'),
('EE-431', 'ro', 'Lääne-Harju'),
('EE-432', 'ro', 'Luunja'),
('EE-441', 'ro', 'Lääne-Nigula'),
('EE-442', 'ro', 'Lüganuse'),
('EE-446', 'ro', 'Maardu'),
('EE-45', 'ro', 'Comitatul Ida-Viru'),
('EE-478', 'ro', 'Muhu'),
('EE-480', 'ro', 'Mulgi'),
('EE-486', 'ro', 'Mustvee'),
('EE-50', 'ro', 'Comitatul Jõgeva'),
('EE-503', 'ro', 'Märjamaa'),
('EE-511', 'ro', 'Narva'),
('EE-514', 'ro', 'Narva-Jõesuu'),
('EE-52', 'ro', 'Comitatul Järva'),
('EE-528', 'ro', 'Nõo'),
('EE-557', 'ro', 'Otepää'),
('EE-56', 'ro', 'Comitatul Lääne'),
('EE-567', 'ro', 'Plătit'),
('EE-586', 'ro', 'Peipsiääre'),
('EE-60', 'ro', 'Comitatul Lääne-Viru'),
('EE-615', 'ro', 'Põhja-Sakala'),
('EE-618', 'ro', 'Põltsamaa'),
('EE-622', 'ro', 'Põlva'),
('EE-624', 'ro', 'Pärnu'),
('EE-638', 'ro', 'Põhja-Pärnumaa'),
('EE-64', 'ro', 'Comitatul Põlva'),
('EE-651', 'ro', 'Raasiku'),
('EE-653', 'ro', 'Rae'),
('EE-661', 'ro', 'Rakvere'),
('EE-663', 'ro', 'Rakvere'),
('EE-668', 'ro', 'Rapla'),
('EE-68', 'ro', 'Comitatul Pärnu'),
('EE-689', 'ro', 'Ruhnu'),
('EE-698', 'ro', 'Rõuge'),
('EE-708', 'ro', 'Räpina'),
('EE-71', 'ro', 'Comitatul Rapla'),
('EE-712', 'ro', 'Saarde'),
('EE-714', 'ro', 'Saaremaa'),
('EE-719', 'ro', 'Saku'),
('EE-726', 'ro', 'Saue'),
('EE-732', 'ro', 'Setomaa'),
('EE-735', 'ro', 'Sillamäe'),
('EE-74', 'ro', 'Regiunea Saare'),
('EE-784', 'ro', 'Tallinn'),
('EE-79', 'ro', 'Comitatul Tartu'),
('EE-792', 'ro', 'Tapa'),
('EE-793', 'ro', 'Tartu'),
('EE-796', 'ro', 'Tartu'),
('EE-803', 'ro', 'Toila'),
('EE-809', 'ro', 'Tori'),
('EE-81', 'ro', 'Comitatul Valga'),
('EE-824', 'ro', 'Tõrva'),
('EE-834', 'ro', 'Türi'),
('EE-84', 'ro', 'Regiunea Viljandi'),
('EE-855', 'ro', 'Valga'),
('EE-87', 'ro', 'Comitatul Võru'),
('EE-890', 'ro', 'Viimsi'),
('EE-897', 'ro', 'Viljandi'),
('EE-899', 'ro', 'Viljandi'),
('EE-901', 'ro', 'Vinni'),
('EE-903', 'ro', 'Viru-Nigula'),
('EE-907', 'ro', 'Vormsi'),
('EE-917', 'ro', 'Võru'),
('EE-919', 'ro', 'Võru'),
('EE-928', 'ro', 'Väike-Maarja');

SET FOREIGN_KEY_CHECKS=1;
