SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('RO-AB', 'da', 'Alba'),
('RO-AG', 'da', 'Argeș'),
('RO-AR', 'da', 'Arad'),
('RO-B', 'da', 'Bucuresti'),
('RO-BC', 'da', 'Bacău'),
('RO-BH', 'da', 'Bihor'),
('RO-BN', 'da', 'Bistrița-Năsăud'),
('RO-BR', 'da', 'Brăila'),
('RO-BT', 'da', 'Botoșani'),
('RO-BV', 'da', 'Brașov'),
('RO-BZ', 'da', 'Buzău'),
('RO-CJ', 'da', 'Cluj'),
('RO-CL', 'da', 'Călărași'),
('RO-CS', 'da', 'Caraș-Severin'),
('RO-CT', 'da', 'Constanța'),
('RO-CV', 'da', 'Covasna'),
('RO-DB', 'da', 'Dâmbovița'),
('RO-DJ', 'da', 'Dolj'),
('RO-GJ', 'da', 'Gorj'),
('RO-GL', 'da', 'Galați'),
('RO-GR', 'da', 'Giurgiu'),
('RO-HD', 'da', 'Hunedoara'),
('RO-HR', 'da', 'Harghita'),
('RO-IF', 'da', 'Ilfov'),
('RO-IL', 'da', 'Ialomița'),
('RO-IS', 'da', 'Iași'),
('RO-MH', 'da', 'Mehedinți'),
('RO-MM', 'da', 'Maramureș'),
('RO-MS', 'da', 'Mureș'),
('RO-NT', 'da', 'Neamț'),
('RO-OT', 'da', 'Olt'),
('RO-PH', 'da', 'Prahova'),
('RO-SB', 'da', 'Sibiu'),
('RO-SJ', 'da', 'Sălaj'),
('RO-SM', 'da', 'Satu Mare'),
('RO-SV', 'da', 'Suceava'),
('RO-TL', 'da', 'Tulcea'),
('RO-TM', 'da', 'Timiș'),
('RO-TR', 'da', 'Teleorman'),
('RO-VL', 'da', 'Vâlcea'),
('RO-VN', 'da', 'Vrancea'),
('RO-VS', 'da', 'Vaslui');

SET FOREIGN_KEY_CHECKS=1;
