SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('IS-1', 'is', 'Höfuðborgarsvæði'),
('IS-2', 'is', 'Suðurnes'),
('IS-3', 'is', 'Vesturland'),
('IS-4', 'is', 'Vestfirðir'),
('IS-5', 'is', 'Norðurland Vestra'),
('IS-6', 'is', 'Norðurland Eystra'),
('IS-7', 'is', 'Austurland'),
('IS-8', 'is', 'Suðurland'),
('IS-AKN', 'is', 'Akraneskaupstaður'),
('IS-AKU', 'is', 'Akureyrarbær'),
('IS-ARN', 'is', 'Árneshreppur'),
('IS-ASA', 'is', 'Ásahreppur'),
('IS-BLA', 'is', 'Bláskógabyggð'),
('IS-BOG', 'is', 'Borgarbyggð'),
('IS-BOL', 'is', 'Bolungarvíkurkaupstaður'),
('IS-DAB', 'is', 'Dalabyggð'),
('IS-DAV', 'is', 'Dalvíkurbyggð'),
('IS-EOM', 'is', 'Eyja- og Miklaholtshreppur'),
('IS-EYF', 'is', 'Eyjafjarðarsveit'),
('IS-FJD', 'is', 'Fjarðabyggð'),
('IS-FJL', 'is', 'Fjallabyggð'),
('IS-FLA', 'is', 'Flóahreppur'),
('IS-FLR', 'is', 'Fljótsdalshreppur'),
('IS-GAR', 'is', 'Garðabær'),
('IS-GOG', 'is', 'Grímsnes- og Grafningshreppur'),
('IS-GRN', 'is', 'Grindavíkurbær'),
('IS-GRU', 'is', 'Grundarfjarðarbær'),
('IS-GRY', 'is', 'Grýtubakkahreppur'),
('IS-HAF', 'is', 'Hafnarfjarðarkaupstaður'),
('IS-HRG', 'is', 'Hörgársveit'),
('IS-HRU', 'is', 'Hrunamannahreppur'),
('IS-HUG', 'is', 'Húnabyggð'),
('IS-HUV', 'is', 'Húnaþing vestra'),
('IS-HVA', 'is', 'Hvalfjarðarsveit'),
('IS-HVE', 'is', 'Hveragerðisbær'),
('IS-ISA', 'is', 'Ísafjarðarbær'),
('IS-KAL', 'is', 'Kaldrananeshreppur'),
('IS-KJO', 'is', 'Kjósarhreppur'),
('IS-KOP', 'is', 'Kópavogsbær'),
('IS-LAN', 'is', 'Langanesbyggð'),
('IS-MOS', 'is', 'Mosfellsbær'),
('IS-MUL', 'is', 'Múlaþing'),
('IS-MYR', 'is', 'Mýrdalshreppur'),
('IS-NOR', 'is', 'Norðurþing'),
('IS-RGE', 'is', 'Rangárþing eystra'),
('IS-RGY', 'is', 'Rangárþing ytra'),
('IS-RHH', 'is', 'Reykhólahreppur'),
('IS-RKN', 'is', 'Reykjanesbær'),
('IS-RKV', 'is', 'Reykjavíkurborg'),
('IS-SBT', 'is', 'Svalbarðsstrandarhreppur'),
('IS-SDN', 'is', 'Suðurnesjabær'),
('IS-SDV', 'is', 'Súðavíkurhreppur'),
('IS-SEL', 'is', 'Seltjarnarnesbær'),
('IS-SFA', 'is', 'Sveitarfélagið Árborg'),
('IS-SHF', 'is', 'Sveitarfélagið Hornafjörður'),
('IS-SKF', 'is', 'Skaftárhreppur'),
('IS-SKG', 'is', 'Skagabyggð'),
('IS-SKO', 'is', 'Skorradalshreppur'),
('IS-SKR', 'is', 'Skagafjörður'),
('IS-SNF', 'is', 'Snæfellsbær'),
('IS-SOG', 'is', 'Skeiða- og Gnúpverjahreppur'),
('IS-SOL', 'is', 'Sveitarfélagið Ölfus'),
('IS-SSS', 'is', 'Sveitarfélagið Skagaströnd'),
('IS-STR', 'is', 'Strandabyggð'),
('IS-STY', 'is', 'Stykkishólmsbær'),
('IS-SVG', 'is', 'Sveitarfélagið Vogar'),
('IS-TAL', 'is', 'Tálknafjarðarhreppur'),
('IS-THG', 'is', 'Þingeyjarsveit'),
('IS-TJO', 'is', 'Tjörneshreppur'),
('IS-VEM', 'is', 'Vestmannaeyjabær'),
('IS-VER', 'is', 'Vesturbyggð'),
('IS-VOP', 'is', 'Vopnafjarðarhreppur');

SET FOREIGN_KEY_CHECKS=1;
