SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('GN-B', 'hy', 'Բոկե'),
('GN-BE', 'hy', 'Բեյլա'),
('GN-BF', 'hy', 'Բոֆա'),
('GN-BK', 'hy', 'Բոկե'),
('GN-C', 'hy', 'Կոնակրի շրջան'),
('GN-CO', 'hy', 'Քոյահ'),
('GN-D', 'hy', 'Կինդիա'),
('GN-DB', 'hy', 'Դաբոլա'),
('GN-DI', 'hy', 'Դինգուիրայե'),
('GN-DL', 'hy', 'Դալաբա'),
('GN-DU', 'hy', 'Դուբրեկա'),
('GN-F', 'hy', 'Ֆարանա'),
('GN-FA', 'hy', 'Ֆարանա'),
('GN-FO', 'hy', 'Ֆորեկարիա'),
('GN-FR', 'hy', 'Ֆրիա'),
('GN-GA', 'hy', 'Գաուալ'),
('GN-GU', 'hy', 'Գուեկեդու'),
('GN-K', 'hy', 'Կանկան'),
('GN-KA', 'hy', 'Կանկան'),
('GN-KB', 'hy', 'Կուբիա'),
('GN-KD', 'hy', 'Կինդիա'),
('GN-KE', 'hy', 'Կերուանե'),
('GN-KN', 'hy', 'Կունդարա'),
('GN-KO', 'hy', 'Կուրուսա'),
('GN-KS', 'hy', 'Կիսիդուգու'),
('GN-L', 'hy', 'Լաբե'),
('GN-LA', 'hy', 'Լաբե'),
('GN-LE', 'hy', 'Լելումա'),
('GN-LO', 'hy', 'Լոլա'),
('GN-M', 'hy', 'Մամու'),
('GN-MC', 'hy', 'Մասենտա'),
('GN-MD', 'hy', 'Մանդիանա'),
('GN-ML', 'hy', 'Մալի'),
('GN-MM', 'hy', 'Մամու'),
('GN-N', 'hy', 'Նզերեկորե'),
('GN-NZ', 'hy', 'Նզերեկորե'),
('GN-PI', 'hy', 'Փիթա'),
('GN-SI', 'hy', 'Սիգուիրի'),
('GN-TE', 'hy', 'Տելիմելե'),
('GN-TO', 'hy', 'Տուգե'),
('GN-YO', 'hy', 'Յոմու');

SET FOREIGN_KEY_CHECKS=1;
