SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('CZ-10', 'kl', 'Hlavni tassaavoq Praha'),
('CZ-20', 'kl', 'Stredoceskip kraja'),
('CZ-201', 'kl', 'Benešov'),
('CZ-202', 'kl', 'Berun'),
('CZ-203', 'kl', 'Kladno'),
('CZ-204', 'kl', 'Kolin'),
('CZ-205', 'kl', 'Kutná Hora'),
('CZ-206', 'kl', 'Mělník'),
('CZ-207', 'kl', 'Mladá Boleslav'),
('CZ-208', 'kl', 'Nymburg'),
('CZ-209', 'kl', 'Praha-východ'),
('CZ-20A', 'kl', 'Praha-zapad'),
('CZ-20B', 'kl', 'Příbram'),
('CZ-20C', 'kl', 'Rakovníkimiittoq'),
('CZ-31', 'kl', 'Jihocesky'),
('CZ-311', 'kl', 'České Budejovice-mi'),
('CZ-312', 'kl', 'Český Krumlov'),
('CZ-313', 'kl', 'Jindrychův Hradec'),
('CZ-314', 'kl', 'Písek'),
('CZ-315', 'kl', 'Praktik'),
('CZ-316', 'kl', 'Strakonimik'),
('CZ-317', 'kl', 'Tábor'),
('CZ-32', 'kl', 'Plzensky kr'),
('CZ-321', 'kl', 'Domažlice'),
('CZ-322', 'kl', 'Klatovi'),
('CZ-323', 'kl', NULL),
('CZ-324', 'kl', NULL),
('CZ-325', 'kl', NULL),
('CZ-326', 'kl', 'Rokykany'),
('CZ-327', 'kl', 'Tachov'),
('CZ-41', 'kl', 'Karlovarsky'),
('CZ-411', 'kl', 'Cheb'),
('CZ-412', 'kl', NULL),
('CZ-413', 'kl', 'Sokolov'),
('CZ-42', 'kl', 'Ustecky'),
('CZ-421', 'kl', 'Děčin'),
('CZ-422', 'kl', 'Chomutov'),
('CZ-423', 'kl', 'Litoměřis'),
('CZ-424', 'kl', 'Louny'),
('CZ-425', 'kl', NULL),
('CZ-426', 'kl', 'Teplice'),
('CZ-427', 'kl', 'Ústí aamma Labem'),
('CZ-51', 'kl', 'Liberecky'),
('CZ-511', 'kl', 'Česká Lípa'),
('CZ-512', 'kl', 'Jablonec aamma Nisou'),
('CZ-513', 'kl', NULL),
('CZ-514', 'kl', 'Semily'),
('CZ-52', 'kl', 'Kralovehradecky'),
('CZ-521', 'kl', 'Hradec Králové'),
('CZ-522', 'kl', 'Jičin'),
('CZ-523', 'kl', 'Náchod'),
('CZ-524', 'kl', 'Rychnov aamma Kněžnou'),
('CZ-525', 'kl', 'Trutnov'),
('CZ-53', 'kl', 'Pardubicky'),
('CZ-531', 'kl', 'Krudimi'),
('CZ-532', 'kl', 'Pardubice'),
('CZ-533', 'kl', 'Svitavy'),
('CZ-534', 'kl', 'Ústí aamma Orlicí'),
('CZ-63', 'kl', 'Vysocina'),
('CZ-631', 'kl', 'Havlíčkův Brod'),
('CZ-632', 'kl', 'Jihlava'),
('CZ-633', 'kl', 'Pelhřimov'),
('CZ-634', 'kl', 'Træbič'),
('CZ-635', 'kl', 'Žďár aamma Sázavou'),
('CZ-64', 'kl', 'Jihomoravsky'),
('CZ-641', 'kl', 'Blansko'),
('CZ-642', 'kl', 'Brno-mesto'),
('CZ-643', 'kl', 'Brno-venkov'),
('CZ-644', 'kl', 'Breklav'),
('CZ-645', 'kl', 'Hodonin'),
('CZ-646', 'kl', 'Vyskov'),
('CZ-647', 'kl', 'Znojmo'),
('CZ-71', 'kl', 'Olomoucky'),
('CZ-711', 'kl', 'Jeseník'),
('CZ-712', 'kl', 'Olomouc'),
('CZ-713', 'kl', 'Prostejov'),
('CZ-714', 'kl', 'Perov'),
('CZ-715', 'kl', 'Šumperk'),
('CZ-72', 'kl', 'Zlinsky'),
('CZ-721', 'kl', 'Kroměříž'),
('CZ-722', 'kl', 'Uherské Hradiště'),
('CZ-723', 'kl', 'Vsetín'),
('CZ-724', 'kl', 'Zlín'),
('CZ-80', 'kl', 'Moravskoslezsky'),
('CZ-801', 'kl', 'Bruntal'),
('CZ-802', 'kl', 'Frýdek-Mistek'),
('CZ-803', 'kl', 'Karviná'),
('CZ-804', 'kl', 'Nový Jičin'),
('CZ-805', 'kl', 'Opava'),
('CZ-806', 'kl', 'Ostrava-mesto');

SET FOREIGN_KEY_CHECKS=1;
