SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('MK-101', 'it', 'Veles'),
('MK-102', 'it', 'Gradsko'),
('MK-103', 'it', 'Demir Kapija'),
('MK-104', 'it', 'Kavadarci'),
('MK-105', 'it', 'Lozovo'),
('MK-106', 'it', 'Comune di Negotino'),
('MK-107', 'it', 'Rosoman'),
('MK-108', 'it', 'Sveti Nikole'),
('MK-109', 'it', 'Čaška'),
('MK-201', 'it', 'Berovo'),
('MK-202', 'it', 'Comune di Vinica'),
('MK-203', 'it', 'Delčevo'),
('MK-204', 'it', 'Zrnovci'),
('MK-205', 'it', 'Karbinci'),
('MK-206', 'it', 'Comune di Kočani'),
('MK-207', 'it', 'Makedonska Kamenica'),
('MK-208', 'it', 'Pehčevo'),
('MK-209', 'it', 'Probištip'),
('MK-210', 'it', 'Češinovo-Obleševo'),
('MK-211', 'it', 'Štip'),
('MK-301', 'it', 'Vevčani'),
('MK-303', 'it', 'Debar'),
('MK-304', 'it', 'Debarca'),
('MK-307', 'it', 'Kičevo'),
('MK-308', 'it', 'Makedonski Brod'),
('MK-310', 'it', 'Comune di Ocrida'),
('MK-311', 'it', 'Plasnica'),
('MK-312', 'it', 'Struga'),
('MK-313', 'it', 'Centar Župa'),
('MK-401', 'it', 'Bogdanci'),
('MK-402', 'it', 'Bosilovo'),
('MK-403', 'it', 'Valandovo'),
('MK-404', 'it', 'Vasilevo'),
('MK-405', 'it', 'Gevgelija'),
('MK-406', 'it', 'Dojran'),
('MK-407', 'it', 'Konče'),
('MK-408', 'it', 'Novo Selo'),
('MK-409', 'it', 'Comune di Radoviš'),
('MK-410', 'it', 'Strumica'),
('MK-501', 'it', 'Bitola'),
('MK-502', 'it', 'Demir Hisar'),
('MK-503', 'it', 'Dolneni'),
('MK-504', 'it', 'Krivogaštani'),
('MK-505', 'it', 'Kruševo'),
('MK-506', 'it', 'Mogila'),
('MK-507', 'it', 'Novaci'),
('MK-508', 'it', 'Comune di Prilep'),
('MK-509', 'it', 'Resen'),
('MK-601', 'it', 'Bogovinje'),
('MK-602', 'it', 'Brvenica'),
('MK-603', 'it', 'Vrapčište'),
('MK-604', 'it', 'Gostivar'),
('MK-605', 'it', 'Želino'),
('MK-606', 'it', 'Jegunovce'),
('MK-607', 'it', 'Mavrovo e Rostuša'),
('MK-608', 'it', 'Tearce'),
('MK-609', 'it', 'Municipio di Tetovo'),
('MK-701', 'it', 'Kratovo'),
('MK-702', 'it', 'Kriva Palanka'),
('MK-703', 'it', 'Comune di Kumanovo'),
('MK-704', 'it', 'Lipkovo'),
('MK-705', 'it', 'Rankovce'),
('MK-706', 'it', 'Staro Nagoričane'),
('MK-801', 'it', 'Aerodromo †'),
('MK-802', 'it', 'Aračinovo'),
('MK-803', 'it', 'Butel †'),
('MK-804', 'it', 'Gazi Baba †'),
('MK-805', 'it', 'Gjorče Petrov †'),
('MK-806', 'it', 'Zelenikovo'),
('MK-807', 'it', 'Ilinden'),
('MK-808', 'it', 'Karpoš †'),
('MK-809', 'it', 'Kisela Voda †'),
('MK-810', 'it', 'Petrovec'),
('MK-811', 'it', 'Saraj †'),
('MK-812', 'it', 'Sopište'),
('MK-813', 'it', 'Studeničani'),
('MK-814', 'it', 'Centro †'),
('MK-815', 'it', 'Čair †'),
('MK-816', 'it', 'Čučer-Sandevo'),
('MK-817', 'it', 'Šuto Orizari †');

SET FOREIGN_KEY_CHECKS=1;
