SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_countries_altnames` (`key`, `language_key`, `name`) VALUES
('HM', 'aa', NULL),
('HM', 'am', 'ኽርድ ኣና ማክዶናልድ ደሴቶች'),
('HM', 'ar', 'جزيرة هيرد وجزر ماكدونالد'),
('HM', 'az', 'Herd və Makdonald adaları'),
('HM', 'be', 'Астравы Херд і Макдональд'),
('HM', 'bg', 'острови Хърд и Макдоналд'),
('HM', 'bn', 'হার্ড এবং ম্যাকডোনাল্ড দ্বীপপুঞ্জ'),
('HM', 'bs', 'Ostrvo Heard i arhipelag McDonald'),
('HM', 'ca', 'Illes Heard i McDonald'),
('HM', 'cs', 'Heardův ostrov a McDonaldovy ostrovy'),
('HM', 'da', 'Heard Island og McDonald Islands'),
('HM', 'de', 'Heard und McDonaldinseln'),
('HM', 'dv', 'ހެއާޑް އައިލެންޑާއި މެކްޑޮނަލްޑް އައިލެންޑްސް އެވެ'),
('HM', 'dz', 'ཧཱརཌ་མཚོ་གླིང་ དང་ མེཀ་ཌོ་ནལཌ྄་གླིང་ཚོམ'),
('HM', 'el', 'Νήσοι Χερντ και Μακντόναλντ'),
('HM', 'en', 'Heard & McDonald Islands'),
('HM', 'es', 'Islas Heard y McDonald'),
('HM', 'et', 'Heardi ja McDonaldi saared'),
('HM', 'fa', 'هرد و جزایر مک‌دونالد'),
('HM', 'fi', 'Heard ja McDonaldinsaaret'),
('HM', 'fo', 'Heard og McDonaldoyggjar'),
('HM', 'fr', 'Îles Heard-et-MacDonald'),
('HM', 'he', 'איי הרד ומקדונלד'),
('HM', 'hr', 'Otoci Heard i McDonald'),
('HM', 'ht', 'Îles Heard-et-MacDonald'),
('HM', 'hu', 'Heard-sziget és McDonald-szigetek'),
('HM', 'hy', 'Հերդ կղզի և ՄակԴոնալդի կղզիներ'),
('HM', 'id', 'Pulau Heard dan Kepulauan McDonald'),
('HM', 'is', 'Heard og McDonaldseyjar'),
('HM', 'it', 'Isole Heard e McDonald'),
('HM', 'ja', 'ハード島・マクドナルド諸島'),
('HM', 'ka', 'ჰერდი და მაკდონალდის კუნძულები'),
('HM', 'kk', 'Херд аралы және Макдональд аралдары'),
('HM', 'kl', NULL),
('HM', 'km', 'កោះ​ហឺដនិង​ម៉ាក់ដូណាល់'),
('HM', 'ko', '허드 맥도널드 제도'),
('HM', 'ky', 'Херд жана Макдональд аралдары'),
('HM', 'la', 'Audivit Island et McDonald Islands'),
('HM', 'lb', 'Heard- a McDonald-Inselen'),
('HM', 'lt', 'Herdo ir Makdonaldo Salos'),
('HM', 'lv', 'Hērda sala un Makdonalda salas'),
('HM', 'mh', NULL),
('HM', 'mk', 'Остров Херд и Острови Мекдоналд'),
('HM', 'mn', 'Херд ба Макдональдийн арлууд'),
('HM', 'ms', 'Kepulauan Heard & McDonald'),
('HM', 'mt', 'il-Gżejjer Heard u l-Gżejjer McDonald'),
('HM', 'my', 'ဟတ်ကျွန်းနှင့်မက်ဒေါနယ်ကျွန်းစု'),
('HM', 'ne', 'हर्ड टापु र म्याकडोनाल्ड टापुहरु'),
('HM', 'nl', 'Heard en McDonaldeilanden'),
('HM', 'no', 'Heard- og McDonaldøyene'),
('HM', 'ny', 'Heard Island ndi McDonald Islands'),
('HM', 'pl', 'Wyspy Heard i McDonalda'),
('HM', 'pt', 'Ilhas Heard e McDonald'),
('HM', 'ro', 'Insula Heard și Insulele McDonald'),
('HM', 'ru', 'о-ва Херд и Макдональд'),
('HM', 'rw', 'Icyirwa Hadi n’Ibirwa MakeDonalidi'),
('HM', 'si', 'හර්ඩ් දූපත සහ මැක්ඩොනල්ඩ් දූපත්'),
('HM', 'sk', 'Heardov ostrov a Macdonaldove ostrovy'),
('HM', 'sl', 'Heardov otok in McDonaldovi otoki'),
('HM', 'sm', 'Heard Island ma McDonald Islands'),
('HM', 'so', 'Jasiiradda Haad & MakDonald'),
('HM', 'sq', 'Ishujt Hërd e Mekdonald'),
('HM', 'sr', 'Острво Херд и Мекдоналдова острва'),
('HM', 'sv', 'Heardön och McDonaldöarna'),
('HM', 'sw', 'Kisiwa cha Heard na Visiwa vya McDonald'),
('HM', 'tg', 'Ҷазираи Ҳерд ва Ҷазираҳои Макдоналд'),
('HM', 'th', 'เกาะเฮิร์ดและหมู่เกาะแมกดอนัลด์'),
('HM', 'tk', 'Herd we Makdonald adalary'),
('HM', 'tl', 'Heard Island at McDonald Islands'),
('HM', 'to', 'ʻOtumotu Heati mo Makitonali'),
('HM', 'tr', 'Heard Adası ve McDonald Adaları'),
('HM', 'uk', 'Острови Герд і Макдоналд'),
('HM', 'ur', 'ہیرڈ جزیرہ و میکڈولینڈ جزائر'),
('HM', 'uz', 'Xerd va Makdonald orollari'),
('HM', 'vi', 'Quần đảo Heard và McDonald'),
('HM', 'zh', '赫德岛和麦克唐纳群岛'),
('HM', 'zu', 'I-Heard & McDonald Island');

SET FOREIGN_KEY_CHECKS=1;
