SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('CZ-10', 'ms', 'Prague'),
('CZ-20', 'ms', 'Wilayah Bohemia Tengah'),
('CZ-201', 'ms', 'Benešov'),
('CZ-202', 'ms', 'Beroun'),
('CZ-203', 'ms', 'Kladno'),
('CZ-204', 'ms', 'Kolín'),
('CZ-205', 'ms', 'Kutná Hora'),
('CZ-206', 'ms', 'Mělník'),
('CZ-207', 'ms', 'Mladá Boleslav'),
('CZ-208', 'ms', 'Nymburk'),
('CZ-209', 'ms', 'Praha-východ'),
('CZ-20A', 'ms', 'Praha-západ'),
('CZ-20B', 'ms', 'Příbram'),
('CZ-20C', 'ms', 'Rakovník'),
('CZ-31', 'ms', 'Wilayah Bohemia Selatan'),
('CZ-311', 'ms', 'České Budějovice'),
('CZ-312', 'ms', 'Český Krumlov'),
('CZ-313', 'ms', 'Jindřichův Hradec'),
('CZ-314', 'ms', 'Písek'),
('CZ-315', 'ms', 'Prachatice'),
('CZ-316', 'ms', 'Strakonice'),
('CZ-317', 'ms', 'Tábor'),
('CZ-32', 'ms', 'Plzen Region'),
('CZ-321', 'ms', 'Domažlice'),
('CZ-322', 'ms', 'Klatovy'),
('CZ-323', 'ms', 'Plzeň-město'),
('CZ-324', 'ms', 'Plzeň-jih'),
('CZ-325', 'ms', 'Plzeň-sever'),
('CZ-326', 'ms', 'Rokycany'),
('CZ-327', 'ms', 'Tachov'),
('CZ-41', 'ms', 'Carlsbad Region'),
('CZ-411', 'ms', 'Cheb'),
('CZ-412', 'ms', 'Karlovy Vary'),
('CZ-413', 'ms', 'Sokolov'),
('CZ-42', 'ms', 'Ústí nad Labem Region'),
('CZ-421', 'ms', 'Děčín'),
('CZ-422', 'ms', 'Chomutov'),
('CZ-423', 'ms', 'Litoměřice'),
('CZ-424', 'ms', 'Louny'),
('CZ-425', 'ms', 'Kebanyakan'),
('CZ-426', 'ms', 'Teplice'),
('CZ-427', 'ms', 'Ústí nad Labem'),
('CZ-51', 'ms', 'Liberec Region'),
('CZ-511', 'ms', 'Česká Lípa'),
('CZ-512', 'ms', 'Jablonec nad Nisou'),
('CZ-513', 'ms', 'Liberec'),
('CZ-514', 'ms', 'Semily'),
('CZ-52', 'ms', 'Hradec Králové Region'),
('CZ-521', 'ms', 'Hradec Králové'),
('CZ-522', 'ms', 'Jičín'),
('CZ-523', 'ms', 'Nachod'),
('CZ-524', 'ms', 'Rychnov nad Kněžnou'),
('CZ-525', 'ms', 'Trutnov'),
('CZ-53', 'ms', 'Pardubice Region'),
('CZ-531', 'ms', 'Chrudim'),
('CZ-532', 'ms', 'Pardubice'),
('CZ-533', 'ms', 'Svitavy'),
('CZ-534', 'ms', 'Ústí nad Orlicí'),
('CZ-63', 'ms', 'Vysocina'),
('CZ-631', 'ms', 'Havlíčkův Brod'),
('CZ-632', 'ms', 'Jihlava'),
('CZ-633', 'ms', 'Pelhřimov'),
('CZ-634', 'ms', 'Třebíč'),
('CZ-635', 'ms', 'Žďár nad Sázavou'),
('CZ-64', 'ms', 'Wilayah Moravia Selatan'),
('CZ-641', 'ms', 'Blansko'),
('CZ-642', 'ms', 'Brno-město'),
('CZ-643', 'ms', 'Brno-venkov'),
('CZ-644', 'ms', 'Břeclav'),
('CZ-645', 'ms', 'Hodonín'),
('CZ-646', 'ms', 'Vyškov'),
('CZ-647', 'ms', 'Znojmo'),
('CZ-71', 'ms', 'Olomouc Region'),
('CZ-711', 'ms', 'Jeseník'),
('CZ-712', 'ms', 'Olomouc'),
('CZ-713', 'ms', 'Prostějov'),
('CZ-714', 'ms', 'Přerov'),
('CZ-715', 'ms', 'Šumperk'),
('CZ-72', 'ms', 'Zlin'),
('CZ-721', 'ms', 'Kroměříž'),
('CZ-722', 'ms', 'Uherské Hradiště'),
('CZ-723', 'ms', 'Vsetín'),
('CZ-724', 'ms', 'Zlín'),
('CZ-80', 'ms', 'Moravian-Silesian Region'),
('CZ-801', 'ms', 'Bruntál'),
('CZ-802', 'ms', 'Frýdek-Místek'),
('CZ-803', 'ms', 'Karviná'),
('CZ-804', 'ms', 'Nový Jičín'),
('CZ-805', 'ms', 'Opava'),
('CZ-806', 'ms', 'Ostrava-město');

SET FOREIGN_KEY_CHECKS=1;
