SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('IT-21', 'ms', 'Piedmont'),
('IT-23', 'ms', 'Aosta Valley'),
('IT-25', 'ms', 'Lombardy'),
('IT-32', 'ms', 'Trentino-Alto Adige'),
('IT-34', 'ms', 'Veneto'),
('IT-36', 'ms', 'Friuli Venezia Giulia'),
('IT-42', 'ms', 'Liguria'),
('IT-45', 'ms', 'Emilia-Romagna'),
('IT-52', 'ms', 'Tuscany'),
('IT-55', 'ms', 'Umbria'),
('IT-57', 'ms', 'The Marches'),
('IT-62', 'ms', 'Latium'),
('IT-65', 'ms', 'Abruzzo'),
('IT-67', 'ms', 'Molise'),
('IT-72', 'ms', 'Campania'),
('IT-75', 'ms', 'Apulia'),
('IT-77', 'ms', 'Basilicate'),
('IT-78', 'ms', 'Calabria'),
('IT-82', 'ms', 'Sicily'),
('IT-88', 'ms', 'Sardinia'),
('IT-AG', 'ms', 'Agrigento'),
('IT-AL', 'ms', 'Alessandria'),
('IT-AN', 'ms', 'Ancona'),
('IT-AP', 'ms', 'Ascoli Piceno'),
('IT-AQ', 'ms', 'L''Aquila'),
('IT-AR', 'ms', 'Arezzo'),
('IT-AT', 'ms', 'Asti'),
('IT-AV', 'ms', 'Avellino'),
('IT-BA', 'ms', 'Bari'),
('IT-BG', 'ms', 'Bergamo'),
('IT-BI', 'ms', 'Biella'),
('IT-BL', 'ms', 'Belluno'),
('IT-BN', 'ms', 'Benevento'),
('IT-BO', 'ms', 'Bologna'),
('IT-BR', 'ms', 'Brindisi'),
('IT-BS', 'ms', 'Brescia'),
('IT-BT', 'ms', 'Barletta-Andria-Trani'),
('IT-BZ', 'ms', 'Bolzano'),
('IT-CA', 'ms', 'Cagliari'),
('IT-CB', 'ms', 'Campobasso'),
('IT-CE', 'ms', 'Caserta'),
('IT-CH', 'ms', 'Chieti'),
('IT-CL', 'ms', 'Caltanissetta'),
('IT-CN', 'ms', 'Cuneo'),
('IT-CO', 'ms', 'Como'),
('IT-CR', 'ms', 'Cremona'),
('IT-CS', 'ms', 'Cosenza'),
('IT-CT', 'ms', 'Catania'),
('IT-CZ', 'ms', 'Catanzaro'),
('IT-EN', 'ms', 'Enna'),
('IT-FC', 'ms', 'Forlì-Cesena'),
('IT-FE', 'ms', 'Ferrara'),
('IT-FG', 'ms', 'Foggia'),
('IT-FI', 'ms', 'Firenze'),
('IT-FM', 'ms', 'Fermo'),
('IT-FR', 'ms', 'Frosinone'),
('IT-GE', 'ms', 'Genova'),
('IT-GO', 'ms', 'Gorizia'),
('IT-GR', 'ms', 'Grosseto'),
('IT-IM', 'ms', 'Imperia'),
('IT-IS', 'ms', 'Isernia'),
('IT-KR', 'ms', 'Crotone'),
('IT-LC', 'ms', 'Lecco'),
('IT-LE', 'ms', 'Lecce'),
('IT-LI', 'ms', 'Livorno'),
('IT-LO', 'ms', 'Lodi'),
('IT-LT', 'ms', 'Latina'),
('IT-LU', 'ms', 'Lucca'),
('IT-MB', 'ms', 'Monza dan Brianza'),
('IT-MC', 'ms', 'Macerata'),
('IT-ME', 'ms', 'Messina'),
('IT-MI', 'ms', 'Milano'),
('IT-MN', 'ms', 'Mantova'),
('IT-MO', 'ms', 'Modena'),
('IT-MS', 'ms', 'Massa-Carrara'),
('IT-MT', 'ms', 'Matera'),
('IT-NA', 'ms', 'Napoli'),
('IT-NO', 'ms', 'Novara'),
('IT-NU', 'ms', 'Nuoro'),
('IT-OR', 'ms', 'Oristano'),
('IT-PA', 'ms', 'Palermo'),
('IT-PC', 'ms', 'Piacenza'),
('IT-PD', 'ms', 'Padova'),
('IT-PE', 'ms', 'Pescara'),
('IT-PG', 'ms', 'Perugia'),
('IT-PI', 'ms', 'Pisa'),
('IT-PN', 'ms', 'Pordenone'),
('IT-PO', 'ms', 'Prato'),
('IT-PR', 'ms', 'Parma'),
('IT-PT', 'ms', 'Pistoia'),
('IT-PU', 'ms', 'Pesaro e Urbino'),
('IT-PV', 'ms', 'Pavia'),
('IT-PZ', 'ms', 'Potenza'),
('IT-RA', 'ms', 'Ravenna'),
('IT-RC', 'ms', 'Reggio Calabria'),
('IT-RE', 'ms', 'Reggio Emilia'),
('IT-RG', 'ms', 'Ragusa'),
('IT-RI', 'ms', 'Rieti'),
('IT-RM', 'ms', 'Roma'),
('IT-RN', 'ms', 'Rimini'),
('IT-RO', 'ms', 'Rovigo'),
('IT-SA', 'ms', 'Salerno'),
('IT-SI', 'ms', 'Siena'),
('IT-SO', 'ms', 'Sondrio'),
('IT-SP', 'ms', 'La Spezia'),
('IT-SR', 'ms', 'Siracusa'),
('IT-SS', 'ms', 'Sassari'),
('IT-SU', 'ms', 'Sud Sardegna'),
('IT-SV', 'ms', 'Savona'),
('IT-TA', 'ms', 'Taranto'),
('IT-TE', 'ms', 'Teramo'),
('IT-TN', 'ms', 'Trento'),
('IT-TO', 'ms', 'Torino'),
('IT-TP', 'ms', 'Trapani'),
('IT-TR', 'ms', 'Terni'),
('IT-TS', 'ms', 'Trieste'),
('IT-TV', 'ms', 'Treviso'),
('IT-UD', 'ms', 'Udine'),
('IT-VA', 'ms', 'Varese'),
('IT-VB', 'ms', 'Verbano-Cusio-Ossola'),
('IT-VC', 'ms', 'Vercelli'),
('IT-VE', 'ms', 'Venezia'),
('IT-VI', 'ms', 'Vicenza'),
('IT-VR', 'ms', 'Verona'),
('IT-VT', 'ms', 'Viterbo'),
('IT-VV', 'ms', 'Vibo Valentia');

SET FOREIGN_KEY_CHECKS=1;
