SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('KE-01', 'ny', 'Baringo'),
('KE-02', 'ny', 'Bomet County'),
('KE-03', 'ny', 'Bungoma County'),
('KE-04', 'ny', 'Busia County'),
('KE-05', 'ny', 'Marakwet District'),
('KE-06', 'ny', 'Embu County'),
('KE-07', 'ny', 'Garissa County'),
('KE-08', 'ny', 'Homa Bay County'),
('KE-09', 'ny', 'Isiolo County'),
('KE-10', 'ny', 'Kajiado County'),
('KE-11', 'ny', 'Kakamega County'),
('KE-12', 'ny', 'Kericho County'),
('KE-13', 'ny', 'Kiambu County'),
('KE-14', 'ny', 'Kilifi County'),
('KE-15', 'ny', 'Kirinyaga County'),
('KE-16', 'ny', 'Kisii County'),
('KE-17', 'ny', 'Kisumu County'),
('KE-18', 'ny', 'Kitui County'),
('KE-19', 'ny', 'Kwale County'),
('KE-20', 'ny', 'Laikipia'),
('KE-21', 'ny', 'Lamu old town'),
('KE-22', 'ny', 'Machakos County'),
('KE-23', 'ny', 'Makueni County'),
('KE-24', 'ny', 'Mandera County'),
('KE-25', 'ny', 'Marsabit County'),
('KE-26', 'ny', 'Meru County'),
('KE-27', 'ny', 'Migori County'),
('KE-28', 'ny', 'Mombasa County'),
('KE-29', 'ny', 'Muranga County'),
('KE-30', 'ny', 'Nairobi County'),
('KE-31', 'ny', 'Nakuru County'),
('KE-32', 'ny', 'Nandi'),
('KE-33', 'ny', 'Narok County'),
('KE-34', 'ny', 'Nyamira county'),
('KE-35', 'ny', 'Nyandarua County'),
('KE-36', 'ny', 'Nyeri County'),
('KE-37', 'ny', 'Samburu County'),
('KE-38', 'ny', 'Siaya County'),
('KE-39', 'ny', 'Taita-Taveta County'),
('KE-40', 'ny', 'Tana River County'),
('KE-41', 'ny', 'Tharaka Nithi County'),
('KE-42', 'ny', 'Trans-Nzoia county'),
('KE-43', 'ny', 'Turkana County'),
('KE-44', 'ny', 'Uasin Gishu County'),
('KE-45', 'ny', 'Vihiga County'),
('KE-46', 'ny', 'Wajir County'),
('KE-47', 'ny', 'West Pokot County');

SET FOREIGN_KEY_CHECKS=1;
