SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('LT-01', 'et', 'Akmenė'),
('LT-02', 'et', 'Alytaus miestas'),
('LT-03', 'et', 'Alytus'),
('LT-04', 'et', 'Anykščiai'),
('LT-05', 'et', 'Birštonas'),
('LT-06', 'et', 'Biržai'),
('LT-07', 'et', 'Druskininkai'),
('LT-08', 'et', 'Elektrėnai'),
('LT-09', 'et', 'Ignalina'),
('LT-10', 'et', 'Jonava'),
('LT-11', 'et', 'Joniškis'),
('LT-12', 'et', 'Jurbarkas'),
('LT-13', 'et', 'Kaišiadorys'),
('LT-14', 'et', 'Kalvarija'),
('LT-15', 'et', 'Kauno miestas'),
('LT-16', 'et', 'Kaunas'),
('LT-17', 'et', 'Kazlų Rūdos'),
('LT-18', 'et', 'Kėdainiai'),
('LT-19', 'et', 'Kelmė'),
('LT-20', 'et', 'Klaipedos miestas'),
('LT-21', 'et', 'Klaipėda'),
('LT-22', 'et', 'Kretinga'),
('LT-23', 'et', 'Kupiškis'),
('LT-24', 'et', 'Lazdijai'),
('LT-25', 'et', 'Marijampolė'),
('LT-26', 'et', 'Mažeikiai'),
('LT-27', 'et', 'Molėtai'),
('LT-28', 'et', 'Neringa'),
('LT-29', 'et', 'Pagėgiai'),
('LT-30', 'et', 'Pakruojis'),
('LT-31', 'et', 'Palangos miestas'),
('LT-32', 'et', 'Panevėžio miestas'),
('LT-33', 'et', 'Panevėžys'),
('LT-34', 'et', 'Pasvalys'),
('LT-35', 'et', 'Plungė'),
('LT-36', 'et', 'Prienai'),
('LT-37', 'et', 'Radviliškis'),
('LT-38', 'et', 'Raseiniai'),
('LT-39', 'et', 'Rietavas'),
('LT-40', 'et', 'Rokiškis'),
('LT-41', 'et', 'Šakiai'),
('LT-42', 'et', 'Šalčininkai'),
('LT-43', 'et', 'Šiaulių miestas'),
('LT-44', 'et', 'Šiauliai'),
('LT-45', 'et', 'Šilalė'),
('LT-46', 'et', 'Šilutė'),
('LT-47', 'et', 'Širvintos'),
('LT-48', 'et', 'Skuodas'),
('LT-49', 'et', 'Švenčionys'),
('LT-50', 'et', 'Tauragė'),
('LT-51', 'et', 'Telšiai'),
('LT-52', 'et', 'Trakai'),
('LT-53', 'et', 'Ukmergė'),
('LT-54', 'et', 'Utena'),
('LT-55', 'et', 'Varėna'),
('LT-56', 'et', 'Vilkaviškis'),
('LT-57', 'et', 'Vilniaus miestas'),
('LT-58', 'et', 'Vilnius'),
('LT-59', 'et', 'Visaginas'),
('LT-60', 'et', 'Zarasai'),
('LT-AL', 'et', 'Alytuse maakond'),
('LT-KL', 'et', 'Klaipėda maakond'),
('LT-KU', 'et', 'Kaunase maakond'),
('LT-MR', 'et', 'Marijampolė maakond'),
('LT-PN', 'et', 'Panevėžysi maakond'),
('LT-SA', 'et', 'Šiauliai maakond'),
('LT-TA', 'et', 'Tauragė maakond'),
('LT-TE', 'et', 'Telšiai maakond'),
('LT-UT', 'et', 'Utena maakond'),
('LT-VL', 'et', 'Vilniuse maakond');

SET FOREIGN_KEY_CHECKS=1;
