SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('BF-01', 'fo', 'Boucle du Mouhoun'),
('BF-02', 'fo', 'Cascades'),
('BF-03', 'fo', 'Centre'),
('BF-04', 'fo', 'Centre-Est'),
('BF-05', 'fo', 'Centre-Nord'),
('BF-06', 'fo', 'Centre-Ouest'),
('BF-07', 'fo', 'Centre-Sud'),
('BF-08', 'fo', 'Est'),
('BF-09', 'fo', 'Hauts-Bassins'),
('BF-10', 'fo', NULL),
('BF-11', 'fo', 'Plateau-Central'),
('BF-12', 'fo', 'Sahel'),
('BF-13', 'fo', 'Sud-Ouest'),
('BF-BAL', 'fo', 'Balé'),
('BF-BAM', 'fo', 'Bam'),
('BF-BAN', 'fo', 'Banva'),
('BF-BAZ', 'fo', 'Bazega'),
('BF-BGR', 'fo', 'Búgúriba'),
('BF-BLG', 'fo', 'Boulgou'),
('BF-BLK', 'fo', 'Boulkiemdé'),
('BF-COM', 'fo', 'Komoé'),
('BF-GAN', 'fo', 'Ganzourgou'),
('BF-GNA', 'fo', 'Gnagna'),
('BF-GOU', 'fo', 'Gourmatur'),
('BF-HOU', 'fo', 'Houet'),
('BF-IOB', 'fo', 'Ioba'),
('BF-KAD', 'fo', 'Kadiogo'),
('BF-KEN', 'fo', 'Kénédugou'),
('BF-KMD', 'fo', 'Komondjari'),
('BF-KMP', 'fo', 'Kompienga'),
('BF-KOP', 'fo', 'Koulpélogo'),
('BF-KOS', 'fo', 'Kossi'),
('BF-KOT', 'fo', 'Kouritenga'),
('BF-KOW', 'fo', 'Kourveogo'),
('BF-LER', 'fo', 'Leraba'),
('BF-LOR', 'fo', 'Lórum'),
('BF-MOU', 'fo', 'Mouhoun'),
('BF-NAM', 'fo', NULL),
('BF-NAO', 'fo', 'Nahouri'),
('BF-NAY', 'fo', 'Najala'),
('BF-NOU', 'fo', 'Noumbiel'),
('BF-OUB', 'fo', 'Oubritenga'),
('BF-OUD', 'fo', NULL),
('BF-PAS', 'fo', 'Passoré'),
('BF-PON', 'fo', 'Poni'),
('BF-SEN', 'fo', 'Séno'),
('BF-SIS', 'fo', 'Sissili'),
('BF-SMT', 'fo', 'Sanmatenga'),
('BF-SNG', 'fo', 'Sanguí'),
('BF-SOM', 'fo', 'Súm'),
('BF-SOR', 'fo', NULL),
('BF-TAP', 'fo', 'Tapoa'),
('BF-TUI', 'fo', NULL),
('BF-YAG', 'fo', 'Jaga'),
('BF-YAT', 'fo', 'Jatenga'),
('BF-ZIR', 'fo', 'Ziro'),
('BF-ZON', 'fo', 'Zondoma'),
('BF-ZOU', 'fo', 'Soundveogo');

SET FOREIGN_KEY_CHECKS=1;
