SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_currencies_altnames` (`key`, `language_key`, `name`) VALUES
('AED', 'lb', 'VAE-Dirham'),
('AFN', 'lb', 'Afghanesch Afghani'),
('ALL', 'lb', 'Albanesche Lek'),
('AMD', 'lb', 'Armeneschen Dram'),
('AOA', 'lb', 'Angolanesche Kwanza'),
('ARS', 'lb', 'Argentinesche Peso'),
('AUD', 'lb', 'Australeschen Dollar'),
('AWG', 'lb', 'Aruba-Florin'),
('AZN', 'lb', 'Aserbaidschan-Manat'),
('BAM', 'lb', 'Bosnien an Herzegowina Konvertéierbar Mark'),
('BBD', 'lb', 'Barbados-Dollar'),
('BDT', 'lb', 'Bangladesch-Taka'),
('BHD', 'lb', 'Bahrain-Dinar'),
('BIF', 'lb', 'Burundi-Frang'),
('BMD', 'lb', 'Bermuda-Dollar'),
('BND', 'lb', 'Brunei-Dollar'),
('BOB', 'lb', 'Bolivianesche Boliviano'),
('BOV', 'lb', 'Bolivianseche Mvdol'),
('BRL', 'lb', 'Brasilianesche Real'),
('BSD', 'lb', 'Bahama-Dollar'),
('BTN', 'lb', 'Bhutan-Ngultrum'),
('BWP', 'lb', 'Botswanesch Pula'),
('BYN', 'lb', 'Wäissrussesche Rubel'),
('BZD', 'lb', 'Belize-Dollar'),
('CAD', 'lb', 'Kanadeschen Dollar'),
('CDF', 'lb', 'Kongo-Frang'),
('CHE', 'lb', 'WIR-Euro'),
('CHF', 'lb', 'Schwäizer Frang'),
('CHW', 'lb', 'WIR-Frang'),
('CLF', 'lb', 'Chileneschen Unidad de Fomento'),
('CLP', 'lb', 'Chilenesche Peso'),
('CNY', 'lb', 'Renminbi Yuan'),
('COP', 'lb', 'Kolumbianesche Peso'),
('COU', 'lb', 'Unidad de Valor Real'),
('CRC', 'lb', 'Costa-Rica-Colón'),
('CUP', 'lb', 'Kubanesche Peso'),
('CVE', 'lb', 'Kap-Verde-Escudo'),
('CZK', 'lb', 'Tschechesch Kroun'),
('DJF', 'lb', 'Dschibuti-Frang'),
('DKK', 'lb', 'Dänesch Kroun'),
('DOP', 'lb', 'Dominikanesche Peso'),
('DZD', 'lb', 'Algereschen Dinar'),
('EGP', 'lb', 'Egyptescht Pond'),
('ERN', 'lb', 'Eritréieschen Nakfa'),
('ETB', 'lb', 'Ethiopescht Birr'),
('EUR', 'lb', 'Euro'),
('FJD', 'lb', 'Fidschi-Dollar'),
('FKP', 'lb', 'Falkland-Pond'),
('GBP', 'lb', 'Britescht Pond'),
('GEL', 'lb', 'Georgesche Lari'),
('GHS', 'lb', 'Ghanaeschen Cedi'),
('GIP', 'lb', 'Gibraltar-Pond'),
('GMD', 'lb', 'Gambia-Dalasi'),
('GNF', 'lb', 'Guinea-Frang'),
('GTQ', 'lb', 'Guatemaltekesche Quetzal'),
('GYD', 'lb', 'Guyana-Dollar'),
('HKD', 'lb', 'Hong-Kong-Dollar'),
('HNL', 'lb', 'Honduras-Lempira'),
('HTG', 'lb', 'Haitianesch Gourde'),
('HUF', 'lb', 'Ungaresche Forint'),
('IDR', 'lb', 'Indonesesch Rupiah'),
('ILS', 'lb', 'Israeleschen Neie Schekel'),
('INR', 'lb', 'Indesch Rupie'),
('IQD', 'lb', 'Irakeschen Dinar'),
('IRR', 'lb', 'Iranesch Rial'),
('ISK', 'lb', 'Islännesch Kroun'),
('JMD', 'lb', 'Jamaika-Dollar'),
('JOD', 'lb', 'Jordaneschen Dinar'),
('JPY', 'lb', 'Japanesche Yen'),
('KES', 'lb', 'Kenia-Schilling'),
('KGS', 'lb', 'Kirgisesche Som'),
('KHR', 'lb', 'Kambodschanesche Riel'),
('KMF', 'lb', 'Komore-Frang'),
('KPW', 'lb', 'Nordkoreanesche Won'),
('KRW', 'lb', 'Südkoreanesche Won'),
('KWD', 'lb', 'Kuwait-Dinar'),
('KYD', 'lb', 'Kaiman-Dollar'),
('KZT', 'lb', 'Kasacheschen Tenge'),
('LAK', 'lb', 'Laoteschen Kip'),
('LBP', 'lb', 'Libanesescht Pond'),
('LKR', 'lb', 'Sri-Lanka-Rupie'),
('LRD', 'lb', 'Liberianeschen Dollar'),
('LSL', 'lb', 'Loti'),
('LYD', 'lb', 'Libeschen Dinar'),
('MAD', 'lb', 'Marokkaneschen Dirham'),
('MDL', 'lb', 'Moldawesche Leu'),
('MGA', 'lb', 'Madagaskar-Ariary'),
('MKD', 'lb', 'Mazedoneschen Denar'),
('MMK', 'lb', 'Myanmaresche Kyat'),
('MNT', 'lb', 'Mongoleschen Tögrög'),
('MOP', 'lb', 'Macau-Pataca'),
('MRU', 'lb', 'Mauretaneschen Ouguiya'),
('MUR', 'lb', 'Mauritius-Rupie'),
('MVR', 'lb', 'Maldiven-Rupie'),
('MWK', 'lb', 'Malawi-Kwacha'),
('MXN', 'lb', 'Mexikanesche Peso'),
('MXV', 'lb', 'Mexikaneschen Unidad de Inversion (UDI)'),
('MYR', 'lb', 'Malayseschen Ringgit'),
('MZN', 'lb', 'Mosambikanesche Metical'),
('NAD', 'lb', 'Namibia-Dollar'),
('NGN', 'lb', 'Nigerianeschen Naira'),
('NIO', 'lb', 'Nicaraguanesche Córdoba'),
('NOK', 'lb', 'Norwegesch Kroun'),
('NPR', 'lb', 'Nepalesesch Rupie'),
('NZD', 'lb', 'Neiséiland-Dollar'),
('OMR', 'lb', 'Omanesche Rial'),
('PAB', 'lb', 'Panamaesche Balboa'),
('PEN', 'lb', 'Peruaneschen Sol'),
('PGK', 'lb', 'Papua-Neiguinéiesche Kina'),
('PHP', 'lb', 'Philippinnesche Peso'),
('PKR', 'lb', 'Pakistanesch Rupie'),
('PLN', 'lb', 'Polneschen Zloty'),
('PYG', 'lb', 'Paraguayeschen Guaraní'),
('QAR', 'lb', 'Katar-Riyal'),
('RON', 'lb', 'Rumänesche Leu'),
('RSD', 'lb', 'Serbeschen Dinar'),
('RUB', 'lb', 'Russesche Rubel'),
('RWF', 'lb', 'Ruanda-Frang'),
('SAR', 'lb', 'Saudi-Rial'),
('SBD', 'lb', 'Salomonen-Dollar'),
('SCR', 'lb', 'Seychellen-Rupie'),
('SDG', 'lb', 'Sudanesescht Pond'),
('SEK', 'lb', 'Schwedesch Kroun'),
('SGD', 'lb', 'Singapur-Dollar'),
('SHP', 'lb', 'St. Helena-Pond'),
('SLE', 'lb', 'Sierra-leonesche Leone'),
('SOS', 'lb', 'Somalia-Schilling'),
('SRD', 'lb', 'Surinameschen Dollar'),
('SSP', 'lb', 'Südsudanesescht Pond'),
('STN', 'lb', 'São-toméeschen Dobra'),
('SVC', 'lb', 'El-Salvador-Colón'),
('SYP', 'lb', 'Syrescht Pond'),
('SZL', 'lb', 'Swasilännesche Lilangeni'),
('THB', 'lb', 'Thailännesche Baht'),
('TJS', 'lb', 'Tadschikistan-Somoni'),
('TMT', 'lb', 'Turkmenistan-Manat'),
('TND', 'lb', 'Tuneseschen Dinar'),
('TOP', 'lb', 'Tongaeschen Paʻanga'),
('TRY', 'lb', 'Tierkesch Lira'),
('TTD', 'lb', 'Trinidad-an-Tobago-Dollar'),
('TWD', 'lb', 'Neien Taiwan-Dollar'),
('TZS', 'lb', 'Tansania-Schilling'),
('UAH', 'lb', 'Ukraineschen Hrywnja'),
('UGX', 'lb', 'Uganda-Schilling'),
('USD', 'lb', 'US-Dollar'),
('USN', 'lb', 'US Dollar (Nächsten Dag)'),
('UYI', 'lb', 'Uruguay Peso en Unidades Indexadas (UI)'),
('UYU', 'lb', 'Uruguayesche Peso'),
('UYW', 'lb', 'Unidad Previsional'),
('UZS', 'lb', 'Usbekistan-Sum'),
('VED', 'lb', 'Bolívar Soberano'),
('VES', 'lb', 'Venezolanesche Bolívar'),
('VND', 'lb', 'Vietnameseschen Dong'),
('VUV', 'lb', 'Vanuatu-Vatu'),
('WST', 'lb', 'Samoaneschen Tala'),
('XAD', 'lb', 'Arab Accounting Dinar'),
('XAF', 'lb', 'CFA-Frang (BEAC)'),
('XAG', 'lb', 'Onze Sëlwer'),
('XAU', 'lb', 'Onze Gold'),
('XBA', 'lb', 'Europäesch Rechnungseenheet'),
('XBB', 'lb', 'Europäesch Währungseenheet (XBB)'),
('XBC', 'lb', 'Europäesch Rechnungseenheet (XBC)'),
('XBD', 'lb', 'Europäesch Rechnungseenheet (XBD)'),
('XCD', 'lb', 'Ostkaribeschen Dollar'),
('XCG', 'lb', 'Caribbean Guilder'),
('XDR', 'lb', 'Sonnerzéiungsrecht'),
('XOF', 'lb', 'CFA-Frang (BCEAO)'),
('XPD', 'lb', 'Onz Palladium'),
('XPF', 'lb', 'CFP-Frang'),
('XPT', 'lb', 'Onz Platin'),
('XSU', 'lb', 'Sucre'),
('XTS', 'lb', 'Testwährung'),
('XUA', 'lb', 'ADB Unit of Account'),
('XXX', 'lb', 'Onbekannt Währung'),
('YER', 'lb', 'Jemen-Rial'),
('ZAR', 'lb', 'Südafrikanesche Rand'),
('ZMW', 'lb', 'Kwacha'),
('ZWG', 'lb', 'Zimbabwe Gold');

SET FOREIGN_KEY_CHECKS=1;
