SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('ES-A', 'it', 'Alicante'),
('ES-AB', 'it', 'Albacete'),
('ES-AL', 'it', 'Almería'),
('ES-AN', 'it', 'Andalusia'),
('ES-AR', 'it', 'Aragona'),
('ES-AS', 'it', 'Principato delle Asturie'),
('ES-AV', 'it', 'Ávila'),
('ES-B', 'it', 'Barcellona [Barcellona]'),
('ES-BA', 'it', 'Badajoz'),
('ES-BI', 'it', 'Bizkaia'),
('ES-BU', 'it', 'Burgos'),
('ES-C', 'it', 'A Coruña [La Coruña]'),
('ES-CA', 'it', 'Cadice'),
('ES-CB', 'it', 'Cantabria'),
('ES-CC', 'it', 'Cáceres'),
('ES-CE', 'it', 'Ceuta'),
('ES-CL', 'it', 'Castiglia e León'),
('ES-CM', 'it', 'Castiglia-La Mancia'),
('ES-CN', 'it', 'Isole Canarie'),
('ES-CO', 'it', 'Córdoba'),
('ES-CR', 'it', 'Ciudad Real'),
('ES-CS', 'it', 'Castellón'),
('ES-CT', 'it', 'Catalogna'),
('ES-CU', 'it', 'Cuenca'),
('ES-EX', 'it', 'Estremadura'),
('ES-GA', 'it', 'Galizia'),
('ES-GC', 'it', 'Las Palmas'),
('ES-GI', 'it', 'Girona [Gerona]'),
('ES-GR', 'it', 'Granada'),
('ES-GU', 'it', 'Guadalajara'),
('ES-H', 'it', 'Huelva'),
('ES-HU', 'it', 'Huesca'),
('ES-IB', 'it', 'Isole Baleari'),
('ES-J', 'it', 'Jaén'),
('ES-L', 'it', 'Lleida [Lérida]'),
('ES-LE', 'it', 'Leone'),
('ES-LO', 'it', 'La Rioja'),
('ES-LU', 'it', 'Lugo [Lugo]'),
('ES-M', 'it', 'Madrid'),
('ES-MA', 'it', 'Malaga'),
('ES-MC', 'it', 'Provincia di Murcia'),
('ES-MD', 'it', 'Madrid'),
('ES-ML', 'it', 'Melilla'),
('ES-MU', 'it', 'Murcia'),
('ES-NA', 'it', 'Navarra'),
('ES-NC', 'it', 'Navarra'),
('ES-O', 'it', 'Asturie'),
('ES-OR', 'it', 'Ourense [Orense]'),
('ES-P', 'it', 'Palencia'),
('ES-PM', 'it', 'Illes Balears [Isole Baleari]'),
('ES-PO', 'it', 'Pontevedra [Pontevedra]'),
('ES-PV', 'it', 'Paesi Baschi'),
('ES-RI', 'it', 'La Rioja'),
('ES-S', 'it', 'Cantabria'),
('ES-SA', 'it', 'Salamanca'),
('ES-SE', 'it', 'Siviglia'),
('ES-SG', 'it', 'Segovia'),
('ES-SO', 'it', 'Soria'),
('ES-SS', 'it', 'Gipuzkoa'),
('ES-T', 'it', 'Tarragona [Tarragona]'),
('ES-TE', 'it', 'Teruel'),
('ES-TF', 'it', 'Santa Cruz de Tenerife'),
('ES-TO', 'it', 'Toledo'),
('ES-V', 'it', 'Valencia'),
('ES-VA', 'it', 'Valladolid'),
('ES-VC', 'it', 'Valenza'),
('ES-VI', 'it', 'Álava'),
('ES-Z', 'it', 'Saragozza'),
('ES-ZA', 'it', 'Zamora');

SET FOREIGN_KEY_CHECKS=1;
