SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('LV-002', 'km', NULL),
('LV-007', 'km', NULL),
('LV-011', 'km', 'អាដាហ្សូណូវ៉ាដ'),
('LV-015', 'km', NULL),
('LV-016', 'km', NULL),
('LV-022', 'km', 'សេស៊ូណូវ៉ាដ'),
('LV-026', 'km', NULL),
('LV-033', 'km', NULL),
('LV-041', 'km', NULL),
('LV-042', 'km', NULL),
('LV-047', 'km', NULL),
('LV-050', 'km', NULL),
('LV-052', 'km', NULL),
('LV-054', 'km', NULL),
('LV-056', 'km', NULL),
('LV-058', 'km', NULL),
('LV-059', 'km', 'ម៉ាដូណា ណូវ៉ាដ'),
('LV-062', 'km', NULL),
('LV-067', 'km', NULL),
('LV-068', 'km', NULL),
('LV-073', 'km', 'ព្រីលូណូវ៉ាដ'),
('LV-077', 'km', NULL),
('LV-080', 'km', NULL),
('LV-087', 'km', NULL),
('LV-088', 'km', NULL),
('LV-089', 'km', 'សូលក្រាស្ទូ ណូវ៉ាដ'),
('LV-091', 'km', NULL),
('LV-094', 'km', NULL),
('LV-097', 'km', NULL),
('LV-099', 'km', NULL),
('LV-101', 'km', NULL),
('LV-102', 'km', NULL),
('LV-106', 'km', NULL),
('LV-111', 'km', NULL),
('LV-112', 'km', NULL),
('LV-113', 'km', 'វ៉ាលមីរ៉ា'),
('LV-DGV', 'km', NULL),
('LV-JEL', 'km', 'ជេលហ្គាវ៉ា'),
('LV-JUR', 'km', 'ជូម៉ាឡា'),
('LV-LPX', 'km', 'លីប៉ាចា'),
('LV-REZ', 'km', 'រ៉េសេកណេ'),
('LV-RIX', 'km', 'រីហ្គា'),
('LV-VEN', 'km', 'ខ្យល់');

SET FOREIGN_KEY_CHECKS=1;
