SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('ES-A', 'tr', 'Alicante'),
('ES-AB', 'tr', 'Albacete'),
('ES-AL', 'tr', 'Almería'),
('ES-AN', 'tr', 'Endülüs'),
('ES-AR', 'tr', 'Aragon'),
('ES-AS', 'tr', 'Asturies'),
('ES-AV', 'tr', 'Avila'),
('ES-B', 'tr', 'Barcelona [Barcelona]'),
('ES-BA', 'tr', 'Badajoz'),
('ES-BI', 'tr', 'Bizkaia'),
('ES-BU', 'tr', 'Burgos'),
('ES-C', 'tr', 'A Coruña [La Coruña]'),
('ES-CA', 'tr', 'Cádiz'),
('ES-CB', 'tr', 'Kantabria'),
('ES-CC', 'tr', 'Cáceres'),
('ES-CE', 'tr', 'Sebte'),
('ES-CL', 'tr', 'Kastilya ve Leon'),
('ES-CM', 'tr', 'Kastilya-La Mancha'),
('ES-CN', 'tr', 'Kanarya Adaları'),
('ES-CO', 'tr', 'Córdoba'),
('ES-CR', 'tr', 'Ciudad Real'),
('ES-CS', 'tr', 'Castellón'),
('ES-CT', 'tr', 'Katalonya'),
('ES-CU', 'tr', 'Cuenca'),
('ES-EX', 'tr', 'Ekstremadura'),
('ES-GA', 'tr', 'Galiçya'),
('ES-GC', 'tr', 'Las Palmas'),
('ES-GI', 'tr', 'Girona [Gerona]'),
('ES-GR', 'tr', 'Granada'),
('ES-GU', 'tr', 'Guadalajara'),
('ES-H', 'tr', 'Huelva'),
('ES-HU', 'tr', 'Huesca'),
('ES-IB', 'tr', NULL),
('ES-J', 'tr', 'Jaén'),
('ES-L', 'tr', 'Lleida [Lérida]'),
('ES-LE', 'tr', 'León'),
('ES-LO', 'tr', 'La Rioja'),
('ES-LU', 'tr', 'Lugo [Lugo]'),
('ES-M', 'tr', 'Madrid'),
('ES-MA', 'tr', 'Malaga'),
('ES-MC', 'tr', 'Murcia'),
('ES-MD', 'tr', 'Madrid'),
('ES-ML', 'tr', 'Melilla'),
('ES-MU', 'tr', 'Murcia'),
('ES-NA', 'tr', 'Navarra'),
('ES-NC', 'tr', 'Navarra'),
('ES-O', 'tr', 'Asturias'),
('ES-OR', 'tr', 'Ourense [Orense]'),
('ES-P', 'tr', 'Palencia'),
('ES-PM', 'tr', 'Illes Balears [Islas Baleares]'),
('ES-PO', 'tr', 'Pontevedra [Pontevedra]'),
('ES-PV', 'tr', 'Bask Bölgesi'),
('ES-RI', 'tr', 'La Rioja'),
('ES-S', 'tr', 'Cantabria'),
('ES-SA', 'tr', 'Salamanca'),
('ES-SE', 'tr', 'Sevilla'),
('ES-SG', 'tr', 'Segovia'),
('ES-SO', 'tr', 'Soria'),
('ES-SS', 'tr', 'Gipuzkoa'),
('ES-T', 'tr', 'Tarragona [Tarragona]'),
('ES-TE', 'tr', 'Teruel'),
('ES-TF', 'tr', 'Santa Cruz de Tenerife'),
('ES-TO', 'tr', 'Toledo'),
('ES-V', 'tr', 'Valencia'),
('ES-VA', 'tr', 'Valladolid'),
('ES-VC', 'tr', 'Valensiya'),
('ES-VI', 'tr', 'Álava'),
('ES-Z', 'tr', 'Zaragoza'),
('ES-ZA', 'tr', 'Zamora');

SET FOREIGN_KEY_CHECKS=1;
