SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('MT-01', 'sv', 'Attard'),
('MT-02', 'sv', 'Balzan'),
('MT-03', 'sv', 'Birgu'),
('MT-04', 'sv', 'Birkirkara'),
('MT-05', 'sv', 'Birżebbuġa'),
('MT-06', 'sv', 'Bormla'),
('MT-07', 'sv', 'Dingli'),
('MT-08', 'sv', 'Il-Fgura'),
('MT-09', 'sv', 'Floriana'),
('MT-10', 'sv', 'Il-Fontana'),
('MT-11', 'sv', 'Il-Gudja'),
('MT-12', 'sv', 'Il-Gżira'),
('MT-13', 'sv', 'Għajnsielem'),
('MT-14', 'sv', 'L-Għarb'),
('MT-15', 'sv', 'Ħal Għargħur'),
('MT-16', 'sv', 'L-Ghasri'),
('MT-17', 'sv', 'Ħal Għaxaq'),
('MT-18', 'sv', 'Il-Ħamrun'),
('MT-19', 'sv', 'L-Iklin'),
('MT-20', 'sv', 'L-Isla'),
('MT-21', 'sv', 'Kalkara'),
('MT-22', 'sv', 'Ta’ Kerċem'),
('MT-23', 'sv', 'Kirkop'),
('MT-24', 'sv', 'Lija'),
('MT-25', 'sv', 'Luqa'),
('MT-26', 'sv', 'Il-Marsa'),
('MT-27', 'sv', 'Marsaskala'),
('MT-28', 'sv', 'Marsaxlokk'),
('MT-29', 'sv', 'Mdina'),
('MT-30', 'sv', 'Il-Mellieħa (kommun i Malta)'),
('MT-31', 'sv', 'L-Imġarr'),
('MT-32', 'sv', 'Mosta'),
('MT-33', 'sv', 'Mqabba'),
('MT-34', 'sv', 'Msida'),
('MT-35', 'sv', 'L-Imtarfa'),
('MT-36', 'sv', 'Il-Munxar'),
('MT-37', 'sv', 'In-Nadur'),
('MT-38', 'sv', 'In-Naxxar'),
('MT-39', 'sv', 'Paola'),
('MT-40', 'sv', 'Pembroke'),
('MT-41', 'sv', 'Pietà'),
('MT-42', 'sv', 'Il-Qala'),
('MT-43', 'sv', 'Qormi'),
('MT-44', 'sv', 'Il-Qrendi'),
('MT-45', 'sv', 'Victoria'),
('MT-46', 'sv', 'Rabat'),
('MT-47', 'sv', 'Safi'),
('MT-48', 'sv', 'St. Julian''s'),
('MT-49', 'sv', 'San Ġwann'),
('MT-50', 'sv', 'San Lawrenz'),
('MT-51', 'sv', 'St. Paul''s Bay'),
('MT-52', 'sv', 'Sannat'),
('MT-53', 'sv', 'Saint Lucia'),
('MT-54', 'sv', 'Santa Venera'),
('MT-55', 'sv', 'Is-Siġġiewi (kommun i Malta)'),
('MT-56', 'sv', 'Sliema'),
('MT-57', 'sv', 'Is-Swieqi'),
('MT-58', 'sv', 'Tarxien'),
('MT-59', 'sv', 'Ta’ Xbiex'),
('MT-60', 'sv', 'Valletta'),
('MT-61', 'sv', 'Ix-Xagħra'),
('MT-62', 'sv', 'Ix-Xewkija'),
('MT-63', 'sv', 'Ix-Xgħajra'),
('MT-64', 'sv', 'Żabbar'),
('MT-65', 'sv', 'Iż-Żebbuġ'),
('MT-66', 'sv', 'Ħaż-Żebbuġ'),
('MT-67', 'sv', 'Iż-Żejtun'),
('MT-68', 'sv', 'Iż-Żurrieq');

SET FOREIGN_KEY_CHECKS=1;
