SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('VN-01', 'lb', 'Lai Châu'),
('VN-02', 'lb', 'Lao Cai'),
('VN-03', 'lb', 'Ha Giang'),
('VN-04', 'lb', 'Cao Bằng'),
('VN-05', 'lb', 'Sơn La'),
('VN-06', 'lb', 'Yen Bai'),
('VN-07', 'lb', 'Tuyen Quang'),
('VN-09', 'lb', 'Lạng Sơn'),
('VN-13', 'lb', 'Quảng Ninh'),
('VN-14', 'lb', 'Hoa Binh'),
('VN-18', 'lb', 'Ninh Binh'),
('VN-20', 'lb', 'Thai Binh'),
('VN-21', 'lb', 'Thanh Hóa'),
('VN-22', 'lb', 'Nghệ An'),
('VN-23', 'lb', 'Gia Lai'),
('VN-24', 'lb', 'Provënz Quang Binh'),
('VN-25', 'lb', 'Quang Tri'),
('VN-26', 'lb', 'Dak Lak'),
('VN-27', 'lb', 'Quang Nam'),
('VN-28', 'lb', 'Kon Tum'),
('VN-29', 'lb', 'Provënz Quảng Ngãi'),
('VN-30', 'lb', 'Gia Lai'),
('VN-31', 'lb', 'Binh Dinh'),
('VN-32', 'lb', 'Phu Yen'),
('VN-33', 'lb', 'Dak Lak'),
('VN-34', 'lb', 'Khanh Hoa'),
('VN-35', 'lb', 'Lam Dong'),
('VN-36', 'lb', 'Ninh Thuan'),
('VN-37', 'lb', 'Tay Ninh'),
('VN-39', 'lb', 'Đồng Nai'),
('VN-40', 'lb', 'Binh Thuan'),
('VN-41', 'lb', 'Long An'),
('VN-43', 'lb', 'Ba Ria - Vung Tau'),
('VN-44', 'lb', 'An Giang'),
('VN-45', 'lb', 'Dong Thap'),
('VN-46', 'lb', 'Tien Giang'),
('VN-47', 'lb', 'Kien Giang'),
('VN-49', 'lb', 'Vinh Long'),
('VN-50', 'lb', 'Ben Tre'),
('VN-51', 'lb', 'Tra Vinh'),
('VN-52', 'lb', 'Soc Trang'),
('VN-53', 'lb', 'Bac Kan'),
('VN-54', 'lb', 'Bac Giang'),
('VN-55', 'lb', 'Bac Lieu'),
('VN-56', 'lb', 'Bac Ninh'),
('VN-57', 'lb', 'Binh Duong'),
('VN-58', 'lb', 'Binh Phuoc'),
('VN-59', 'lb', 'Ca Mau'),
('VN-61', 'lb', 'Hai Duong'),
('VN-63', 'lb', 'Ha Nam'),
('VN-66', 'lb', 'Hưng Yên'),
('VN-67', 'lb', 'Nam Dinh'),
('VN-68', 'lb', 'Phu Tho'),
('VN-69', 'lb', 'Thai Nguyen'),
('VN-70', 'lb', 'Vinh Phuc'),
('VN-71', 'lb', 'Kann Tho City'),
('VN-72', 'lb', 'Dak Nong'),
('VN-73', 'lb', 'Hau Giang'),
('VN-CT', 'lb', 'Can Tho'),
('VN-DN', 'lb', 'Da Nang'),
('VN-HN', 'lb', 'Quang Tri'),
('VN-HP', 'lb', 'Hai Phong'),
('VN-SG', 'lb', 'Ho Chi Minh');

SET FOREIGN_KEY_CHECKS=1;
