SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('ES-A', 'de', 'Alicante'),
('ES-AB', 'de', 'Albacete'),
('ES-AL', 'de', 'Almería'),
('ES-AN', 'de', 'Andalusien'),
('ES-AR', 'de', 'Aragonien'),
('ES-AS', 'de', 'Fürstentum Asturien'),
('ES-AV', 'de', 'Ávila'),
('ES-B', 'de', 'Barcelona [Barcelona]'),
('ES-BA', 'de', 'Badajoz'),
('ES-BI', 'de', 'Bizkaia'),
('ES-BU', 'de', 'Burgos'),
('ES-C', 'de', 'A Coruña [La Coruña]'),
('ES-CA', 'de', 'Cádiz'),
('ES-CB', 'de', 'Kantabrien'),
('ES-CC', 'de', 'Cáceres'),
('ES-CE', 'de', 'Ceuta'),
('ES-CL', 'de', 'Nordkastilien'),
('ES-CM', 'de', 'Südkastilien'),
('ES-CN', 'de', 'Kanarische Inseln'),
('ES-CO', 'de', 'Córdoba'),
('ES-CR', 'de', 'Ciudad Real'),
('ES-CS', 'de', 'Castellón'),
('ES-CT', 'de', 'Katalonien'),
('ES-CU', 'de', 'Cuenca'),
('ES-EX', 'de', 'Estremadura'),
('ES-GA', 'de', 'Galicien'),
('ES-GC', 'de', 'Las Palmas'),
('ES-GI', 'de', 'Girona [Gerona]'),
('ES-GR', 'de', 'Granada'),
('ES-GU', 'de', 'Guadalajara'),
('ES-H', 'de', 'Huelva'),
('ES-HU', 'de', 'Huesca'),
('ES-IB', 'de', 'Balearische Inseln'),
('ES-J', 'de', 'Jaén'),
('ES-L', 'de', 'Lleida [Lérida]'),
('ES-LE', 'de', 'León'),
('ES-LO', 'de', 'La Rioja'),
('ES-LU', 'de', 'Lugo [Lugo]'),
('ES-M', 'de', 'Madrid'),
('ES-MA', 'de', 'Málaga'),
('ES-MC', 'de', 'Region Murcia'),
('ES-MD', 'de', 'Madrid'),
('ES-ML', 'de', 'Melilla'),
('ES-MU', 'de', 'Murcia'),
('ES-NA', 'de', 'Navarra'),
('ES-NC', 'de', 'Autonome Region Navarra'),
('ES-O', 'de', 'Asturien'),
('ES-OR', 'de', 'Ourense [Orense]'),
('ES-P', 'de', 'Palencia'),
('ES-PM', 'de', 'Illes Balears [Islas Baleares]'),
('ES-PO', 'de', 'Pontevedra [Pontevedra]'),
('ES-PV', 'de', 'Baskenland'),
('ES-RI', 'de', 'La Rioja'),
('ES-S', 'de', 'Kantabrien'),
('ES-SA', 'de', 'Salamanca'),
('ES-SE', 'de', 'Sevilla'),
('ES-SG', 'de', 'Segovia'),
('ES-SO', 'de', 'Soria'),
('ES-SS', 'de', 'Gipuzkoa'),
('ES-T', 'de', 'Tarragona [Tarragona]'),
('ES-TE', 'de', 'Teruel'),
('ES-TF', 'de', 'Santa Cruz de Tenerife'),
('ES-TO', 'de', 'Toledo'),
('ES-V', 'de', 'Valencia'),
('ES-VA', 'de', 'Valladolid'),
('ES-VC', 'de', 'Valencia'),
('ES-VI', 'de', 'Álava'),
('ES-Z', 'de', 'Saragossa'),
('ES-ZA', 'de', 'Zamora');

SET FOREIGN_KEY_CHECKS=1;
