SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('VN-01', 'lv', 'Lai Čau'),
('VN-02', 'lv', 'Laokajas province'),
('VN-03', 'lv', 'Hazana'),
('VN-04', 'lv', 'Cao Bằng'),
('VN-05', 'lv', 'Son La'),
('VN-06', 'lv', 'Jenbajas province'),
('VN-07', 'lv', 'Tujenkuana'),
('VN-09', 'lv', 'Lạng Sơn'),
('VN-13', 'lv', 'Quảng Ninh'),
('VN-14', 'lv', 'Hoabiņa'),
('VN-18', 'lv', 'Niņbiņa'),
('VN-20', 'lv', 'Thajbiņas province'),
('VN-21', 'lv', 'Thanh Hóa'),
('VN-22', 'lv', 'Nghệ An'),
('VN-23', 'lv', 'Gia Lai'),
('VN-24', 'lv', 'Kuanbiņa'),
('VN-25', 'lv', 'Kuanči province'),
('VN-26', 'lv', 'Dak Lak'),
('VN-27', 'lv', 'Kuannama'),
('VN-28', 'lv', 'Kontumas province'),
('VN-29', 'lv', 'Kuanngaja'),
('VN-30', 'lv', 'Zalaja'),
('VN-31', 'lv', 'Biņdiņas province'),
('VN-32', 'lv', 'Fujena'),
('VN-33', 'lv', 'Daklaka'),
('VN-34', 'lv', 'Haņhoa'),
('VN-35', 'lv', 'Lomdonas province'),
('VN-36', 'lv', 'Niņthuona'),
('VN-37', 'lv', 'Tojniņa'),
('VN-39', 'lv', 'Dong Nai'),
('VN-40', 'lv', 'Biņthuanas province'),
('VN-41', 'lv', 'Lonana'),
('VN-43', 'lv', 'Baria-Vungtau'),
('VN-44', 'lv', 'Anzana'),
('VN-45', 'lv', 'Donthapas province'),
('VN-46', 'lv', 'Thenzana'),
('VN-47', 'lv', 'Kjenzana'),
('VN-49', 'lv', 'Viņlona'),
('VN-50', 'lv', 'Benčes province'),
('VN-51', 'lv', 'Čaviņas province'),
('VN-52', 'lv', 'Šokčana'),
('VN-53', 'lv', 'Bac Kan'),
('VN-54', 'lv', 'Bakzanas province'),
('VN-55', 'lv', 'Bakljeu'),
('VN-56', 'lv', 'Bakniņas province'),
('VN-57', 'lv', 'Biņziona'),
('VN-58', 'lv', 'Biņfioka'),
('VN-59', 'lv', 'Kamau'),
('VN-61', 'lv', 'Hajziona'),
('VN-63', 'lv', 'Hanamas province'),
('VN-66', 'lv', 'Hung Yen'),
('VN-67', 'lv', 'Namdiņa'),
('VN-68', 'lv', 'Futuo'),
('VN-69', 'lv', 'Thajngujenas province'),
('VN-70', 'lv', 'Viņfukas province'),
('VN-71', 'lv', 'Can Tho City'),
('VN-72', 'lv', 'Daknona'),
('VN-73', 'lv', 'Houzana'),
('VN-CT', 'lv', 'Kontho'),
('VN-DN', 'lv', 'Dananga'),
('VN-HN', 'lv', 'Quang Tri'),
('VN-HP', 'lv', 'Haifona'),
('VN-SG', 'lv', 'Hošimina');

SET FOREIGN_KEY_CHECKS=1;
