SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('DO-01', 'fo', NULL),
('DO-02', 'fo', 'Azua'),
('DO-03', 'fo', 'Bahoruco'),
('DO-04', 'fo', 'Barahona'),
('DO-05', 'fo', 'Dajabon'),
('DO-06', 'fo', 'Duarte'),
('DO-07', 'fo', 'Elias Pina'),
('DO-08', 'fo', 'El Seibo'),
('DO-09', 'fo', 'Espaillat'),
('DO-10', 'fo', 'Independencia'),
('DO-11', 'fo', 'La Altagracia'),
('DO-12', 'fo', 'La Romana'),
('DO-13', 'fo', 'Vega'),
('DO-14', 'fo', 'Maria Trinidad Sanchez'),
('DO-15', 'fo', 'Monte Cristi'),
('DO-16', 'fo', 'Pedernales'),
('DO-17', 'fo', 'Perávia'),
('DO-18', 'fo', 'Puerto Plata'),
('DO-19', 'fo', 'Hermanas Mirabal'),
('DO-20', 'fo', 'Samana-landsluturin'),
('DO-21', 'fo', 'Sankristobal'),
('DO-22', 'fo', 'San Juan'),
('DO-23', 'fo', 'San Pedro de Macoris'),
('DO-24', 'fo', 'Sanchez Ramirez'),
('DO-25', 'fo', 'Santiago'),
('DO-26', 'fo', 'Santíago Ródriguez'),
('DO-27', 'fo', 'Valverde'),
('DO-28', 'fo', 'Monsenor Nouel'),
('DO-29', 'fo', 'Monte Plata'),
('DO-30', 'fo', 'Hato Mayor'),
('DO-31', 'fo', 'San Jose de Ocoa'),
('DO-32', 'fo', NULL),
('DO-33', 'fo', 'Cibao Nordeste'),
('DO-34', 'fo', 'Cibao Noroeste'),
('DO-35', 'fo', 'Cibao Norte'),
('DO-36', 'fo', 'Cibao Sur'),
('DO-37', 'fo', 'El Valle'),
('DO-38', 'fo', 'Enriquillo'),
('DO-39', 'fo', 'Higuamo'),
('DO-40', 'fo', 'Ozama'),
('DO-41', 'fo', 'Valdesia'),
('DO-42', 'fo', 'Yuma');

SET FOREIGN_KEY_CHECKS=1;
