SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('VN-01', 'ms', 'Lai Châu'),
('VN-02', 'ms', 'Lao Cai'),
('VN-03', 'ms', 'Ha Giang'),
('VN-04', 'ms', 'Cao Bằng'),
('VN-05', 'ms', 'Sơn La'),
('VN-06', 'ms', 'Provinsi Yen Bai'),
('VN-07', 'ms', 'Tuyen Quang'),
('VN-09', 'ms', 'Lạng Sơn'),
('VN-13', 'ms', 'Quảng Ninh'),
('VN-14', 'ms', 'Provinsi Hoa Binh'),
('VN-18', 'ms', 'Provinsi Ninh Binh'),
('VN-20', 'ms', 'Thai Binh'),
('VN-21', 'ms', 'Thanh Hóa'),
('VN-22', 'ms', 'Nghệ An'),
('VN-23', 'ms', 'Gia Lai'),
('VN-24', 'ms', 'Quang Binh'),
('VN-25', 'ms', 'Quang Trị'),
('VN-26', 'ms', 'Dak Lak'),
('VN-27', 'ms', 'Quang Nam'),
('VN-28', 'ms', 'Kon Tum'),
('VN-29', 'ms', 'Quang Ngai'),
('VN-30', 'ms', 'Gia Lai'),
('VN-31', 'ms', 'Binh Dinh'),
('VN-32', 'ms', 'Phu Yen'),
('VN-33', 'ms', 'Dak Lak'),
('VN-34', 'ms', 'Khanh Hoa'),
('VN-35', 'ms', 'Lam Dong'),
('VN-36', 'ms', 'Ninh Thuan'),
('VN-37', 'ms', 'Tay Ninh'),
('VN-39', 'ms', 'Wilayah GJong Nai'),
('VN-40', 'ms', 'Binh Thuan'),
('VN-41', 'ms', 'Long An'),
('VN-43', 'ms', 'Ba Ria–Vung Tau'),
('VN-44', 'ms', 'Wilayah An Giang'),
('VN-45', 'ms', 'Dong Thap Province'),
('VN-46', 'ms', 'Tien Giang'),
('VN-47', 'ms', 'Wilayah Kien Giang'),
('VN-49', 'ms', 'Vinh Long'),
('VN-50', 'ms', 'Ben Tre'),
('VN-51', 'ms', 'Provinsi Tra Vinh'),
('VN-52', 'ms', 'Soc Trang'),
('VN-53', 'ms', 'Wilayah Bac Kan'),
('VN-54', 'ms', 'Bac Giang'),
('VN-55', 'ms', 'Bac Lieu'),
('VN-56', 'ms', 'Wilayah Bac Ninh'),
('VN-57', 'ms', 'Binh Duong'),
('VN-58', 'ms', 'Binh Phuoc'),
('VN-59', 'ms', 'Wilayah Ca Mau'),
('VN-61', 'ms', 'Wilayah Hai Duong'),
('VN-63', 'ms', 'Wilayah Ha Nam'),
('VN-66', 'ms', 'Wilayah Hung Yen'),
('VN-67', 'ms', 'Nam Dinh'),
('VN-68', 'ms', 'Phe Thọ'),
('VN-69', 'ms', 'Thai Nguyen'),
('VN-70', 'ms', 'Vinh Phuc'),
('VN-71', 'ms', 'Bandar Can Tho'),
('VN-72', 'ms', 'Wilayah GJak Nong'),
('VN-73', 'ms', 'Wilayah Hau Giang'),
('VN-CT', 'ms', 'Can Tho'),
('VN-DN', 'ms', 'Da Nang'),
('VN-HN', 'ms', 'Quang Tri'),
('VN-HP', 'ms', 'Haiphong'),
('VN-SG', 'ms', 'Bandar Raya Ho Chi Minh');

SET FOREIGN_KEY_CHECKS=1;
