SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('IT-21', 'bs', 'Pijemont'),
('IT-23', 'bs', 'Valle d''Aosta'),
('IT-25', 'bs', 'Lombardija'),
('IT-32', 'bs', 'Trentino-Južni Tirol'),
('IT-34', 'bs', 'Veneto'),
('IT-36', 'bs', 'Furlanija-Julijska Krajina'),
('IT-42', 'bs', 'Ligurija'),
('IT-45', 'bs', 'Emilia-Romagna'),
('IT-52', 'bs', 'Toskana'),
('IT-55', 'bs', 'Umbrija'),
('IT-57', 'bs', 'Marche'),
('IT-62', 'bs', 'Lacio'),
('IT-65', 'bs', 'Abruzzo'),
('IT-67', 'bs', 'Molise'),
('IT-72', 'bs', 'Kampanija'),
('IT-75', 'bs', 'Apulija'),
('IT-77', 'bs', 'Basilicata'),
('IT-78', 'bs', 'Kalabrija'),
('IT-82', 'bs', 'Sicilija'),
('IT-88', 'bs', 'Sardinija'),
('IT-AG', 'bs', 'Agrigento'),
('IT-AL', 'bs', 'Alesandrija'),
('IT-AN', 'bs', 'Ancona'),
('IT-AP', 'bs', 'Ascoli Piceno'),
('IT-AQ', 'bs', 'L''Aquila'),
('IT-AR', 'bs', 'Arezzo'),
('IT-AT', 'bs', 'Asti'),
('IT-AV', 'bs', 'Avellino'),
('IT-BA', 'bs', 'Bari'),
('IT-BG', 'bs', 'Bergamo'),
('IT-BI', 'bs', 'Biella'),
('IT-BL', 'bs', 'Belluno'),
('IT-BN', 'bs', 'Benevento'),
('IT-BO', 'bs', 'Bologna'),
('IT-BR', 'bs', 'Brindisi'),
('IT-BS', 'bs', 'Brescia'),
('IT-BT', 'bs', 'Barletta-Andria-Trani'),
('IT-BZ', 'bs', 'Bolzano'),
('IT-CA', 'bs', 'Cagliari'),
('IT-CB', 'bs', 'Campobasso'),
('IT-CE', 'bs', 'Caserta'),
('IT-CH', 'bs', 'Chieti'),
('IT-CL', 'bs', 'Caltanissetta'),
('IT-CN', 'bs', 'Cuneo'),
('IT-CO', 'bs', 'Como'),
('IT-CR', 'bs', 'Cremona'),
('IT-CS', 'bs', 'Cosenza'),
('IT-CT', 'bs', 'Catania'),
('IT-CZ', 'bs', 'Catanzaro'),
('IT-EN', 'bs', 'Enna'),
('IT-FC', 'bs', 'Forlì-Cesena'),
('IT-FE', 'bs', 'Ferara'),
('IT-FG', 'bs', 'Foggia'),
('IT-FI', 'bs', 'Firenze'),
('IT-FM', 'bs', 'Fermo'),
('IT-FR', 'bs', 'Frosinone'),
('IT-GE', 'bs', 'Genova'),
('IT-GO', 'bs', 'Gorizia'),
('IT-GR', 'bs', 'Grosseto'),
('IT-IM', 'bs', 'Imperija'),
('IT-IS', 'bs', 'Isernija'),
('IT-KR', 'bs', 'Crotone'),
('IT-LC', 'bs', 'Lecco'),
('IT-LE', 'bs', 'Lecce'),
('IT-LI', 'bs', 'Livorno'),
('IT-LO', 'bs', 'Lodi'),
('IT-LT', 'bs', 'Latina'),
('IT-LU', 'bs', 'Lucca'),
('IT-MB', 'bs', 'Monza i Brianza'),
('IT-MC', 'bs', 'Macerata'),
('IT-ME', 'bs', 'Mesina'),
('IT-MI', 'bs', 'Milano'),
('IT-MN', 'bs', 'Mantova'),
('IT-MO', 'bs', 'Modena'),
('IT-MS', 'bs', 'Massa-Carrara'),
('IT-MT', 'bs', 'Matera'),
('IT-NA', 'bs', 'Napoli'),
('IT-NO', 'bs', 'Novara'),
('IT-NU', 'bs', 'Nuoro'),
('IT-OR', 'bs', 'Oristano'),
('IT-PA', 'bs', 'Palermo'),
('IT-PC', 'bs', 'Piacenza'),
('IT-PD', 'bs', 'Padova'),
('IT-PE', 'bs', 'Pescara'),
('IT-PG', 'bs', 'Perugia'),
('IT-PI', 'bs', 'Pisa'),
('IT-PN', 'bs', 'Pordenone'),
('IT-PO', 'bs', 'Prato'),
('IT-PR', 'bs', 'Parma'),
('IT-PT', 'bs', 'Pistoia'),
('IT-PU', 'bs', 'Pesaro i Urbino'),
('IT-PV', 'bs', 'Pavija'),
('IT-PZ', 'bs', 'Potenza'),
('IT-RA', 'bs', 'Ravena'),
('IT-RC', 'bs', 'Reggio Calabria'),
('IT-RE', 'bs', 'Reggio Emilia'),
('IT-RG', 'bs', 'Ragusa'),
('IT-RI', 'bs', 'Rieti'),
('IT-RM', 'bs', 'Roma'),
('IT-RN', 'bs', 'Rimini'),
('IT-RO', 'bs', 'Rovigo'),
('IT-SA', 'bs', 'Salerno'),
('IT-SI', 'bs', 'Siena'),
('IT-SO', 'bs', 'Sondrio'),
('IT-SP', 'bs', 'La Spezia'),
('IT-SR', 'bs', 'Siracusa'),
('IT-SS', 'bs', 'Sasari'),
('IT-SU', 'bs', 'Sud Sardegna'),
('IT-SV', 'bs', 'Savona'),
('IT-TA', 'bs', 'Taranto'),
('IT-TE', 'bs', 'Teramo'),
('IT-TN', 'bs', 'Trento'),
('IT-TO', 'bs', 'Torino'),
('IT-TP', 'bs', 'Trapani'),
('IT-TR', 'bs', 'Terni'),
('IT-TS', 'bs', 'Trst'),
('IT-TV', 'bs', 'Treviso'),
('IT-UD', 'bs', 'Udine'),
('IT-VA', 'bs', 'Varese'),
('IT-VB', 'bs', 'Verbano-Cusio-Ossola'),
('IT-VC', 'bs', 'Vercelli'),
('IT-VE', 'bs', 'Venezia'),
('IT-VI', 'bs', 'Vicenza'),
('IT-VR', 'bs', 'Verona'),
('IT-VT', 'bs', 'Viterbo'),
('IT-VV', 'bs', 'Vibo Valentia');

SET FOREIGN_KEY_CHECKS=1;
