SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('DO-01', 'sl', 'Distrito Nacional'),
('DO-02', 'sl', 'Provinca Azua'),
('DO-03', 'sl', 'Provinca Baoruco'),
('DO-04', 'sl', 'Provinca Barahona'),
('DO-05', 'sl', 'Provinca Dajabón'),
('DO-06', 'sl', 'Provinca Duarte'),
('DO-07', 'sl', 'Provinca Elías Piña'),
('DO-08', 'sl', 'Provinca El Seibo'),
('DO-09', 'sl', 'Provinca Espaillat'),
('DO-10', 'sl', 'Provinca Independencia'),
('DO-11', 'sl', 'Provinca La Altagracia'),
('DO-12', 'sl', 'Provinca La Romana'),
('DO-13', 'sl', 'Provinca La Vega'),
('DO-14', 'sl', 'Provinca María Trinidad Sánchez'),
('DO-15', 'sl', 'Provinca Monte Cristi'),
('DO-16', 'sl', 'Provinca Pedernales'),
('DO-17', 'sl', 'Provinca Peravia'),
('DO-18', 'sl', 'Provinca Puerto Plata'),
('DO-19', 'sl', 'Provinca Hermanas Mirabal'),
('DO-20', 'sl', 'Provinca Samaná'),
('DO-21', 'sl', 'Provinca San Cristóbal'),
('DO-22', 'sl', 'Provinca San Juan'),
('DO-23', 'sl', 'Provinca San Pedro de Macorís'),
('DO-24', 'sl', 'Provinca Sánchez Ramírez'),
('DO-25', 'sl', 'Provinca Santiago'),
('DO-26', 'sl', 'Provinca Santiago Rodríguez'),
('DO-27', 'sl', 'Provinca Valverde'),
('DO-28', 'sl', 'Provinca Monseñor Nouel'),
('DO-29', 'sl', 'Provinca Monte Plata'),
('DO-30', 'sl', 'Provinca Hato Mayor'),
('DO-31', 'sl', 'Provinca San José de Ocoa'),
('DO-32', 'sl', 'Provinca Santo Domingo'),
('DO-33', 'sl', 'Cibao Nordeste'),
('DO-34', 'sl', 'Cibao Noroeste'),
('DO-35', 'sl', 'Cibao Norte'),
('DO-36', 'sl', 'Cibao Sur'),
('DO-37', 'sl', 'El Valle'),
('DO-38', 'sl', 'Enriquillo'),
('DO-39', 'sl', 'Higuamo'),
('DO-40', 'sl', 'Ozama'),
('DO-41', 'sl', 'Valdesia'),
('DO-42', 'sl', 'Yuma');

SET FOREIGN_KEY_CHECKS=1;
