SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('HU-BA', 'zh', '巴蘭尼亞州'),
('HU-BC', 'zh', '贝凯什克萨巴'),
('HU-BE', 'zh', '貝凱什州'),
('HU-BK', 'zh', '巴奇-基什孔州'),
('HU-BU', 'zh', '布达佩斯'),
('HU-BZ', 'zh', '包爾紹德-奧包烏伊-曾普倫州'),
('HU-CS', 'zh', '琼格拉德-乔纳德州'),
('HU-DE', 'zh', '德布勒森'),
('HU-DU', 'zh', NULL),
('HU-EG', 'zh', '埃格尔'),
('HU-ER', 'zh', NULL),
('HU-FE', 'zh', '費耶爾州'),
('HU-GS', 'zh', '傑爾-莫雄-肖普朗州'),
('HU-GY', 'zh', '杰尔'),
('HU-HB', 'zh', '豪伊杜-比豪爾州'),
('HU-HE', 'zh', '赫維什州'),
('HU-HV', 'zh', '霍德梅兹瓦萨赫伊'),
('HU-JN', 'zh', '亞斯-瑙吉孔-索爾諾克州'),
('HU-KE', 'zh', '科馬羅姆-埃斯泰爾戈姆州'),
('HU-KM', 'zh', '凯奇凯梅特'),
('HU-KV', 'zh', '考波什堡'),
('HU-MI', 'zh', '米什科尔茨'),
('HU-NK', 'zh', '纳吉卡尼兹萨'),
('HU-NO', 'zh', '諾格拉德州'),
('HU-NY', 'zh', '尼赖吉哈佐'),
('HU-PE', 'zh', '佩斯州'),
('HU-PS', 'zh', NULL),
('HU-SD', 'zh', '塞格德'),
('HU-SF', 'zh', NULL),
('HU-SH', 'zh', '松博特海伊'),
('HU-SK', 'zh', '索尔诺克'),
('HU-SN', 'zh', '肖普朗'),
('HU-SO', 'zh', '紹莫吉州'),
('HU-SS', 'zh', '塞克萨德'),
('HU-ST', 'zh', '萨尔戈塔尔扬'),
('HU-SZ', 'zh', '索博爾奇-索特馬爾-貝拉格州'),
('HU-TB', 'zh', '塔塔巴尼亚'),
('HU-TO', 'zh', '托爾瑙州'),
('HU-VA', 'zh', '沃什州'),
('HU-VE', 'zh', '維斯普雷姆州'),
('HU-VM', 'zh', '维斯普雷姆'),
('HU-ZA', 'zh', '佐洛州'),
('HU-ZE', 'zh', NULL);

SET FOREIGN_KEY_CHECKS=1;
