SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('TH-10', 'sk', 'Bangkok'),
('TH-11', 'sk', 'Čangwat Samut Prakan'),
('TH-12', 'sk', 'Čangwat Nonthaburi'),
('TH-13', 'sk', 'pthumthani'),
('TH-14', 'sk', 'Phra Nakhon Si Ayutthaya'),
('TH-15', 'sk', 'Changwat Ang Thong'),
('TH-16', 'sk', 'Čangwat Lop Buri'),
('TH-17', 'sk', 'Čangwat Sing Buri'),
('TH-18', 'sk', 'Changwat Chai Nat'),
('TH-19', 'sk', 'sraburi'),
('TH-20', 'sk', 'Changwat Chon Buri'),
('TH-21', 'sk', 'Rayong'),
('TH-22', 'sk', 'canthburi'),
('TH-23', 'sk', 'Čangwat Trat'),
('TH-24', 'sk', 'Čangwat Čačoengsao'),
('TH-25', 'sk', 'pracinburi'),
('TH-26', 'sk', 'Čangwat Nakhon Nayok'),
('TH-27', 'sk', 'Čangwat Sa Kaeo'),
('TH-30', 'sk', 'Čangwat Nakhon Ratchasima'),
('TH-31', 'sk', 'buriramy'),
('TH-32', 'sk', 'Čangwat Surin'),
('TH-33', 'sk', 'Čangwat Si Sa Ket'),
('TH-34', 'sk', 'Čangwat Ubon Ratchathani'),
('TH-35', 'sk', 'Čangwat Jasothon'),
('TH-36', 'sk', 'Čangwat Čaiyaphum'),
('TH-37', 'sk', 'Čangwat Amnat Charoen'),
('TH-38', 'sk', 'Changwat Bueng Kan'),
('TH-39', 'sk', 'Čangwat Nong Bua Lamphu'),
('TH-40', 'sk', 'Čangwat Khon Kaen'),
('TH-41', 'sk', 'Čangwat Udon Thani'),
('TH-42', 'sk', 'Changwat Loei'),
('TH-43', 'sk', 'Čangwat Nong Khai'),
('TH-44', 'sk', 'mhasarkham'),
('TH-45', 'sk', 'Changwat Roi Et'),
('TH-46', 'sk', 'Čangwat Kalasin'),
('TH-47', 'sk', 'Čangwat Sakon Nakhon'),
('TH-48', 'sk', 'Čangwat Nakhon Phanom'),
('TH-49', 'sk', 'Čangwat Mukdahan'),
('TH-50', 'sk', 'Čangwat Čiang Mai'),
('TH-51', 'sk', 'laphun'),
('TH-52', 'sk', 'lapang'),
('TH-53', 'sk', 'Čangwat Uttaradit'),
('TH-54', 'sk', 'Čangwat Phrae'),
('TH-55', 'sk', 'nan'),
('TH-56', 'sk', 'Čangwat Phayao'),
('TH-57', 'sk', 'Čangwat Čiang Rai'),
('TH-58', 'sk', 'Čangwat Mae Hong Son'),
('TH-60', 'sk', 'Čangwat Nakhon Sawan'),
('TH-61', 'sk', 'Čangwat Uthai Thani'),
('TH-62', 'sk', 'Čangwat Kamphaeng Phet'),
('TH-63', 'sk', 'tak'),
('TH-64', 'sk', 'Čangwat Sukhothai'),
('TH-65', 'sk', 'Phitsanulok'),
('TH-66', 'sk', 'Čangwat Phičit'),
('TH-67', 'sk', 'Čangwat Phetchabun'),
('TH-70', 'sk', 'Čangwat Ratchaburi'),
('TH-71', 'sk', 'Čangwat Kančanaburi'),
('TH-72', 'sk', 'Changwat Suphan Buri'),
('TH-73', 'sk', 'Čangwat Nakhon Pathom'),
('TH-74', 'sk', 'Čangwat Samut Sakhon'),
('TH-75', 'sk', 'Čangwat Samut Songkhram'),
('TH-76', 'sk', 'Čangwat Phetchaburi'),
('TH-77', 'sk', 'Čangwat Prachuap Khiri Khan'),
('TH-80', 'sk', 'Čangwat Nakhon Si Thammarat'),
('TH-81', 'sk', 'krabi'),
('TH-82', 'sk', 'phangnga'),
('TH-83', 'sk', 'phuket'),
('TH-84', 'sk', 'Čangwat Surat Thani'),
('TH-85', 'sk', 'Čangwat Ranong'),
('TH-86', 'sk', 'Čangwat Chumphon'),
('TH-90', 'sk', 'sngkhla'),
('TH-91', 'sk', 'Čangwat Satun'),
('TH-92', 'sk', 'trang'),
('TH-93', 'sk', 'phathlung'),
('TH-94', 'sk', 'pattani'),
('TH-95', 'sk', 'yala'),
('TH-96', 'sk', 'Čangwat Narathiwat'),
('TH-S', 'sk', 'Phatthaya');

SET FOREIGN_KEY_CHECKS=1;
