SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('SI-001', 'is', 'Sveitarfélagið Ajdovscina'),
('SI-002', 'is', 'Sveitarfélagið Beltinci'),
('SI-003', 'is', 'Sveitarfélagið Bled'),
('SI-004', 'is', 'Sveitarfélagið Bohinj'),
('SI-005', 'is', 'Sveitarfélagið Borovnica'),
('SI-006', 'is', 'Sveitarfélagið Bovec'),
('SI-007', 'is', 'Sveitarfélagið Brda'),
('SI-008', 'is', 'Sveitarfélagið Brezovica'),
('SI-009', 'is', 'Sveitarfélagið Brezice'),
('SI-010', 'is', 'Sveitarfélagið Tisina'),
('SI-011', 'is', 'Borgarsveitarfélagið Celje'),
('SI-012', 'is', 'Sveitarfélagið Cerklje na Gorenjskem'),
('SI-013', 'is', 'Sveitarfélagið Cerknica'),
('SI-014', 'is', 'Sveitarfélagið Cerkno'),
('SI-015', 'is', 'Sveitarfélagið Crensovci'),
('SI-016', 'is', 'Sveitarfélagið Crna na Koroskem'),
('SI-017', 'is', 'Sveitarfélagið Crnomelj'),
('SI-018', 'is', 'Sveitarfélagið Destrnik'),
('SI-019', 'is', 'Sveitarfélagið Divaca'),
('SI-020', 'is', 'Sveitarfélagið Dobrepolje'),
('SI-021', 'is', 'Sveitarfélagið Dobrova-Polhov Gradec'),
('SI-022', 'is', 'Sveitarfélagið Dol pri Ljubljani'),
('SI-023', 'is', 'Sveitarfélagið Domzale'),
('SI-024', 'is', 'Sveitarfélagið Dornava'),
('SI-025', 'is', NULL),
('SI-026', 'is', 'Sveitarfélagið Duplek'),
('SI-027', 'is', 'Sveitarfélagið Gorenja Vas-Poljane'),
('SI-028', 'is', 'Sveitarfélagið Gorisnica'),
('SI-029', 'is', 'Sveitarfélagið Gornja Radgona'),
('SI-030', 'is', 'Sveitarfélagið Gornji Grad'),
('SI-031', 'is', 'Sveitarfélagið Gornji Petrovci'),
('SI-032', 'is', NULL),
('SI-033', 'is', 'Sveitarfélagið Salovci'),
('SI-034', 'is', 'Sveitarfélagið Hrastnik'),
('SI-035', 'is', 'Sveitarfélagið Hrpelje-Kozina'),
('SI-036', 'is', 'Sveitarfélagið Idrija'),
('SI-037', 'is', 'Sveitarfélagið Ig'),
('SI-038', 'is', 'Sveitarfélagið Ilirska Bistrica'),
('SI-039', 'is', 'Sveitarfélagið Ivancna Gorica'),
('SI-040', 'is', 'Sveitarfélagið Izola'),
('SI-041', 'is', 'Sveitarfélagið Jesenice'),
('SI-042', 'is', NULL),
('SI-043', 'is', 'Sveitarfélagið Kamnik'),
('SI-044', 'is', NULL),
('SI-045', 'is', 'Sveitarfélagið Kidricevo'),
('SI-046', 'is', 'Sveitarfélagið Kobarid'),
('SI-047', 'is', 'Sveitarfélagið Kobilje'),
('SI-048', 'is', 'Sveitarfélagið Kocevje'),
('SI-049', 'is', NULL),
('SI-050', 'is', 'Borgarsveitarfélagið Koper'),
('SI-051', 'is', 'Sveitarfélagið Kozje'),
('SI-052', 'is', 'Sveitarfélag Kranj'),
('SI-053', 'is', 'Sveitarfélagið Kranjska Gora'),
('SI-054', 'is', 'Borgarsveitarfélagið Krsko'),
('SI-055', 'is', 'Sveitarfélagið Kungota'),
('SI-056', 'is', 'Sveitarfélagið Kuzma'),
('SI-057', 'is', 'Sveitarfélagið Lasko'),
('SI-058', 'is', NULL),
('SI-059', 'is', 'Sveitarfélagið Lendava'),
('SI-060', 'is', 'Sveitarfélagið Litija'),
('SI-061', 'is', 'Borgarsveitarfélagið Ljubljana'),
('SI-062', 'is', 'Sveitarfélagið Ljubno'),
('SI-063', 'is', 'Sveitarfélagið Ljutomer'),
('SI-064', 'is', NULL),
('SI-065', 'is', 'Obcina Loska Dolina'),
('SI-066', 'is', NULL),
('SI-067', 'is', 'Sveitarfélagið Luce'),
('SI-068', 'is', 'Sveitarfélagið Lukovica'),
('SI-069', 'is', 'Sveitarfélagið Majsperk'),
('SI-070', 'is', NULL),
('SI-071', 'is', 'Sveitarfélagið Medvode'),
('SI-072', 'is', 'Sveitarfélagið Menges'),
('SI-073', 'is', NULL),
('SI-074', 'is', 'Sveitarfélagið Mezica'),
('SI-075', 'is', 'Sveitarfélagið Miren-Kostanjevica'),
('SI-076', 'is', NULL),
('SI-077', 'is', 'Sveitarfélagið Moravce'),
('SI-078', 'is', 'Sveitarfélagið Moravske Toplice'),
('SI-079', 'is', 'Sveitarfélagið Mozirje'),
('SI-080', 'is', 'Borgarsveitarfélagið Murska Sobota'),
('SI-081', 'is', 'Sveitarfélagið Muta'),
('SI-082', 'is', 'Sveitarfélagið Naklo'),
('SI-083', 'is', 'Sveitarfélagið Nazarje'),
('SI-084', 'is', 'Borgarsveitarfélagið Nova Gorica'),
('SI-085', 'is', 'Borgarsveitarfélagið Novo Mesto'),
('SI-086', 'is', 'Sveitarfélagið Odranci'),
('SI-087', 'is', 'Sveitarfélagið Ormoz'),
('SI-088', 'is', 'Sveitarfélagið Osilnica'),
('SI-089', 'is', 'Sveitarfélagið Pesnica'),
('SI-090', 'is', 'Píran'),
('SI-091', 'is', 'Sveitarfélagið Pivka'),
('SI-092', 'is', 'Sveitarfélagið Podcetrtek'),
('SI-093', 'is', 'Sveitarfélagið Podvelka'),
('SI-094', 'is', 'Sveitarfélagið Postojna'),
('SI-095', 'is', NULL),
('SI-096', 'is', 'Borgarsveitarfélagið Ptuj'),
('SI-097', 'is', 'Sveitarfélagið Puconci'),
('SI-098', 'is', NULL),
('SI-099', 'is', 'Sveitarfélagið Radece'),
('SI-100', 'is', 'Sveitarfélagið Radenci'),
('SI-101', 'is', 'Sveitarfélagið Radlje ob Dravi'),
('SI-102', 'is', 'Sveitarfélagið Radovljica'),
('SI-103', 'is', NULL),
('SI-104', 'is', 'Sveitarfélagið Ribnica'),
('SI-105', 'is', 'Sveitarfélagið Rogasovci'),
('SI-106', 'is', 'Sveitarfélagið Rogaska Slatina'),
('SI-107', 'is', 'Sveitarfélagið Rogatec'),
('SI-108', 'is', 'Sveitarfélagið Ruse'),
('SI-109', 'is', 'Sveitarfélagið Semic'),
('SI-110', 'is', 'Sveitarfélagið Sevnica'),
('SI-111', 'is', 'Sveitarfélagið Sezana'),
('SI-112', 'is', 'Borgarsveitarfélagið Slovenj Gradec'),
('SI-113', 'is', 'Sveitarfélagið Slovenska Bistrica'),
('SI-114', 'is', 'Sveitarfélagið Slovenske Konjice'),
('SI-115', 'is', 'Sveitarfélagið Starse'),
('SI-116', 'is', 'Sveitarfélagið Sveti Jurij ob Scavnici'),
('SI-117', 'is', NULL),
('SI-118', 'is', 'Sveitarfélagið Sentilj'),
('SI-119', 'is', 'Sveitarfélagið Sentjernej'),
('SI-120', 'is', 'Sveitarfélagið Sentjur'),
('SI-121', 'is', 'Sveitarfélagið Skocjan'),
('SI-122', 'is', 'Sveitarfélagið Skofja Loka'),
('SI-123', 'is', 'Sveitarfélagið Skofljica'),
('SI-124', 'is', 'Sveitarfélagið Smarje pri Jelsah'),
('SI-125', 'is', 'Sveitarfélagið Smartno ob Paki'),
('SI-126', 'is', 'Sveitarfélagið Sostanj'),
('SI-127', 'is', NULL),
('SI-128', 'is', 'Sveitarfélagið Tolmin'),
('SI-129', 'is', 'Sveitarfélagið Trbovlje'),
('SI-130', 'is', 'Sveitarfélagið Trebnje'),
('SI-131', 'is', 'Sveitarfélagið Trzic'),
('SI-132', 'is', 'Sveitarfélagið Turnisce'),
('SI-133', 'is', 'Borgarsveitarfélagið Velenje'),
('SI-134', 'is', 'Sveitarfélagið Velike Lasce'),
('SI-135', 'is', 'Sveitarfélagið Videm'),
('SI-136', 'is', 'Sveitarfélagið Vipava'),
('SI-137', 'is', 'Sveitarfélagið Vitanje'),
('SI-138', 'is', 'Sveitarfélagið Vodice'),
('SI-139', 'is', 'Sveitarfélagið Vojnik'),
('SI-140', 'is', 'Sveitarfélagið Vrhnika'),
('SI-141', 'is', 'Sveitarfélagið Vuzenica'),
('SI-142', 'is', 'Sveitarfélagið Zagorje ob Savi'),
('SI-143', 'is', 'Sveitarfélagið Zavrc'),
('SI-144', 'is', 'Sveitarfélagið Zrece'),
('SI-146', 'is', 'Sveitarfélagið Zelezniki'),
('SI-147', 'is', 'Sveitarfélagið Ziri'),
('SI-148', 'is', 'Benedikt'),
('SI-149', 'is', 'Sveitarfélagið Bistrica ob Sotli'),
('SI-150', 'is', 'Sveitarfélagið Bloke'),
('SI-151', 'is', 'Sveitarfélagið Braslovce'),
('SI-152', 'is', 'Sveitarfélagið Cankova'),
('SI-153', 'is', 'Sveitarfélagið Cerkvenjak'),
('SI-154', 'is', 'Sveitarfélagið Dobje'),
('SI-155', 'is', 'Sveitarfélagið Dobrna'),
('SI-156', 'is', 'Sveitarfélagið Dobrovnik'),
('SI-157', 'is', 'Sveitarfélagið Dolenjske Toplice'),
('SI-158', 'is', 'Sveitarfélagið Grad'),
('SI-159', 'is', NULL),
('SI-160', 'is', 'Sveitarfélagið Hoce-Slivnica'),
('SI-161', 'is', 'Sveitarfélagið Hodos'),
('SI-162', 'is', NULL),
('SI-163', 'is', 'Sveitarfélagið Jezersko'),
('SI-164', 'is', 'Komenda'),
('SI-165', 'is', NULL),
('SI-166', 'is', 'Sveitarfélagið Krizevci'),
('SI-167', 'is', 'Sveitarfélagið Lovrenc na Pohorju'),
('SI-168', 'is', 'Sveitarfélagið Markovci'),
('SI-169', 'is', 'Sveitarfélagið Miklavz na Dravskem Polju'),
('SI-170', 'is', 'Sveitarfélagið Mirna Pec'),
('SI-171', 'is', 'Sveitarfélagið Oplotnica'),
('SI-172', 'is', 'Sveitarfélagið Podlehnik'),
('SI-173', 'is', 'Sveitarfélagið Polzela'),
('SI-174', 'is', 'Sveitarfélagið Prebold'),
('SI-175', 'is', 'Sveitarfélagið Prevalje'),
('SI-176', 'is', 'Sveitarfélagið Razkrizje'),
('SI-177', 'is', 'Sveitarfélagið Ribnica na Pohorju'),
('SI-178', 'is', 'Sveitarfélagið Selnica ob Dravi'),
('SI-179', 'is', 'Sveitarfélagið Sodrazica'),
('SI-180', 'is', 'Sveitarfélagið Solcava'),
('SI-181', 'is', 'Sveitarfélagið Sveta Ana'),
('SI-182', 'is', 'Obcina Sveti Andraz v Slovenskih goricah'),
('SI-183', 'is', 'Sveitarfélagið Sempeter-Vrtojba'),
('SI-184', 'is', NULL),
('SI-185', 'is', 'Sveitarfélagið Trnovska Vas'),
('SI-186', 'is', 'Sveitarfélagið Trzin'),
('SI-187', 'is', 'Sveitarfélagið Velika Polana'),
('SI-188', 'is', 'Sveitarfélagið Verzej'),
('SI-189', 'is', 'Sveitarfélagið Vransko'),
('SI-190', 'is', 'Sveitarfélagið Zalec'),
('SI-191', 'is', 'Sveitarfélagið Zetale'),
('SI-192', 'is', 'Sveitarfélagið Zirovnica'),
('SI-193', 'is', 'Sveitarfélagið Zuzemberk'),
('SI-194', 'is', 'Sveitarfélagið Smartno pri Litiji'),
('SI-195', 'is', 'Obcina Apace'),
('SI-196', 'is', 'Sveitarfélagið Cirkulane'),
('SI-197', 'is', 'Sveitarfélagið Kostanjevica na Krki'),
('SI-198', 'is', NULL),
('SI-199', 'is', 'Sveitarfélagið Mokronog-Trebelno'),
('SI-200', 'is', 'Obcina Poljcane'),
('SI-201', 'is', 'Obcina Rence-Vogrsko'),
('SI-202', 'is', 'Obcina Sredisce ob Dravi'),
('SI-203', 'is', 'Obcina Straza'),
('SI-204', 'is', 'Obcina Sveta Trojica v Slovenskih goricah'),
('SI-205', 'is', 'Obcina Sveti Tomaz'),
('SI-206', 'is', 'Sveitarfélagið Smarjeske Toplice'),
('SI-207', 'is', 'Sveitarfélagið Gorje'),
('SI-208', 'is', 'Sveitarfélagið Log-Dragomer'),
('SI-209', 'is', 'Obcina Recica ob Savinji'),
('SI-210', 'is', 'Obcina Sveti Jurij v Slovenskih goricah'),
('SI-211', 'is', 'Obcina Sentrupert'),
('SI-212', 'is', 'Mirna'),
('SI-213', 'is', 'Ankaran');

SET FOREIGN_KEY_CHECKS=1;
