SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('CZ-10', 'to', 'Hlavni mesto Palaha'),
('CZ-20', 'to', 'Sitetosesi kraj'),
('CZ-201', 'to', 'Penisov'),
('CZ-202', 'to', NULL),
('CZ-203', 'to', 'Klateno'),
('CZ-204', 'to', 'Kolini'),
('CZ-205', 'to', 'Kutná Hola'),
('CZ-206', 'to', 'Melinik'),
('CZ-207', 'to', 'Malatā Polesilavi'),
('CZ-208', 'to', NULL),
('CZ-209', 'to', NULL),
('CZ-20A', 'to', NULL),
('CZ-20B', 'to', NULL),
('CZ-20C', 'to', 'Lakovinik'),
('CZ-31', 'to', 'Jihocesky'),
('CZ-311', 'to', 'Seske Putejovisi'),
('CZ-312', 'to', NULL),
('CZ-313', 'to', NULL),
('CZ-314', 'to', 'Písek'),
('CZ-315', 'to', 'Prachatice'),
('CZ-316', 'to', NULL),
('CZ-317', 'to', 'Tábor'),
('CZ-32', 'to', NULL),
('CZ-321', 'to', NULL),
('CZ-322', 'to', 'Kalatovi'),
('CZ-323', 'to', NULL),
('CZ-324', 'to', NULL),
('CZ-325', 'to', NULL),
('CZ-326', 'to', NULL),
('CZ-327', 'to', 'Takovi'),
('CZ-41', 'to', 'Karlovarsky'),
('CZ-411', 'to', 'Cheb'),
('CZ-412', 'to', 'Kālovi Kehekehe'),
('CZ-413', 'to', 'Sokolov'),
('CZ-42', 'to', 'Ustecky'),
('CZ-421', 'to', NULL),
('CZ-422', 'to', 'Somutovi'),
('CZ-423', 'to', 'Litomēřisi'),
('CZ-424', 'to', 'Louni'),
('CZ-425', 'to', 'Ko e lahi tahá'),
('CZ-426', 'to', 'Tepilisi'),
('CZ-427', 'to', 'ʻUsitī mo Lepemi'),
('CZ-51', 'to', 'Liberecky'),
('CZ-511', 'to', 'Sesika Lipa'),
('CZ-512', 'to', NULL),
('CZ-513', 'to', 'Lipeleki'),
('CZ-514', 'to', 'Semili'),
('CZ-52', 'to', 'Kralovehradecky'),
('CZ-521', 'to', 'Hāteki Kālove'),
('CZ-522', 'to', 'Sisini'),
('CZ-523', 'to', NULL),
('CZ-524', 'to', 'Likinovi mo Knežnou'),
('CZ-525', 'to', 'Trutnov'),
('CZ-53', 'to', 'Pardubicky'),
('CZ-531', 'to', NULL),
('CZ-532', 'to', NULL),
('CZ-533', 'to', 'Sivitavi'),
('CZ-534', 'to', 'ʻUsitī mo ʻOlisi'),
('CZ-63', 'to', 'Vysocina'),
('CZ-631', 'to', 'Havličkv Brod'),
('CZ-632', 'to', 'Jihlava'),
('CZ-633', 'to', 'Pelimovi'),
('CZ-634', 'to', NULL),
('CZ-635', 'to', 'Žďár mo Sazavou'),
('CZ-64', 'to', 'Jihomoravsky'),
('CZ-641', 'to', 'Palanisiko'),
('CZ-642', 'to', NULL),
('CZ-643', 'to', 'Pino-venikovi'),
('CZ-644', 'to', NULL),
('CZ-645', 'to', 'Hotoni'),
('CZ-646', 'to', 'Vaisikovi'),
('CZ-647', 'to', 'Snojmo'),
('CZ-71', 'to', 'Olomoucky'),
('CZ-711', 'to', NULL),
('CZ-712', 'to', 'ʻOlomouki'),
('CZ-713', 'to', 'Prositejov'),
('CZ-714', 'to', 'Přerov'),
('CZ-715', 'to', 'Sumperk'),
('CZ-72', 'to', 'Zlinsky'),
('CZ-721', 'to', 'Kolomeříž'),
('CZ-722', 'to', NULL),
('CZ-723', 'to', 'Vesetini'),
('CZ-724', 'to', 'Zlín'),
('CZ-80', 'to', 'Moravskoslezsky'),
('CZ-801', 'to', NULL),
('CZ-802', 'to', NULL),
('CZ-803', 'to', 'Kāviná'),
('CZ-804', 'to', 'Novī Sisini'),
('CZ-805', 'to', 'Opava'),
('CZ-806', 'to', 'ʻOsitalava-mesito');

SET FOREIGN_KEY_CHECKS=1;
