SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('US-AK', 'km', 'អាឡាស្កា'),
('US-AL', 'km', 'អាឡាបាម៉ា'),
('US-AR', 'km', NULL),
('US-AS', 'km', 'សាម័រអាមេរិក'),
('US-AZ', 'km', 'អារីហ្សូណា'),
('US-CA', 'km', 'កាលីហ្វញ៉ា'),
('US-CO', 'km', 'ខូឡូរ៉ាដូ'),
('US-CT', 'km', 'ខុនណេកទីខាត់'),
('US-DC', 'km', 'ស្រុកកូឡុំប៊ី'),
('US-DE', 'km', NULL),
('US-FL', 'km', 'ផ្លរីដា'),
('US-GA', 'km', 'ហ្សកហ្ស៊ី'),
('US-GU', 'km', 'កោះហ្គាំ'),
('US-HI', 'km', 'ហាវ៉ៃ'),
('US-IA', 'km', 'អាយអូវ៉ា'),
('US-ID', 'km', 'អៃដាហូ'),
('US-IL', 'km', 'អ៊ីលីណយ'),
('US-IN', 'km', NULL),
('US-KS', 'km', 'កានសាស'),
('US-KY', 'km', NULL),
('US-LA', 'km', NULL),
('US-MA', 'km', 'ម៉ាសាឈូសេត'),
('US-MD', 'km', 'ម៉ារីលែន'),
('US-ME', 'km', NULL),
('US-MI', 'km', 'មីឈីហ្គែន'),
('US-MN', 'km', 'មីនីសូតា'),
('US-MO', 'km', 'មីសសួរី'),
('US-MP', 'km', 'កោះម៉ារៀណាខាងជើង'),
('US-MS', 'km', 'មីស៊ីស៊ីពី'),
('US-MT', 'km', 'ម៉ុនតាណា'),
('US-NC', 'km', 'ខារ៉ូលីណាខាងជើង'),
('US-ND', 'km', 'ដាកូតាខាងជើង'),
('US-NE', 'km', 'នេប្រាស្កា'),
('US-NH', 'km', NULL),
('US-NJ', 'km', NULL),
('US-NM', 'km', 'ម៉ិកស៊ិកថ្មី។'),
('US-NV', 'km', 'រដ្ឋណេវ៉ាដា'),
('US-NY', 'km', 'ញូវយ៉ក'),
('US-OH', 'km', 'អូហៃអូ'),
('US-OK', 'km', 'អូក្លាហូម៉ា'),
('US-OR', 'km', 'អូរីហ្គិន'),
('US-PA', 'km', 'ផេនស៊ីលវ៉ានៀ'),
('US-PR', 'km', 'ព័រតូរីកូ'),
('US-RI', 'km', 'កោះរ៉ូដ'),
('US-SC', 'km', NULL),
('US-SD', 'km', 'ដាកូតាខាងត្បូង'),
('US-TN', 'km', 'តេណេសស៊ី'),
('US-TX', 'km', 'រដ្ឋតិចសាស់'),
('US-UM', 'km', 'សហរដ្ឋអាមេរិកកោះឆ្ងាយតូច'),
('US-UT', 'km', 'យូថាហ៍'),
('US-VA', 'km', NULL),
('US-VI', 'km', 'កោះវឺជីន សហរដ្ឋអាមេរិក'),
('US-VT', 'km', 'វឺម៉ុន'),
('US-WA', 'km', 'វ៉ាស៊ីនតោន'),
('US-WI', 'km', NULL),
('US-WV', 'km', NULL),
('US-WY', 'km', 'វីយ៉ូមីង');

SET FOREIGN_KEY_CHECKS=1;
