SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_countries_altnames` (`key`, `language_key`, `name`) VALUES
('MV', 'aa', NULL),
('MV', 'am', 'ማልዲቭስ'),
('MV', 'ar', 'جزر المالديف'),
('MV', 'az', 'Maldiv adaları'),
('MV', 'be', 'Мальдывы'),
('MV', 'bg', 'Малдиви'),
('MV', 'bn', 'মালদ্বীপ'),
('MV', 'bs', 'Maldivi'),
('MV', 'ca', 'Maldives'),
('MV', 'cs', 'Maledivy'),
('MV', 'da', 'Maldiverne'),
('MV', 'de', 'Malediven'),
('MV', 'dv', 'ދިވެހިރާއްޖެ'),
('MV', 'dz', 'མཱལ་དིབས'),
('MV', 'el', 'Μαλδίβες'),
('MV', 'en', 'Maldives'),
('MV', 'es', 'Maldivas'),
('MV', 'et', 'Maldiivid'),
('MV', 'fa', 'مالدیو'),
('MV', 'fi', 'Malediivit'),
('MV', 'fo', 'Maldivoyggjar'),
('MV', 'fr', 'Maldives'),
('MV', 'he', 'האיים המלדיביים'),
('MV', 'hr', 'Maldivi'),
('MV', 'ht', 'Maldives'),
('MV', 'hu', 'Maldív-szigetek'),
('MV', 'hy', 'Մալդիվներ'),
('MV', 'id', 'Maladewa'),
('MV', 'is', 'Maldíveyjar'),
('MV', 'it', 'Maldive'),
('MV', 'ja', 'モルディブ'),
('MV', 'ka', 'მალდივები'),
('MV', 'kk', 'Мальдив аралдары'),
('MV', 'kl', NULL),
('MV', 'km', 'ម៉ាល់ឌីវ'),
('MV', 'ko', '몰디브'),
('MV', 'ky', 'Мальдив'),
('MV', 'la', 'Insulae Maldivae'),
('MV', 'lb', 'Maldiven'),
('MV', 'lt', 'Maldyvai'),
('MV', 'lv', 'Maldīvija'),
('MV', 'mh', NULL),
('MV', 'mk', 'Малдиви'),
('MV', 'mn', 'Мальдив'),
('MV', 'ms', 'Maldives'),
('MV', 'mt', 'il-Maldivi'),
('MV', 'my', 'မော်လ်ဒိုက်'),
('MV', 'ne', 'माल्दिभ्स'),
('MV', 'nl', 'Maldiven'),
('MV', 'no', 'Maldivene'),
('MV', 'ny', 'Maldives'),
('MV', 'pl', 'Malediwy'),
('MV', 'pt', 'Maldivas'),
('MV', 'ro', 'Maldive'),
('MV', 'ru', 'Мальдивы'),
('MV', 'rw', 'Malidivezi'),
('MV', 'si', 'මාල දිවයින'),
('MV', 'sk', 'Maldivy'),
('MV', 'sl', 'Maldivi'),
('MV', 'sm', 'Maldives'),
('MV', 'so', 'Maaldiifis'),
('MV', 'sq', 'Maldive'),
('MV', 'sr', 'Малдиви'),
('MV', 'sv', 'Maldiverna'),
('MV', 'sw', 'Maldivi'),
('MV', 'tg', 'Малдив'),
('MV', 'th', 'มัลดีฟส์'),
('MV', 'tk', 'Maldiwler'),
('MV', 'tl', 'Maldives'),
('MV', 'to', 'Malativisi'),
('MV', 'tr', 'Maldivler'),
('MV', 'uk', 'Мальдіви'),
('MV', 'ur', 'مالدیپ'),
('MV', 'uz', 'Maldiv orollari'),
('MV', 'vi', 'Maldives'),
('MV', 'zh', '马尔代夫'),
('MV', 'zu', 'i-Maldives');

SET FOREIGN_KEY_CHECKS=1;
