SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('KE-01', 'lv', 'Baringo'),
('KE-02', 'lv', 'Bomet County'),
('KE-03', 'lv', 'Bungoma County'),
('KE-04', 'lv', 'Busia County'),
('KE-05', 'lv', 'Marakwet District'),
('KE-06', 'lv', 'Embu County'),
('KE-07', 'lv', 'Garissa County'),
('KE-08', 'lv', 'Homa Bay County'),
('KE-09', 'lv', 'Isiolo County'),
('KE-10', 'lv', 'Kajiado County'),
('KE-11', 'lv', 'Kakamega County'),
('KE-12', 'lv', 'Kericho County'),
('KE-13', 'lv', 'Kiambu County'),
('KE-14', 'lv', 'Kilifi County'),
('KE-15', 'lv', 'Kirinyaga County'),
('KE-16', 'lv', 'Kisii County'),
('KE-17', 'lv', 'Kisumu County'),
('KE-18', 'lv', 'Kitui County'),
('KE-19', 'lv', 'Kwale County'),
('KE-20', 'lv', 'Laikipia'),
('KE-21', 'lv', 'Lamu'),
('KE-22', 'lv', 'Machakos County'),
('KE-23', 'lv', 'Makueni County'),
('KE-24', 'lv', 'Mandera County'),
('KE-25', 'lv', 'Marsabit County'),
('KE-26', 'lv', 'Meru County'),
('KE-27', 'lv', 'Migori County'),
('KE-28', 'lv', 'Mombasa County'),
('KE-29', 'lv', 'Muranga County'),
('KE-30', 'lv', 'Nairobi province'),
('KE-31', 'lv', 'Nakuru County'),
('KE-32', 'lv', 'Nandi'),
('KE-33', 'lv', 'Narok County'),
('KE-34', 'lv', 'Nyamira county'),
('KE-35', 'lv', 'Nyandarua County'),
('KE-36', 'lv', 'Nyeri County'),
('KE-37', 'lv', 'Samburu County'),
('KE-38', 'lv', 'Siaya County'),
('KE-39', 'lv', 'Taita-Taveta County'),
('KE-40', 'lv', 'Tana River County'),
('KE-41', 'lv', 'Tharaka Nithi County'),
('KE-42', 'lv', 'Trans-Nzoia county'),
('KE-43', 'lv', 'Turkana County'),
('KE-44', 'lv', 'Uasin Gishu County'),
('KE-45', 'lv', 'Vihiga County'),
('KE-46', 'lv', 'Wajir County'),
('KE-47', 'lv', 'West Pokot County');

SET FOREIGN_KEY_CHECKS=1;
