SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('LT-01', 'lb', 'Akmenė'),
('LT-02', 'lb', 'Alytaus-Miestas'),
('LT-03', 'lb', 'Alytus'),
('LT-04', 'lb', 'Anykščiai'),
('LT-05', 'lb', 'Birštonas'),
('LT-06', 'lb', 'Biržai'),
('LT-07', 'lb', 'Druskininkai'),
('LT-08', 'lb', 'Elektrėnai'),
('LT-09', 'lb', 'Ignalina'),
('LT-10', 'lb', 'Jonava'),
('LT-11', 'lb', 'Joniškis'),
('LT-12', 'lb', 'Jurbarkas'),
('LT-13', 'lb', 'Kaišiadorys'),
('LT-14', 'lb', 'Kalvarija'),
('LT-15', 'lb', 'Kauno-Miestas'),
('LT-16', 'lb', 'Kaunas'),
('LT-17', 'lb', 'Kazlų Rūdos'),
('LT-18', 'lb', 'Kėdainiai'),
('LT-19', 'lb', 'Kelmė'),
('LT-20', 'lb', 'Klaipėdos miestas'),
('LT-21', 'lb', 'Klaipeda'),
('LT-22', 'lb', 'Kretinga'),
('LT-23', 'lb', 'Kupiškis'),
('LT-24', 'lb', 'Lazdijai'),
('LT-25', 'lb', 'Marijampolė'),
('LT-26', 'lb', 'Mažeikiai'),
('LT-27', 'lb', 'Molėtai'),
('LT-28', 'lb', 'Neringa'),
('LT-29', 'lb', 'Pagėgiai'),
('LT-30', 'lb', 'Pakrujis'),
('LT-31', 'lb', 'Palangos-Miestas'),
('LT-32', 'lb', 'Panevėžio-Miestas'),
('LT-33', 'lb', 'Panevėžys'),
('LT-34', 'lb', 'Pasvalys'),
('LT-35', 'lb', 'Plungė'),
('LT-36', 'lb', 'Prienai'),
('LT-37', 'lb', 'Radviliškis'),
('LT-38', 'lb', 'Raseiniai'),
('LT-39', 'lb', 'Rietavas'),
('LT-40', 'lb', 'Rokiškis'),
('LT-41', 'lb', 'Šakiai'),
('LT-42', 'lb', 'Šalčininkai'),
('LT-43', 'lb', 'Šiaulių miestas'),
('LT-44', 'lb', 'Šiauliai'),
('LT-45', 'lb', 'Šilalė'),
('LT-46', 'lb', 'Šilutė'),
('LT-47', 'lb', 'Širvintos'),
('LT-48', 'lb', 'Skuodas'),
('LT-49', 'lb', 'Švenčionys'),
('LT-50', 'lb', 'Tauragė'),
('LT-51', 'lb', 'Telšiai'),
('LT-52', 'lb', 'Trakai'),
('LT-53', 'lb', 'Ukmergė'),
('LT-54', 'lb', 'Utena'),
('LT-55', 'lb', 'Varėna'),
('LT-56', 'lb', 'Vilkaviškis'),
('LT-57', 'lb', 'Vilniaus miestas'),
('LT-58', 'lb', 'Vilnius'),
('LT-59', 'lb', 'Visaginas'),
('LT-60', 'lb', 'Zarasai'),
('LT-AL', 'lb', 'Alytus Grofschaft'),
('LT-KL', 'lb', 'Klaipeda Grofschaft'),
('LT-KU', 'lb', 'Kaunas Grofschaft'),
('LT-MR', 'lb', 'Marijampole Grofschaft'),
('LT-PN', 'lb', 'Panevëzys'),
('LT-SA', 'lb', 'Siauliai Grofschaft'),
('LT-TA', 'lb', 'Taurage Grofschaft'),
('LT-TE', 'lb', 'Telsiu Apskritis'),
('LT-UT', 'lb', 'Utena Grofschaft'),
('LT-VL', 'lb', 'Vilnius Grofschaft');

SET FOREIGN_KEY_CHECKS=1;
