SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('FR-01', 'pl', 'Ain'),
('FR-02', 'pl', 'Aisne'),
('FR-03', 'pl', 'Allier'),
('FR-04', 'pl', 'Alpes-de-Haute-Provence'),
('FR-05', 'pl', 'Hautes-Alpes'),
('FR-06', 'pl', 'Alpy-Maritimes'),
('FR-07', 'pl', 'Ardèche'),
('FR-08', 'pl', 'Ardeny'),
('FR-09', 'pl', 'Ariège'),
('FR-10', 'pl', 'Aube'),
('FR-11', 'pl', 'Aude'),
('FR-12', 'pl', 'Aveyron'),
('FR-13', 'pl', 'Bouches-du-Rhône'),
('FR-14', 'pl', 'Calvados'),
('FR-15', 'pl', 'Cantal'),
('FR-16', 'pl', 'Charente'),
('FR-17', 'pl', 'Charente-Maritime'),
('FR-18', 'pl', 'Cher'),
('FR-19', 'pl', 'Corrèze'),
('FR-20R', 'pl', 'Corse'),
('FR-21', 'pl', 'Côte-d''Or'),
('FR-22', 'pl', 'Côtes-d''Armor'),
('FR-23', 'pl', 'Creuse'),
('FR-24', 'pl', 'Dordogne'),
('FR-25', 'pl', 'Wątpliwości'),
('FR-26', 'pl', 'Drôme'),
('FR-27', 'pl', 'Eure'),
('FR-28', 'pl', 'Eure-et-Loir'),
('FR-29', 'pl', 'Finistère'),
('FR-2A', 'pl', 'Corse-du-Sud'),
('FR-2B', 'pl', 'Haute-Corse'),
('FR-30', 'pl', 'Gard'),
('FR-31', 'pl', 'Górna Garonna'),
('FR-32', 'pl', 'Gers'),
('FR-33', 'pl', 'Żyronda'),
('FR-34', 'pl', 'Hérault'),
('FR-35', 'pl', 'Ille-et-Vilaine'),
('FR-36', 'pl', 'Indre'),
('FR-37', 'pl', 'Indre-et-Loire'),
('FR-38', 'pl', 'Isère'),
('FR-39', 'pl', 'jura'),
('FR-40', 'pl', 'Landes'),
('FR-41', 'pl', 'Loir-et-Cher'),
('FR-42', 'pl', 'Loara'),
('FR-43', 'pl', 'Haute-Loire'),
('FR-44', 'pl', 'Loara Atlantycka'),
('FR-45', 'pl', 'Loiret'),
('FR-46', 'pl', 'Dużo'),
('FR-47', 'pl', 'Lot-et-Garonne'),
('FR-48', 'pl', 'Lozère'),
('FR-49', 'pl', 'Maine-et-Loire'),
('FR-50', 'pl', 'Manche'),
('FR-51', 'pl', 'Marna'),
('FR-52', 'pl', 'Haute-Marne'),
('FR-53', 'pl', 'Mayenne'),
('FR-54', 'pl', 'Meurthe-et-Moselle'),
('FR-55', 'pl', 'Moza'),
('FR-56', 'pl', 'Morbihan'),
('FR-57', 'pl', 'Mozela'),
('FR-58', 'pl', 'Nièvre'),
('FR-59', 'pl', 'Nord'),
('FR-60', 'pl', 'Oise'),
('FR-61', 'pl', 'Orne'),
('FR-62', 'pl', 'Pas-de-Calais'),
('FR-63', 'pl', 'Puy-de-Dôme'),
('FR-64', 'pl', 'Pyrénées-Atlantiques'),
('FR-65', 'pl', 'Górne Pireneje'),
('FR-66', 'pl', 'Pireneje Wschodnie'),
('FR-67', 'pl', 'Bas-Rhin'),
('FR-68', 'pl', 'Haut-Rhin'),
('FR-69', 'pl', 'Rodan'),
('FR-69M', 'pl', 'Metropole Lyon'),
('FR-6AE', 'pl', 'Alzacja'),
('FR-70', 'pl', 'Haute-Saône'),
('FR-71', 'pl', 'Saona i Loara'),
('FR-72', 'pl', 'Sarthe'),
('FR-73', 'pl', 'Savoie'),
('FR-74', 'pl', 'Górna Sabaudia'),
('FR-75C', 'pl', 'Paryż'),
('FR-76', 'pl', 'Sekwana-morska'),
('FR-77', 'pl', 'Seine-et-Marne'),
('FR-78', 'pl', 'Yvelines'),
('FR-79', 'pl', 'Deux-Sèvres'),
('FR-80', 'pl', 'Somma'),
('FR-81', 'pl', 'Tarn'),
('FR-82', 'pl', 'Tarn-et-Garonne'),
('FR-83', 'pl', 'Var'),
('FR-84', 'pl', 'Vaucluse'),
('FR-85', 'pl', 'Wandea'),
('FR-86', 'pl', 'Wiedeń'),
('FR-87', 'pl', 'Haute-Vienne'),
('FR-88', 'pl', 'Wogezy'),
('FR-89', 'pl', 'Yonne'),
('FR-90', 'pl', 'Territoire De Belfort'),
('FR-91', 'pl', 'Essonne'),
('FR-92', 'pl', 'Hauts-de-Seine'),
('FR-93', 'pl', 'Sekwana-Saint-Denis'),
('FR-94', 'pl', 'Val-de-Marna'),
('FR-95', 'pl', 'Val-d''Oise'),
('FR-971', 'pl', 'Gwadelupa'),
('FR-972', 'pl', 'Martynika'),
('FR-973', 'pl', 'Guyane (française)'),
('FR-974', 'pl', 'Reunion'),
('FR-976', 'pl', 'Majotta'),
('FR-ARA', 'pl', 'Owernia-Rodan-Alpy'),
('FR-BFC', 'pl', 'Burgundia-Franche-Comté'),
('FR-BL', 'pl', 'Saint-Barthélemy'),
('FR-BRE', 'pl', 'Bretania'),
('FR-CP', 'pl', 'Clipperton'),
('FR-CVL', 'pl', 'Region Centralny-Dolina Loary'),
('FR-GES', 'pl', 'Grand Est'),
('FR-HDF', 'pl', 'Hauts-de-France'),
('FR-IDF', 'pl', 'Île-de-France'),
('FR-MF', 'pl', 'Saint-Martin'),
('FR-NAQ', 'pl', 'Nowa Akwitania'),
('FR-NC', 'pl', 'Nouvelle-Calédonie'),
('FR-NOR', 'pl', 'Normandia'),
('FR-OCC', 'pl', 'Oksytania'),
('FR-PAC', 'pl', 'Prowansja-Alpy-Lazurowe Wybrzeże'),
('FR-PDL', 'pl', 'Kraj Loary'),
('FR-PF', 'pl', 'Polynésie française'),
('FR-PM', 'pl', 'Saint-Pierre-et-Miquelon'),
('FR-TF', 'pl', 'Terres australes françaises'),
('FR-WF', 'pl', 'Wallis-et-Futuna');

SET FOREIGN_KEY_CHECKS=1;
