SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('ID-AC', 'sk', 'Provincia Nanggroe Aceh Darussalam'),
('ID-BA', 'sk', 'Provinsi Bali'),
('ID-BB', 'sk', 'Kepulauan Bangka Belitung'),
('ID-BE', 'sk', 'Propinsi Bengkulu'),
('ID-BT', 'sk', 'Banten'),
('ID-GO', 'sk', 'Provincia Gorontalo'),
('ID-JA', 'sk', 'Provinsi Jambi'),
('ID-JB', 'sk', 'Jawa Barat'),
('ID-JI', 'sk', 'Jawa Timur'),
('ID-JK', 'sk', 'Daerah Khusus Ibukota Jakarta'),
('ID-JT', 'sk', 'Provincia Jawa Tengah'),
('ID-JW', 'sk', 'Jawa'),
('ID-KA', 'sk', 'Kalimantan'),
('ID-KB', 'sk', 'Provincia Kalimantan Barat'),
('ID-KI', 'sk', 'Provincia Kalimantan Timur'),
('ID-KR', 'sk', 'Provincia Kepulauan Riau'),
('ID-KS', 'sk', 'Provincia Kalimantan Selatan'),
('ID-KT', 'sk', 'Provincia Kalimantan Tengah'),
('ID-KU', 'sk', 'Severný Kalimantan'),
('ID-LA', 'sk', 'Provincia Lampung'),
('ID-MA', 'sk', 'Provinsi Maluku'),
('ID-ML', 'sk', 'Maluku'),
('ID-MU', 'sk', 'Severné Maluku'),
('ID-NB', 'sk', 'Západná Nusa Tenggara'),
('ID-NT', 'sk', 'Východná Nusa Tenggara'),
('ID-NU', 'sk', 'Nusa Tenggara'),
('ID-PA', 'sk', 'Provinsi Papua'),
('ID-PB', 'sk', 'Provincia Papua-Barat'),
('ID-PD', 'sk', 'Papua Barat Daya'),
('ID-PE', 'sk', 'Papua Pengunungan'),
('ID-PP', 'sk', 'Papua'),
('ID-PS', 'sk', 'Papua Selatan'),
('ID-PT', 'sk', 'Papua Tengah'),
('ID-RI', 'sk', 'Provinsi Riau'),
('ID-SA', 'sk', 'Sulawesi Utara'),
('ID-SB', 'sk', 'Provincia Sumatra Barat'),
('ID-SG', 'sk', 'Sulawesi Tenggara'),
('ID-SL', 'sk', 'Sulawesi'),
('ID-SM', 'sk', 'Sumatera'),
('ID-SN', 'sk', 'Provincia Sulawesi Selatan'),
('ID-SR', 'sk', 'Provincia Sulawesi Barat'),
('ID-SS', 'sk', 'Sumatera Selatan'),
('ID-ST', 'sk', 'Sulawesi Tengah'),
('ID-SU', 'sk', 'Severná Sumatra'),
('ID-YO', 'sk', 'Daerah Istimewa Yogyakarta');

SET FOREIGN_KEY_CHECKS=1;
