SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_countries_altnames` (`key`, `language_key`, `name`) VALUES
('SA', 'aa', NULL),
('SA', 'am', 'ሳውድአረቢያ'),
('SA', 'ar', 'المملكة العربية السعودية'),
('SA', 'az', 'Səudiyyə Ərəbistanı'),
('SA', 'be', 'Саудаўская Аравія'),
('SA', 'bg', 'Саудитска Арабия'),
('SA', 'bn', 'সৌদি আরব'),
('SA', 'bs', 'Saudijska Arabija'),
('SA', 'ca', 'Aràbia Saudí'),
('SA', 'cs', 'Saúdská Arábie'),
('SA', 'da', 'Saudi-Arabien'),
('SA', 'de', 'Saudi-Arabien'),
('SA', 'dv', 'ސައޫދީ އަރަބިއްޔާ'),
('SA', 'dz', 'སཱཝ་དི་ ཨ་རེ་བྷི་ཡ'),
('SA', 'el', 'Σαουδική Αραβία'),
('SA', 'en', 'Saudi Arabia'),
('SA', 'es', 'Arabia Saudí'),
('SA', 'et', 'Saudi Araabia'),
('SA', 'fa', 'عربستان سعودی'),
('SA', 'fi', 'Saudi-Arabia'),
('SA', 'fo', 'Saudiarabia'),
('SA', 'fr', 'Arabie saoudite'),
('SA', 'he', 'ערב הסעודית'),
('SA', 'hr', 'Saudijska Arabija'),
('SA', 'ht', 'Arabie saoudite'),
('SA', 'hu', 'Szaúd-Arábia'),
('SA', 'hy', 'Սաուդյան Արաբիա'),
('SA', 'id', 'Arab Saudi'),
('SA', 'is', 'Sádi-Arabía'),
('SA', 'it', 'Arabia Saudita'),
('SA', 'ja', 'サウジアラビア'),
('SA', 'ka', 'საუდის არაბეთი'),
('SA', 'kk', 'Сауд Арабиясы'),
('SA', 'kl', 'Saudi Arabia'),
('SA', 'km', 'អារ៉ាប៊ីសាអូឌីត'),
('SA', 'ko', '사우디아라비아'),
('SA', 'ky', 'Сауд Арабиясы'),
('SA', 'la', 'Arabia Saudiana'),
('SA', 'lb', 'Saudi-Arabien'),
('SA', 'lt', 'Saudo Arabija'),
('SA', 'lv', 'Saūda Arābija'),
('SA', 'mh', NULL),
('SA', 'mk', 'Саудиска Арабија'),
('SA', 'mn', 'Саудын Араб'),
('SA', 'ms', 'Arab Saudi'),
('SA', 'mt', 'l-Arabja Sawdija'),
('SA', 'my', 'ဆော်ဒီအာရေးဘီးယား'),
('SA', 'ne', 'साउदी अरब'),
('SA', 'nl', 'Saoedi-Arabië'),
('SA', 'no', 'Saudi-Arabia'),
('SA', 'ny', 'Saudi Arabia'),
('SA', 'pl', 'Arabia Saudyjska'),
('SA', 'pt', 'Arábia Saudita'),
('SA', 'ro', 'Arabia Saudită'),
('SA', 'ru', 'Саудовская Аравия'),
('SA', 'rw', 'Arabiya Sawudite'),
('SA', 'si', 'සෞදි අරාබිය'),
('SA', 'sk', 'Saudská Arábia'),
('SA', 'sl', 'Saudova Arabija'),
('SA', 'sm', 'Saudi Arabia'),
('SA', 'so', 'Sacuudi Carabiya'),
('SA', 'sq', 'Arabi Saudite'),
('SA', 'sr', 'Саудијска Арабија'),
('SA', 'sv', 'Saudiarabien'),
('SA', 'sw', 'Saudia'),
('SA', 'tg', 'Арабистони Саудӣ'),
('SA', 'th', 'ซาอุดีอาระเบีย'),
('SA', 'tk', 'Saud Arabystany'),
('SA', 'tl', 'Arabyang Saudi'),
('SA', 'to', 'Saute ʻAlepea'),
('SA', 'tr', 'Suudi Arabistan'),
('SA', 'uk', 'Саудівська Аравія'),
('SA', 'ur', 'سعودی عرب'),
('SA', 'uz', 'Saudiya Arabistoni'),
('SA', 'vi', 'Ả Rập Xê-út'),
('SA', 'zh', '沙特阿拉伯'),
('SA', 'zu', 'i-Saudi Arabia');

SET FOREIGN_KEY_CHECKS=1;
