SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('HU-BA', 'bg', 'Бараня'),
('HU-BC', 'bg', 'Бекешчаба'),
('HU-BE', 'bg', 'Бекеш'),
('HU-BK', 'bg', 'Бач-Кишкун'),
('HU-BU', 'bg', 'Будапеща'),
('HU-BZ', 'bg', 'Боршод-Абауй-Земплен'),
('HU-CS', 'bg', 'Чонград'),
('HU-DE', 'bg', 'Дебрецен'),
('HU-DU', 'bg', 'Дунауйварош'),
('HU-EG', 'bg', 'Егер'),
('HU-ER', 'bg', 'Ерд'),
('HU-FE', 'bg', 'Фейер'),
('HU-GS', 'bg', 'Дьор-Мошон-Шопрон'),
('HU-GY', 'bg', 'Гьор'),
('HU-HB', 'bg', 'Хайду-Бихар'),
('HU-HE', 'bg', 'Хевеш'),
('HU-HV', 'bg', NULL),
('HU-JN', 'bg', 'Яс-Надкун-Солнок'),
('HU-KE', 'bg', 'Комаром-Естергом'),
('HU-KM', 'bg', 'Кечкемет'),
('HU-KV', 'bg', 'Капошвар'),
('HU-MI', 'bg', 'Мишколц'),
('HU-NK', 'bg', 'Нагиканизса'),
('HU-NO', 'bg', 'Ноград'),
('HU-NY', 'bg', NULL),
('HU-PE', 'bg', 'Пещ'),
('HU-PS', 'bg', 'Печ'),
('HU-SD', 'bg', 'Сегед'),
('HU-SF', 'bg', 'Секешфехервар'),
('HU-SH', 'bg', 'Сомбатхей'),
('HU-SK', 'bg', 'Солнок'),
('HU-SN', 'bg', 'Шопрон'),
('HU-SO', 'bg', 'Шомод'),
('HU-SS', 'bg', NULL),
('HU-ST', 'bg', 'Салготарян'),
('HU-SZ', 'bg', 'Саболч-Сатмар-Берег'),
('HU-TB', 'bg', 'Татабаня'),
('HU-TO', 'bg', 'Толна'),
('HU-VA', 'bg', 'Ваш'),
('HU-VE', 'bg', 'Веспрем'),
('HU-VM', 'bg', 'Веспрем'),
('HU-ZA', 'bg', 'Зала'),
('HU-ZE', 'bg', 'Залаегерсег');

SET FOREIGN_KEY_CHECKS=1;
