SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('BF-01', 'da', 'Boucle du Mouhoun'),
('BF-02', 'da', 'Cascades'),
('BF-03', 'da', 'Centre'),
('BF-04', 'da', 'Centre-Est'),
('BF-05', 'da', 'Centre-Nord'),
('BF-06', 'da', 'Centre-Ouest'),
('BF-07', 'da', 'Centre-Sud'),
('BF-08', 'da', 'Est'),
('BF-09', 'da', 'Hauts-Bassins'),
('BF-10', 'da', 'Nord'),
('BF-11', 'da', 'Plateau-Central'),
('BF-12', 'da', 'Sahel'),
('BF-13', 'da', 'Sud-Ouest'),
('BF-BAL', 'da', 'Balé'),
('BF-BAM', 'da', 'Bam'),
('BF-BAN', 'da', 'Banwa'),
('BF-BAZ', 'da', 'Bazèga'),
('BF-BGR', 'da', 'Bougouriba'),
('BF-BLG', 'da', 'Boulgou'),
('BF-BLK', 'da', 'Boulkiemdé'),
('BF-COM', 'da', 'Comoé'),
('BF-GAN', 'da', 'Ganzourgou'),
('BF-GNA', 'da', 'Gnagna'),
('BF-GOU', 'da', 'Gourma'),
('BF-HOU', 'da', 'Houet'),
('BF-IOB', 'da', 'Ioba'),
('BF-KAD', 'da', 'Kadiogo'),
('BF-KEN', 'da', 'Kenédougou'),
('BF-KMD', 'da', 'Komondjari'),
('BF-KMP', 'da', 'Kompienga'),
('BF-KOP', 'da', 'Koulpélogo'),
('BF-KOS', 'da', 'Kossi'),
('BF-KOT', 'da', 'Kouritenga'),
('BF-KOW', 'da', 'Kourwéogo'),
('BF-LER', 'da', 'Léraba'),
('BF-LOR', 'da', 'Lorum'),
('BF-MOU', 'da', 'Mouhoun'),
('BF-NAM', 'da', 'Namentenga'),
('BF-NAO', 'da', 'Nahouri'),
('BF-NAY', 'da', 'Nayala'),
('BF-NOU', 'da', 'Noumbiel'),
('BF-OUB', 'da', 'Oubritenga'),
('BF-OUD', 'da', 'Oudalan'),
('BF-PAS', 'da', 'Passoré'),
('BF-PON', 'da', 'Poni'),
('BF-SEN', 'da', 'Séno'),
('BF-SIS', 'da', 'Sissili'),
('BF-SMT', 'da', 'Sanmatenga'),
('BF-SNG', 'da', 'Sanguié'),
('BF-SOM', 'da', 'Soum'),
('BF-SOR', 'da', 'Sourou'),
('BF-TAP', 'da', 'Tapoa'),
('BF-TUI', 'da', 'Tuy'),
('BF-YAG', 'da', 'Yagha'),
('BF-YAT', 'da', 'Yatenga'),
('BF-ZIR', 'da', 'Ziro'),
('BF-ZON', 'da', 'Zondoma'),
('BF-ZOU', 'da', 'Zoundwéogo');

SET FOREIGN_KEY_CHECKS=1;
