SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions` (`key`, `country`, `name`, `native_name`, `capital`, `population`, `timezone_utc`, `timezone_iana`) VALUES
('MA-01', 'MA', 'Tanger-Tetouan-Al Hoceima', 'طنجة - تطوان - الحسيمة', 2971712, 3556729, 'UTC+0', 'Africa/Casablanca'),
('MA-02', 'MA', 'Oriental', 'جهة الشرق', 2974539, 2314346, 'UTC+0', 'Africa/Casablanca'),
('MA-03', 'MA', 'Fes-Meknes', 'فاس-مكناس', 2977592, 4236892, 'UTC+0', 'Africa/Casablanca'),
('MA-04', 'MA', 'Rabat-Sale-Kenitra', NULL, 2975669, 4580866, 'UTC+0', 'Africa/Casablanca'),
('MA-05', 'MA', 'Beni Mellal-Khenifra', 'بني ملال - خنيفرة', 2981021, 2520776, 'UTC+0', 'Africa/Casablanca'),
('MA-06', 'MA', 'Casablanca-Settat', 'الدار البيضاء - سطات', 2980469, 6861739, 'UTC+0', 'Africa/Casablanca'),
('MA-07', 'MA', 'Marrakesh-Safi', 'مراكش آسفي', 2975180, 4520569, 'UTC+0', 'Africa/Casablanca'),
('MA-08', 'MA', 'Draa-Tafilalet', NULL, NULL, 1635008, 'UTC+0', 'Africa/Casablanca'),
('MA-09', 'MA', 'Souss-Massa', 'سوس ماسة', 2984062, 2676847, 'UTC+0', 'Africa/Casablanca'),
('MA-10', 'MA', 'Guelmim-Oued Noun', 'كلميم وادي نون', 2977466, 433757, 'UTC+0', 'Africa/Casablanca'),
('MA-11', 'MA', 'Laayoune-Sakia El Hamra', 'العيون - الساقية الحمراء', NULL, 367758, 'UTC+0', 'Africa/Casablanca'),
('MA-12', 'MA', 'Dakhla-Oued Ed-Dahab', NULL, NULL, 142955, 'UTC+0', 'Africa/El_Aaiun, Africa/Nouakchott, Africa/Casablanca'),
('MA-AGD', 'MA', 'Agadir-Ida-Ou-Tanane', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-AOU', 'MA', 'Aousserd (EH)', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-ASZ', 'MA', 'Assa-Zag (EH-partial)', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-AZI', 'MA', 'Azilal', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-BEM', 'MA', 'Béni Mellal', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-BER', 'MA', 'Berkane', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-BES', 'MA', 'Benslimane', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-BOD', 'MA', 'Boujdour (EH)', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-BOM', 'MA', 'Boulemane', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-BRR', 'MA', 'Berrechid', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-CAS', 'MA', 'Casablanca', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-CHE', 'MA', 'Chefchaouen', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-CHI', 'MA', 'Chichaoua', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-CHT', 'MA', 'Chtouka-Ait Baha', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-DRI', 'MA', 'Driouch', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-ERR', 'MA', 'Errachidia', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-ESI', 'MA', 'Essaouira', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-ESM', 'MA', 'Es-Semara (EH-partial)', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-FAH', 'MA', 'Fahs-Anjra', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-FES', 'MA', 'Fès', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-FIG', 'MA', 'Figuig', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-FQH', 'MA', 'Fquih Ben Salah', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-GUE', 'MA', 'Guelmim', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-GUF', 'MA', 'Guercif', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-HAJ', 'MA', 'El Hajeb', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-HAO', 'MA', 'Al Haouz', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-HOC', 'MA', 'Al Hoceïma', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-IFR', 'MA', 'Ifrane', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-INE', 'MA', 'Inezgane-Ait Melloul', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-JDI', 'MA', 'El Jadida', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-JRA', 'MA', 'Jerada', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-KEN', 'MA', 'Kénitra', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-KES', 'MA', 'El Kelâa des Sraghna', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-KHE', 'MA', 'Khémisset', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-KHN', 'MA', 'Khénifra', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-KHO', 'MA', 'Khouribga', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-LAA', 'MA', 'Laâyoune (EH)', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-LAR', 'MA', 'Larache', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-MAR', 'MA', 'Marrakech', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-MDF', 'MA', 'M’diq-Fnideq', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-MED', 'MA', 'Médiouna', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-MEK', 'MA', 'Meknès', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-MID', 'MA', 'Midelt', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-MOH', 'MA', 'Mohammadia', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-MOU', 'MA', 'Moulay Yacoub', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-NAD', 'MA', 'Nador', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-NOU', 'MA', 'Nouaceur', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-OUA', 'MA', 'Ouarzazate', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-OUD', 'MA', 'Oued Ed-Dahab (EH)', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-OUJ', 'MA', 'Oujda-Angad', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-OUZ', 'MA', 'Ouezzane', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-RAB', 'MA', 'Rabat', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-REH', 'MA', 'Rehamna', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-SAF', 'MA', 'Safi', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-SAL', 'MA', 'Salé', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-SEF', 'MA', 'Sefrou', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-SET', 'MA', 'Settat', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-SIB', 'MA', 'Sidi Bennour', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-SIF', 'MA', 'Sidi Ifni', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-SIK', 'MA', 'Sidi Kacem', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-SIL', 'MA', 'Sidi Slimane', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-SKH', 'MA', 'Skhirate-Témara', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-TAF', 'MA', 'Tarfaya (EH-partial)', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-TAI', 'MA', 'Taourirt', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-TAO', 'MA', 'Taounate', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-TAR', 'MA', 'Taroudannt', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-TAT', 'MA', 'Tata', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-TAZ', 'MA', 'Taza', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-TET', 'MA', 'Tétouan', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-TIN', 'MA', 'Tinghir', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-TIZ', 'MA', 'Tiznit', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-TNG', 'MA', 'Tanger-Assilah', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-TNT', 'MA', 'Tan-Tan (EH-partial)', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-YUS', 'MA', 'Youssoufia', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca'),
('MA-ZAG', 'MA', 'Zagora', NULL, NULL, NULL, 'UTC+0', 'Africa/Casablanca');

SET FOREIGN_KEY_CHECKS=1;
