SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('BD-01', 'to', NULL),
('BD-02', 'to', NULL),
('BD-03', 'to', NULL),
('BD-04', 'to', NULL),
('BD-05', 'to', NULL),
('BD-06', 'to', NULL),
('BD-07', 'to', 'Bhola'),
('BD-08', 'to', 'Kumila'),
('BD-09', 'to', NULL),
('BD-10', 'to', NULL),
('BD-11', 'to', NULL),
('BD-12', 'to', 'Chuatanga'),
('BD-13', 'to', NULL),
('BD-14', 'to', NULL),
('BD-15', 'to', NULL),
('BD-16', 'to', 'Feni'),
('BD-17', 'to', NULL),
('BD-18', 'to', NULL),
('BD-19', 'to', NULL),
('BD-20', 'to', 'Hapikani'),
('BD-21', 'to', 'Jamalipu'),
('BD-22', 'to', NULL),
('BD-23', 'to', NULL),
('BD-24', 'to', 'Sioipuhati'),
('BD-25', 'to', 'Jalakati'),
('BD-26', 'to', NULL),
('BD-27', 'to', 'Kulina'),
('BD-28', 'to', NULL),
('BD-29', 'to', NULL),
('BD-30', 'to', 'Kusitia'),
('BD-31', 'to', 'Lakisimipu'),
('BD-32', 'to', 'Lamonihati'),
('BD-33', 'to', 'Manikani'),
('BD-34', 'to', NULL),
('BD-35', 'to', NULL),
('BD-36', 'to', 'Mataripu'),
('BD-37', 'to', NULL),
('BD-38', 'to', NULL),
('BD-39', 'to', 'Mehepu'),
('BD-40', 'to', 'Nalayangani'),
('BD-41', 'to', 'Netalakona'),
('BD-42', 'to', 'Nasingi'),
('BD-43', 'to', 'Nalaili'),
('BD-44', 'to', 'Natole'),
('BD-45', 'to', 'Chapai Nauapikani'),
('BD-46', 'to', NULL),
('BD-47', 'to', 'Noakali'),
('BD-48', 'to', 'Naokaoni'),
('BD-49', 'to', 'Papina'),
('BD-50', 'to', NULL),
('BD-51', 'to', 'Patuakali'),
('BD-52', 'to', NULL),
('BD-53', 'to', NULL),
('BD-54', 'to', NULL),
('BD-55', 'to', NULL),
('BD-56', 'to', 'Langamati'),
('BD-57', 'to', NULL),
('BD-58', 'to', 'Satkhira'),
('BD-59', 'to', NULL),
('BD-60', 'to', NULL),
('BD-61', 'to', 'Sunamikani'),
('BD-62', 'to', NULL),
('BD-63', 'to', 'Tangaili'),
('BD-64', 'to', NULL),
('BD-A', 'to', 'Vahenga Barisal'),
('BD-B', 'to', NULL),
('BD-C', 'to', NULL),
('BD-D', 'to', 'Vahefonua Khulna'),
('BD-E', 'to', NULL),
('BD-F', 'to', 'Vahefonua Rangpur'),
('BD-G', 'to', 'Vahefonua Sylhet'),
('BD-H', 'to', 'Vahefonua Mymensingh');

SET FOREIGN_KEY_CHECKS=1;
