SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('CZ-10', 'hu', 'Prága'),
('CZ-20', 'hu', 'Közép-csehországi kerület'),
('CZ-201', 'hu', 'Benešov'),
('CZ-202', 'hu', 'Beroun'),
('CZ-203', 'hu', 'Kladno'),
('CZ-204', 'hu', 'Kolín'),
('CZ-205', 'hu', 'Kutná Hora'),
('CZ-206', 'hu', 'Mělník'),
('CZ-207', 'hu', 'Mladá Boleslav'),
('CZ-208', 'hu', 'Nymburk'),
('CZ-209', 'hu', 'Praha-východ'),
('CZ-20A', 'hu', 'Prága-západ'),
('CZ-20B', 'hu', 'Příbram'),
('CZ-20C', 'hu', 'Rakovník'),
('CZ-31', 'hu', 'Dél-csehországi kerület'),
('CZ-311', 'hu', 'České Budějovice'),
('CZ-312', 'hu', 'Český Krumlov'),
('CZ-313', 'hu', 'Jindřichův Hradec'),
('CZ-314', 'hu', 'Písek'),
('CZ-315', 'hu', 'Prachatice'),
('CZ-316', 'hu', 'Strakonice'),
('CZ-317', 'hu', 'Tábor'),
('CZ-32', 'hu', 'Plzeňi kerület'),
('CZ-321', 'hu', 'Domažlice'),
('CZ-322', 'hu', 'Klatovy'),
('CZ-323', 'hu', 'Plzeň-město'),
('CZ-324', 'hu', 'Plzeň-jih'),
('CZ-325', 'hu', 'Plzeň-sever'),
('CZ-326', 'hu', 'Rokycany'),
('CZ-327', 'hu', 'Tachov'),
('CZ-41', 'hu', 'Karlovy Vary-i kerület'),
('CZ-411', 'hu', 'Cheb'),
('CZ-412', 'hu', 'Karlovy Vary'),
('CZ-413', 'hu', 'Sokolov'),
('CZ-42', 'hu', 'Ústí nad Labem-i kerület'),
('CZ-421', 'hu', 'Děčín'),
('CZ-422', 'hu', 'Chomutov'),
('CZ-423', 'hu', 'Litoměřice'),
('CZ-424', 'hu', 'Louny'),
('CZ-425', 'hu', 'A legtöbb'),
('CZ-426', 'hu', 'Teplice'),
('CZ-427', 'hu', 'Ústí nad Labem'),
('CZ-51', 'hu', 'Libereci kerület'),
('CZ-511', 'hu', 'Česká Lípa'),
('CZ-512', 'hu', 'Jablonec nad Nisou'),
('CZ-513', 'hu', 'Liberec'),
('CZ-514', 'hu', 'Semily'),
('CZ-52', 'hu', 'Hradec Králové-i kerület'),
('CZ-521', 'hu', 'Hradec Králové'),
('CZ-522', 'hu', 'Jičín'),
('CZ-523', 'hu', 'Náchod'),
('CZ-524', 'hu', 'Rychnov nad Kněžnou'),
('CZ-525', 'hu', 'Trutnov'),
('CZ-53', 'hu', 'Pardubicei kerület'),
('CZ-531', 'hu', 'Chrudim'),
('CZ-532', 'hu', 'Pardubice'),
('CZ-533', 'hu', 'Szvitavy'),
('CZ-534', 'hu', 'Ústí nad Orlicí'),
('CZ-63', 'hu', 'Vysočina kerület'),
('CZ-631', 'hu', 'Havlíčkův Brod'),
('CZ-632', 'hu', 'Jihlava'),
('CZ-633', 'hu', 'Pelhřimov'),
('CZ-634', 'hu', 'Třebíč'),
('CZ-635', 'hu', 'Žďár nad Sázavou'),
('CZ-64', 'hu', 'Dél-Morva kerület'),
('CZ-641', 'hu', 'Blansko'),
('CZ-642', 'hu', 'Brno-město'),
('CZ-643', 'hu', 'Brno-venkov'),
('CZ-644', 'hu', 'Břeclav'),
('CZ-645', 'hu', 'Hodonín'),
('CZ-646', 'hu', 'Vyškov'),
('CZ-647', 'hu', 'Znojmo'),
('CZ-71', 'hu', 'Olomouci kerület'),
('CZ-711', 'hu', 'Jeseník'),
('CZ-712', 'hu', 'Olomouc'),
('CZ-713', 'hu', 'Prostějov'),
('CZ-714', 'hu', 'Přerov'),
('CZ-715', 'hu', 'Šumperk'),
('CZ-72', 'hu', 'Zlíni kerület'),
('CZ-721', 'hu', 'Kroměříž'),
('CZ-722', 'hu', 'Uherské Hradiště'),
('CZ-723', 'hu', 'Vsetín'),
('CZ-724', 'hu', 'Zlín'),
('CZ-80', 'hu', 'Morva-sziléziai kerület'),
('CZ-801', 'hu', 'Bruntál'),
('CZ-802', 'hu', 'Frýdek-Místek'),
('CZ-803', 'hu', 'Karviná'),
('CZ-804', 'hu', 'Nový Jičín'),
('CZ-805', 'hu', 'Opava'),
('CZ-806', 'hu', 'Ostrava-město');

SET FOREIGN_KEY_CHECKS=1;
