SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('MT-01', 'kl', 'Attard'),
('MT-02', 'kl', 'Balsan'),
('MT-03', 'kl', 'Birgu'),
('MT-04', 'kl', 'Birkirkara'),
('MT-05', 'kl', 'Birzebbuga'),
('MT-06', 'kl', 'Bormla'),
('MT-07', 'kl', 'Dingli'),
('MT-08', 'kl', 'Fgura'),
('MT-09', 'kl', 'Il-Furjana'),
('MT-10', 'kl', 'Fontana'),
('MT-11', 'kl', 'Gudja'),
('MT-12', 'kl', 'Gzira'),
('MT-13', 'kl', 'Ghajnsielem'),
('MT-14', 'kl', 'L-Qarb'),
('MT-15', 'kl', 'Hal Gharghur'),
('MT-16', 'kl', 'Ghasri'),
('MT-17', 'kl', 'Ghaxaq'),
('MT-18', 'kl', 'Hamrun'),
('MT-19', 'kl', 'L-Iklin'),
('MT-20', 'kl', 'L-Isla'),
('MT-21', 'kl', 'Kalkara'),
('MT-22', 'kl', 'Kercem'),
('MT-23', 'kl', 'Kirkop'),
('MT-24', 'kl', 'Lija'),
('MT-25', 'kl', 'Luqa'),
('MT-26', 'kl', 'Marsa'),
('MT-27', 'kl', 'Marsaskala'),
('MT-28', 'kl', 'Marsaxlokk'),
('MT-29', 'kl', 'Imdina'),
('MT-30', 'kl', 'Mellieha'),
('MT-31', 'kl', 'Imgarr'),
('MT-32', 'kl', 'Mosta'),
('MT-33', 'kl', 'Imqabba'),
('MT-34', 'kl', 'Imsida'),
('MT-35', 'kl', 'Imtarfa'),
('MT-36', 'kl', 'Munxar'),
('MT-37', 'kl', 'Nadur'),
('MT-38', 'kl', 'Naxxar'),
('MT-39', 'kl', 'Paola'),
('MT-40', 'kl', 'Pembroke'),
('MT-41', 'kl', 'Pieta'),
('MT-42', 'kl', 'Qala'),
('MT-43', 'kl', 'Qormi'),
('MT-44', 'kl', 'Qrendi'),
('MT-45', 'kl', 'Viktoria'),
('MT-46', 'kl', 'Rabat'),
('MT-47', 'kl', 'Safi'),
('MT-48', 'kl', 'Sankt Julianip'),
('MT-49', 'kl', 'San Gwann'),
('MT-50', 'kl', 'Sankt Lavrens'),
('MT-51', 'kl', NULL),
('MT-52', 'kl', 'Sannat'),
('MT-53', 'kl', 'Santa Lucija'),
('MT-54', 'kl', 'Santa Venera'),
('MT-55', 'kl', 'Siggiewi'),
('MT-56', 'kl', 'Sliema'),
('MT-57', 'kl', 'Swieqi'),
('MT-58', 'kl', 'Tarxien'),
('MT-59', 'kl', 'Ta'' Xbiex'),
('MT-60', 'kl', 'Valletta'),
('MT-61', 'kl', 'Xaghra'),
('MT-62', 'kl', 'Xewkija'),
('MT-63', 'kl', 'Xghajra'),
('MT-64', 'kl', 'Zabbar'),
('MT-65', 'kl', 'Iz-Zebbi'),
('MT-66', 'kl', 'Zebbug'),
('MT-67', 'kl', 'Zejtun'),
('MT-68', 'kl', 'Zurrieq');

SET FOREIGN_KEY_CHECKS=1;
