SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('PH-00', 'pt', 'Metro Manila'),
('PH-01', 'pt', 'Ilocos (Região I)'),
('PH-02', 'pt', 'Vale Cagayan (Região II)'),
('PH-03', 'pt', 'Luzon Central (Região III)'),
('PH-05', 'pt', 'Bicol (Região V)'),
('PH-06', 'pt', 'Visayas Ocidentais (Região VI)'),
('PH-07', 'pt', 'Visayas Centrais (Região VII)'),
('PH-08', 'pt', 'Visayas Orientais (Região VIII)'),
('PH-09', 'pt', 'Península de Zamboanga (Região IX)'),
('PH-10', 'pt', 'Norte de Mindanao (Região X)'),
('PH-11', 'pt', 'Davao (Região XI)'),
('PH-12', 'pt', 'Soccsksargen (Região XII)'),
('PH-13', 'pt', 'Caraga (Região XIII)'),
('PH-14', 'pt', 'Região Autônoma de Mindanao Muçulmana (ARMM)'),
('PH-15', 'pt', 'Região Administrativa da Cordilheira (CAR)'),
('PH-40', 'pt', 'Calabarzon (Região IV-A)'),
('PH-41', 'pt', 'Mimaropa (Região IV-B)'),
('PH-ABR', 'pt', 'Ilocos'),
('PH-AGN', 'pt', 'Vale Cagayan'),
('PH-AGS', 'pt', 'Centro de Luzón'),
('PH-AKL', 'pt', 'Aklan'),
('PH-ALB', 'pt', 'Bicol'),
('PH-ANT', 'pt', 'Visayas Ocidentais'),
('PH-APA', 'pt', 'Apayao'),
('PH-AUR', 'pt', 'aurora'),
('PH-BAN', 'pt', 'Visayas Centrais'),
('PH-BAS', 'pt', 'Basilan'),
('PH-BEN', 'pt', 'Norte de Mindanao'),
('PH-BIL', 'pt', 'Biliran'),
('PH-BOH', 'pt', 'Davao'),
('PH-BTG', 'pt', 'Península de Zamboanga'),
('PH-BTN', 'pt', 'Visayas Orientais'),
('PH-BUK', 'pt', 'Soccsksargen'),
('PH-BUL', 'pt', 'Caraga'),
('PH-CAG', 'pt', 'Região Autônoma de Mindanao Muçulmana'),
('PH-CAM', 'pt', 'Camiguin'),
('PH-CAN', 'pt', 'Região Administrativa da Cordilheira'),
('PH-CAP', 'pt', 'Capiz'),
('PH-CAS', 'pt', 'Camarines Sur'),
('PH-CAT', 'pt', 'Catanduanes'),
('PH-CAV', 'pt', 'Cavite'),
('PH-CEB', 'pt', 'Cebu'),
('PH-COM', 'pt', 'Davao de Oro'),
('PH-DAO', 'pt', 'Davao Oriental'),
('PH-DAS', 'pt', 'Davao del Sur'),
('PH-DAV', 'pt', 'Davao del Norte'),
('PH-DIN', 'pt', 'Ilhas Dinagat'),
('PH-DVO', 'pt', 'Davao Ocidental'),
('PH-EAS', 'pt', 'Samar Oriental'),
('PH-GUI', 'pt', 'Guimaras'),
('PH-IFU', 'pt', 'Ifugao'),
('PH-ILI', 'pt', 'Iloilo'),
('PH-ILN', 'pt', 'Ilocos Norte'),
('PH-ILS', 'pt', 'Ilocos Sur'),
('PH-ISA', 'pt', 'Isabela'),
('PH-KAL', 'pt', 'Kalinga'),
('PH-LAG', 'pt', 'Laguna'),
('PH-LAN', 'pt', 'Lanao del Norte'),
('PH-LAS', 'pt', 'Lanao del Sur'),
('PH-LEY', 'pt', 'Leyte'),
('PH-LUN', 'pt', 'La Union'),
('PH-MAD', 'pt', 'Marinduque'),
('PH-MAS', 'pt', 'Masbate'),
('PH-MDC', 'pt', 'Calabarzon'),
('PH-MDR', 'pt', 'Mimaropa'),
('PH-MGN', 'pt', 'Maguindanao del Norte'),
('PH-MGS', 'pt', 'Maguindanao del Sur'),
('PH-MOU', 'pt', 'Província da Montanha'),
('PH-MSC', 'pt', 'Misamis Ocidental'),
('PH-MSR', 'pt', 'Misamis Oriental'),
('PH-NCO', 'pt', 'Cotabato'),
('PH-NEC', 'pt', 'Negros Ocidental'),
('PH-NER', 'pt', 'Negros Oriental'),
('PH-NSA', 'pt', 'Samar do Norte'),
('PH-NUE', 'pt', 'Nova Écija'),
('PH-NUV', 'pt', 'Nova Vizcaya'),
('PH-PAM', 'pt', 'Pampanga'),
('PH-PAN', 'pt', 'Pangasinan'),
('PH-PLW', 'pt', 'Palawan'),
('PH-QUE', 'pt', 'Quezon'),
('PH-QUI', 'pt', 'Quirino'),
('PH-RIZ', 'pt', 'Rizal'),
('PH-ROM', 'pt', 'Romblon'),
('PH-SAR', 'pt', 'Sarangani'),
('PH-SCO', 'pt', 'Cotabato Sul'),
('PH-SIG', 'pt', 'Siquijor'),
('PH-SLE', 'pt', 'Leyte do Sul'),
('PH-SLU', 'pt', 'Sulu'),
('PH-SOR', 'pt', 'Sorsogon'),
('PH-SUK', 'pt', 'Sultão Kudarat'),
('PH-SUN', 'pt', 'Surigao del Norte'),
('PH-SUR', 'pt', 'Surigao del Sur'),
('PH-TAR', 'pt', 'Tarlac'),
('PH-TAW', 'pt', 'Tawi-Tawi'),
('PH-WSA', 'pt', 'Samar'),
('PH-ZAN', 'pt', 'Zamboanga do Norte'),
('PH-ZAS', 'pt', 'Zamboanga del Sur'),
('PH-ZMB', 'pt', 'Zambales'),
('PH-ZSI', 'pt', 'Zamboanga Sibupay');

SET FOREIGN_KEY_CHECKS=1;
