SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('US-AK', 'tl', 'Alaska'),
('US-AL', 'tl', 'Alabama'),
('US-AR', 'tl', 'Arkansas'),
('US-AS', 'tl', 'American Samoa'),
('US-AZ', 'tl', 'Arisona'),
('US-CA', 'tl', 'California'),
('US-CO', 'tl', 'Kolorado'),
('US-CT', 'tl', 'Connecticut'),
('US-DC', 'tl', 'District of Columbia'),
('US-DE', 'tl', 'Delaware'),
('US-FL', 'tl', 'Florida'),
('US-GA', 'tl', 'Georgia'),
('US-GU', 'tl', 'Guam'),
('US-HI', 'tl', 'Hawaii'),
('US-IA', 'tl', 'Ayowa'),
('US-ID', 'tl', 'Idaho'),
('US-IL', 'tl', 'Illinois'),
('US-IN', 'tl', 'Indiyana'),
('US-KS', 'tl', 'Kansas'),
('US-KY', 'tl', 'Kentaki'),
('US-LA', 'tl', 'Luwisiyana'),
('US-MA', 'tl', 'Massachusetts'),
('US-MD', 'tl', 'Maryland'),
('US-ME', 'tl', 'Maine'),
('US-MI', 'tl', 'Michigan'),
('US-MN', 'tl', 'Minnesota'),
('US-MO', 'tl', 'Misuri'),
('US-MP', 'tl', 'Northern Mariana Islands'),
('US-MS', 'tl', 'Misisipi'),
('US-MT', 'tl', 'Montana'),
('US-NC', 'tl', 'North Carolina'),
('US-ND', 'tl', 'North Dakota'),
('US-NE', 'tl', 'Nebraska'),
('US-NH', 'tl', 'New Hampshire'),
('US-NJ', 'tl', 'New Jersey'),
('US-NM', 'tl', 'New Mexico'),
('US-NV', 'tl', 'Nevada'),
('US-NY', 'tl', 'New York'),
('US-OH', 'tl', 'Ohio'),
('US-OK', 'tl', 'Oklahoma'),
('US-OR', 'tl', 'Oregon'),
('US-PA', 'tl', 'Pennsylvania'),
('US-PR', 'tl', 'Puerto Rico'),
('US-RI', 'tl', 'Rhode Island'),
('US-SC', 'tl', 'Timog Carolina'),
('US-SD', 'tl', 'South Dakota'),
('US-TN', 'tl', 'Tennessee'),
('US-TX', 'tl', 'Texas'),
('US-UM', 'tl', 'United States Minor Outlying Islands'),
('US-UT', 'tl', 'Utah'),
('US-VA', 'tl', 'Virginia'),
('US-VI', 'tl', 'Virgin Islands, U.S.'),
('US-VT', 'tl', 'Vermont'),
('US-WA', 'tl', 'Washington'),
('US-WI', 'tl', 'Wisconsin'),
('US-WV', 'tl', 'Kanlurang Virginia'),
('US-WY', 'tl', 'Wyoming');

SET FOREIGN_KEY_CHECKS=1;
