SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('AZ-ABS', 'uz', 'Absheron tumani'),
('AZ-AGA', 'uz', 'Agstafa rayoni'),
('AZ-AGC', 'uz', 'Ag''jabodi rayoni'),
('AZ-AGM', 'uz', 'Agʻdam tumani'),
('AZ-AGS', 'uz', 'Agdash rayoni'),
('AZ-AGU', 'uz', 'Agsu District'),
('AZ-AST', 'uz', 'Astara'),
('AZ-BA', 'uz', 'Boku'),
('AZ-BAB', 'uz', 'Babək'),
('AZ-BAL', 'uz', 'Balakan District'),
('AZ-BAR', 'uz', 'Barda'),
('AZ-BEY', 'uz', 'Beylagan tumani'),
('AZ-BIL', 'uz', 'Bilasuvar tumani'),
('AZ-CAB', 'uz', 'Jabrayil tumani'),
('AZ-CAL', 'uz', 'Jalilabad tumani'),
('AZ-CUL', 'uz', 'Kulfa'),
('AZ-DAS', 'uz', 'Dashkasan tumani'),
('AZ-FUZ', 'uz', 'Fuzuliy tumani'),
('AZ-GA', 'uz', 'Ganja'),
('AZ-GAD', 'uz', 'Gadabay District'),
('AZ-GOR', 'uz', 'Goranboy District'),
('AZ-GOY', 'uz', 'Goychay tumani'),
('AZ-GYG', 'uz', 'Goygol Rayon'),
('AZ-HAC', 'uz', 'Hojig‘abul tumani'),
('AZ-IMI', 'uz', 'Andoza:Imishli tumani hududiy birliklari'),
('AZ-ISM', 'uz', 'Andoza:Ismayilli tumani hududiy birliklari'),
('AZ-KAL', 'uz', 'Kalbajar tumani'),
('AZ-KAN', 'uz', 'Kǝngǝrli'),
('AZ-KUR', 'uz', 'Kordamir tumani'),
('AZ-LA', 'uz', 'Lankaron'),
('AZ-LAC', 'uz', 'Andoza:Lachin tumani hududiy birliklari'),
('AZ-LAN', 'uz', 'Andoza:Lankaran tumani hududiy birliklari'),
('AZ-LER', 'uz', 'Lerik tumani'),
('AZ-MAS', 'uz', 'Masalli'),
('AZ-MI', 'uz', 'Mingacevir City'),
('AZ-NA', 'uz', 'Naftalan shahri'),
('AZ-NEF', 'uz', 'Neftchala rayoni'),
('AZ-NV', 'uz', 'Naxçıvan'),
('AZ-NX', 'uz', 'Nakhchivon ASSR'),
('AZ-OGU', 'uz', 'O''g''uz rayoni'),
('AZ-ORD', 'uz', 'Ordubad'),
('AZ-QAB', 'uz', 'Qabala tumani'),
('AZ-QAX', 'uz', 'Qax tumani'),
('AZ-QAZ', 'uz', 'Qazax tumani'),
('AZ-QBA', 'uz', 'Quba tumani'),
('AZ-QBI', 'uz', 'Gubadli tumani'),
('AZ-QOB', 'uz', 'Gobustan tumani'),
('AZ-QUS', 'uz', 'Qusar tumani'),
('AZ-SA', 'uz', 'Shaki City'),
('AZ-SAB', 'uz', 'Sabirabad tumani'),
('AZ-SAD', 'uz', 'Sədərək'),
('AZ-SAH', 'uz', 'Shahbuz'),
('AZ-SAK', 'uz', 'Shaki'),
('AZ-SAL', 'uz', 'Salyan tumani'),
('AZ-SAR', 'uz', 'Şərur'),
('AZ-SAT', 'uz', 'Saatly Rayon'),
('AZ-SBN', 'uz', 'Shabran'),
('AZ-SIY', 'uz', 'Siazan rayoni'),
('AZ-SKR', 'uz', 'Shamkir tumani'),
('AZ-SM', 'uz', 'Sumgait'),
('AZ-SMI', 'uz', 'Shamaxi rayoni'),
('AZ-SMX', 'uz', 'Samux rayoni'),
('AZ-SR', 'uz', 'Shirvan'),
('AZ-SUS', 'uz', 'Shusha'),
('AZ-TAR', 'uz', 'Tartar tumani'),
('AZ-TOV', 'uz', 'Tuvuz tumani'),
('AZ-UCA', 'uz', 'Ujar tumani'),
('AZ-XA', 'uz', 'Xonkendi'),
('AZ-XAC', 'uz', 'Xachmaz rayoni'),
('AZ-XCI', 'uz', 'Xocalı tumani'),
('AZ-XIZ', 'uz', 'Xizi tumani'),
('AZ-XVD', 'uz', 'Khojävend'),
('AZ-YAR', 'uz', 'Yardimlı tumani'),
('AZ-YE', 'uz', 'Yevlax City'),
('AZ-YEV', 'uz', 'Yevlax rayoni'),
('AZ-ZAN', 'uz', 'Zangilan tumani'),
('AZ-ZAQ', 'uz', 'Zaqatala tumani'),
('AZ-ZAR', 'uz', 'Zardab');

SET FOREIGN_KEY_CHECKS=1;
