SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_countries_altnames` (`key`, `language_key`, `name`) VALUES
('NC', 'aa', NULL),
('NC', 'am', 'ኒው ካሌዶኒያ'),
('NC', 'ar', 'كاليدونيا الجديدة'),
('NC', 'az', 'Yeni Kaledoniya'),
('NC', 'be', 'Новая Каледонія'),
('NC', 'bg', 'Нова Каледония'),
('NC', 'bn', 'নিউ ক্যালেডোনিয়া'),
('NC', 'bs', 'Nova Kaledonija'),
('NC', 'ca', 'Nova Caledònia'),
('NC', 'cs', 'Nová Kaledonie'),
('NC', 'da', 'Ny Kaledonien'),
('NC', 'de', 'Neukaledonien'),
('NC', 'dv', 'ނިއު ކެލެޑޯނިއާ'),
('NC', 'dz', 'ནིའུ་ཀ་ལི་དོ་ནི་ཡ'),
('NC', 'el', 'Νέα Καληδονία'),
('NC', 'en', 'New Caledonia'),
('NC', 'es', 'Nueva Caledonia'),
('NC', 'et', 'Uus-Kaledoonia'),
('NC', 'fa', 'کالدونیای جدید'),
('NC', 'fi', 'Uusi-Kaledonia'),
('NC', 'fo', 'Nýkaledónia'),
('NC', 'fr', 'Nouvelle-Calédonie'),
('NC', 'he', 'קלדוניה החדשה'),
('NC', 'hr', 'Nova Kaledonija'),
('NC', 'ht', 'Nouvelle-Calédonie'),
('NC', 'hu', 'Új-Kaledónia'),
('NC', 'hy', 'Նոր Կալեդոնիա'),
('NC', 'id', 'Kaledonia Baru'),
('NC', 'is', 'Nýja-Kaledónía'),
('NC', 'it', 'Nuova Caledonia'),
('NC', 'ja', 'ニューカレドニア'),
('NC', 'ka', 'ახალი კალედონია'),
('NC', 'kk', 'Жаңа Каледония'),
('NC', 'kl', 'Nutaaq Caledonia'),
('NC', 'km', 'នូវែល​កាឡេដូនី'),
('NC', 'ko', '뉴칼레도니아'),
('NC', 'ky', 'Жаңы Каледония'),
('NC', 'la', 'Nova Caledonia'),
('NC', 'lb', 'Neikaledonien'),
('NC', 'lt', 'Naujoji Kaledonija'),
('NC', 'lv', 'Jaunkaledonija'),
('NC', 'mh', NULL),
('NC', 'mk', 'Нова Каледонија'),
('NC', 'mn', 'Шинэ Каледони'),
('NC', 'ms', 'New Caledonia'),
('NC', 'mt', 'New Caledonia'),
('NC', 'my', 'နယူး ကယ်လီဒိုနီးယား'),
('NC', 'ne', 'न्यु क्यालेडोनिया'),
('NC', 'nl', 'Nieuw-Caledonië'),
('NC', 'no', 'Ny-Caledonia'),
('NC', 'ny', 'New Caledonia'),
('NC', 'pl', 'Nowa Kaledonia'),
('NC', 'pt', 'Nova Caledônia'),
('NC', 'ro', 'Noua Caledonie'),
('NC', 'ru', 'Новая Каледония'),
('NC', 'rw', 'Nuveli Kalidoniya'),
('NC', 'si', 'නව කැලිඩෝනියාව'),
('NC', 'sk', 'Nová Kaledónia'),
('NC', 'sl', 'Nova Kaledonija'),
('NC', 'sm', 'Niu Kaletonia'),
('NC', 'so', 'Jasiiradda Niyuu Kaledooniya'),
('NC', 'sq', 'Kaledoni e Re'),
('NC', 'sr', 'Нова Каледонија'),
('NC', 'sv', 'Nya Kaledonien'),
('NC', 'sw', 'New Caledonia'),
('NC', 'tg', 'Каледонияи Нав'),
('NC', 'th', 'นิวแคลิโดเนีย'),
('NC', 'tk', 'Täze Kaledoniýa'),
('NC', 'tl', 'Bagong Caledonia'),
('NC', 'to', 'Niu Kaletōnia'),
('NC', 'tr', 'Yeni Kaledonya'),
('NC', 'uk', 'Нова Каледонія'),
('NC', 'ur', 'نیو کلیڈونیا'),
('NC', 'uz', 'Yangi Kaledoniya'),
('NC', 'vi', 'New Caledonia'),
('NC', 'zh', '新喀里多尼亚'),
('NC', 'zu', 'i-New Caledonia');

SET FOREIGN_KEY_CHECKS=1;
