SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('JP-01', 'lb', 'Hokkaido'),
('JP-02', 'lb', 'Aomori-ken'),
('JP-03', 'lb', 'Iwate'),
('JP-04', 'lb', 'Miyagi-ken'),
('JP-05', 'lb', 'Akita'),
('JP-06', 'lb', 'Yamagata-ken'),
('JP-07', 'lb', 'Fukushima-ken'),
('JP-08', 'lb', 'Ibaraki'),
('JP-09', 'lb', 'Tochigi'),
('JP-10', 'lb', 'Gunma-ken'),
('JP-11', 'lb', 'Saitama-ken'),
('JP-12', 'lb', 'Chiba-ken'),
('JP-13', 'lb', 'Tokio'),
('JP-14', 'lb', 'Kanagawa'),
('JP-15', 'lb', 'Niigata-ken'),
('JP-16', 'lb', 'Toyama-ken'),
('JP-17', 'lb', 'Ishikawa-ken'),
('JP-18', 'lb', 'Fukui'),
('JP-19', 'lb', 'Yamanashi'),
('JP-20', 'lb', 'Prefektur Nagano'),
('JP-21', 'lb', 'Gifu'),
('JP-22', 'lb', 'Shizuoka'),
('JP-23', 'lb', 'Aichi-ken'),
('JP-24', 'lb', 'Mie-ken'),
('JP-25', 'lb', 'Shiga'),
('JP-26', 'lb', 'Kyoto Präfektur'),
('JP-27', 'lb', 'Osaka-fu'),
('JP-28', 'lb', 'Hyogo'),
('JP-29', 'lb', 'Nara-ken'),
('JP-30', 'lb', 'Wakayama'),
('JP-31', 'lb', 'Tottori'),
('JP-32', 'lb', 'Shimane-ken'),
('JP-33', 'lb', 'Okayma-ken'),
('JP-34', 'lb', 'Hiroshima-ken'),
('JP-35', 'lb', 'Yamaguchi'),
('JP-36', 'lb', 'Tokushima-ken'),
('JP-37', 'lb', 'Kagawa-ken'),
('JP-38', 'lb', 'Ehime'),
('JP-39', 'lb', 'Kochi Präfektur'),
('JP-40', 'lb', 'Prefektur Fukuoka'),
('JP-41', 'lb', 'Saga-ken'),
('JP-42', 'lb', 'Nagasaki Präfektur'),
('JP-43', 'lb', 'Kumamoto'),
('JP-44', 'lb', 'Oita Präfektur'),
('JP-45', 'lb', 'Miyazaki'),
('JP-46', 'lb', 'Kagoshima-ken'),
('JP-47', 'lb', 'Okinawa');

SET FOREIGN_KEY_CHECKS=1;
