SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('BD-01', 'uz', 'Bandarban'),
('BD-02', 'uz', 'Barguna'),
('BD-03', 'uz', 'Bogura'),
('BD-04', 'uz', 'Brahmanbariya'),
('BD-05', 'uz', 'Bagerhat'),
('BD-06', 'uz', 'Barishal'),
('BD-07', 'uz', 'Bhola'),
('BD-08', 'uz', 'Cumilla'),
('BD-09', 'uz', 'Chandpur'),
('BD-10', 'uz', 'Chattogramma'),
('BD-11', 'uz', NULL),
('BD-12', 'uz', 'Chuadang'),
('BD-13', 'uz', 'Dakka'),
('BD-14', 'uz', 'Dinajpur'),
('BD-15', 'uz', 'Faridpur'),
('BD-16', 'uz', 'Feni'),
('BD-17', 'uz', 'Gopalganj'),
('BD-18', 'uz', 'Gazipur'),
('BD-19', 'uz', 'Gaibandha'),
('BD-20', 'uz', 'Habiganj'),
('BD-21', 'uz', 'Jamalpur'),
('BD-22', 'uz', 'Jashor'),
('BD-23', 'uz', 'Jhenaidah'),
('BD-24', 'uz', 'Joypurhat'),
('BD-25', 'uz', 'Jhalakathi'),
('BD-26', 'uz', 'Kishoreganj'),
('BD-27', 'uz', 'Khulna'),
('BD-28', 'uz', 'Kurigram'),
('BD-29', 'uz', 'Xagrachari'),
('BD-30', 'uz', 'Kushtiya'),
('BD-31', 'uz', 'Lakshmipur'),
('BD-32', 'uz', 'Lalmonirhat'),
('BD-33', 'uz', 'Manikganj'),
('BD-34', 'uz', 'Mymensingh'),
('BD-35', 'uz', 'Munshiganj'),
('BD-36', 'uz', 'Madaripur'),
('BD-37', 'uz', 'Magura'),
('BD-38', 'uz', 'Moulvibazar'),
('BD-39', 'uz', 'Meherpur'),
('BD-40', 'uz', 'Narayanganj'),
('BD-41', 'uz', 'Netrakona'),
('BD-42', 'uz', 'Narsingdi'),
('BD-43', 'uz', 'Narail'),
('BD-44', 'uz', 'Natore'),
('BD-45', 'uz', 'Chapai Nawabganj'),
('BD-46', 'uz', 'Nilphamari'),
('BD-47', 'uz', 'Noaxali'),
('BD-48', 'uz', 'Naogaon'),
('BD-49', 'uz', 'Pabna'),
('BD-50', 'uz', 'Pirojpur'),
('BD-51', 'uz', 'Patuaxali'),
('BD-52', 'uz', 'Panchagarh'),
('BD-53', 'uz', 'Rajbari'),
('BD-54', 'uz', 'Rajshahi'),
('BD-55', 'uz', 'Rangpur'),
('BD-56', 'uz', 'Rangamati'),
('BD-57', 'uz', 'Sherpur'),
('BD-58', 'uz', 'Satkhira'),
('BD-59', 'uz', 'Sirajganj'),
('BD-60', 'uz', 'Sylhet'),
('BD-61', 'uz', 'Sunamganj'),
('BD-62', 'uz', 'Shariatpur'),
('BD-63', 'uz', 'Tangail'),
('BD-64', 'uz', 'Thakurgaon'),
('BD-A', 'uz', 'Barisal Division'),
('BD-B', 'uz', 'Chittagong'),
('BD-C', 'uz', 'Dhaka Division'),
('BD-D', 'uz', 'Khulna Division'),
('BD-E', 'uz', 'Rajshahi Division'),
('BD-F', 'uz', 'Rangpur Division'),
('BD-G', 'uz', 'Sylhet Division'),
('BD-H', 'uz', 'Mymensingh bo''limi');

SET FOREIGN_KEY_CHECKS=1;
