SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions` (`key`, `country`, `name`, `native_name`, `capital`, `population`, `timezone_utc`, `timezone_iana`) VALUES
('BF-01', 'BF', 'Boucle du Mouhoun Region', 'Boucle du Mouhoun', 194117, 1434847, 'UTC+0', 'Africa/Bamako, Africa/Ouagadougou'),
('BF-02', 'BF', 'Cascades Region', 'Cascades', 195357, 524956, 'UTC+0', 'Africa/Ouagadougou'),
('BF-03', 'BF', 'Centre', 'Centre', NULL, 2136581, 'UTC+0', 'Africa/Ouagadougou'),
('BF-04', 'BF', 'Centre-Est', 'Centre-Est', 188257, 1132023, 'UTC+0', 'Africa/Ouagadougou, Africa/Lome, Africa/Accra'),
('BF-05', 'BF', 'Centre-Nord', 'Centre-Nord', 192537, 1203073, 'UTC+0', 'Africa/Ouagadougou'),
('BF-06', 'BF', 'Centre-Ouest', 'Centre-Ouest', 191986, 1348784, 'UTC+0', 'Africa/Ouagadougou'),
('BF-07', 'BF', 'Centre-Sud', 'Centre-Sud', 191251, 722631, 'UTC+0', 'Africa/Ouagadougou'),
('BF-08', 'BF', 'Est', 'Est', 193600, 1209399, 'UTC+0', 'Africa/Ouagadougou, Africa/Lome'),
('BF-09', 'BF', 'High-Basins Region', 'Hauts-Bassins', 194872, 1410284, 'UTC+0', 'Africa/Ouagadougou'),
('BF-10', 'BF', 'Nord', 'région Nord', 190316, 1182770, 'UTC+0', 'Africa/Ouagadougou'),
('BF-11', 'BF', 'Plateau-Central', 'Plateau-Central', 187041, 696372, 'UTC+0', 'Africa/Ouagadougou'),
('BF-12', 'BF', 'Sahel', 'Sahel', 193764, 968442, 'UTC+0, UTC+1', 'Africa/Ouagadougou, Africa/Niamey'),
('BF-13', 'BF', 'Southwest Region', 'Sud-Ouest', NULL, 624056, 'UTC+0', 'Africa/Ouagadougou, Africa/Abidjan'),
('BF-BAL', 'BF', 'Balé', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-BAM', 'BF', 'Bam', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-BAN', 'BF', 'Banwa', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-BAZ', 'BF', 'Bazèga', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-BGR', 'BF', 'Bougouriba', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-BLG', 'BF', 'Boulgou', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-BLK', 'BF', 'Boulkiemdé', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-COM', 'BF', 'Comoé', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-GAN', 'BF', 'Ganzourgou', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-GNA', 'BF', 'Gnagna', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-GOU', 'BF', 'Gourma', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-HOU', 'BF', 'Houet', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-IOB', 'BF', 'Ioba', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-KAD', 'BF', 'Kadiogo', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-KEN', 'BF', 'Kénédougou', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-KMD', 'BF', 'Komondjari', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-KMP', 'BF', 'Kompienga', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-KOP', 'BF', 'Koulpélogo', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-KOS', 'BF', 'Kossi', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-KOT', 'BF', 'Kouritenga', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-KOW', 'BF', 'Kourwéogo', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-LER', 'BF', 'Léraba', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-LOR', 'BF', 'Loroum', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-MOU', 'BF', 'Mouhoun', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-NAM', 'BF', 'Namentenga', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-NAO', 'BF', 'Nahouri', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-NAY', 'BF', 'Nayala', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-NOU', 'BF', 'Noumbiel', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-OUB', 'BF', 'Oubritenga', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-OUD', 'BF', 'Oudalan', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-PAS', 'BF', 'Passoré', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-PON', 'BF', 'Poni', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-SEN', 'BF', 'Séno', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-SIS', 'BF', 'Sissili', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-SMT', 'BF', 'Sanmatenga', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-SNG', 'BF', 'Sanguié', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-SOM', 'BF', 'Soum', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-SOR', 'BF', 'Sourou', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-TAP', 'BF', 'Tapoa', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-TUI', 'BF', 'Tuy', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-YAG', 'BF', 'Yagha', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-YAT', 'BF', 'Yatenga', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-ZIR', 'BF', 'Ziro', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-ZON', 'BF', 'Zondoma', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou'),
('BF-ZOU', 'BF', 'Zoundwéogo', NULL, NULL, NULL, 'UTC+0', 'Africa/Ouagadougou');

SET FOREIGN_KEY_CHECKS=1;
