SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('LV-002', 'id', 'Kotamadya Aizkraukle'),
('LV-007', 'id', 'Kotamadya Alūksne'),
('LV-011', 'id', 'Kotamadya Ādaži'),
('LV-015', 'id', 'Kotamadya Balvi'),
('LV-016', 'id', 'Kotamadya Bauska'),
('LV-022', 'id', 'Munisipalitas Cēsis'),
('LV-026', 'id', 'Munisipalitas Dobele'),
('LV-033', 'id', 'Kotamadya Gulbene'),
('LV-041', 'id', 'Kotamadya Jelgava'),
('LV-042', 'id', 'Munisipalitas Jēkabpils'),
('LV-047', 'id', 'Distrik Krāslava'),
('LV-050', 'id', 'Kotamadya Kuldīga'),
('LV-052', 'id', 'Munisipalitas Ķekava'),
('LV-054', 'id', 'Kotamadya Limbaži'),
('LV-056', 'id', 'Kotamadya Līvāni'),
('LV-058', 'id', 'Kotamadya Ludza'),
('LV-059', 'id', 'Kotamadya Madona'),
('LV-062', 'id', 'Kotamadya Mārupe'),
('LV-067', 'id', 'Munisipalitas Ogre'),
('LV-068', 'id', 'Kotamadya Olaine'),
('LV-073', 'id', 'Kotamadya Preiļi'),
('LV-077', 'id', 'Kotamadya Rēzekne'),
('LV-080', 'id', 'Kotamadya Ropaži'),
('LV-087', 'id', 'Kotamadya Salaspils'),
('LV-088', 'id', 'Kotamadya Saldus'),
('LV-089', 'id', 'Kotamadya Saulkrasti'),
('LV-091', 'id', 'Kotamadya Sigulda'),
('LV-094', 'id', 'Kotamadya Smiltene'),
('LV-097', 'id', 'Kotamadya Talsi'),
('LV-099', 'id', 'Munisipalitas Tukums'),
('LV-101', 'id', 'Kotamadya Valka'),
('LV-102', 'id', 'Kotamadya Varakļāni'),
('LV-106', 'id', 'Kotamadya Ventspils'),
('LV-111', 'id', 'Augsdaugavas novads'),
('LV-112', 'id', 'Dienvidkurzemes novads'),
('LV-113', 'id', 'Valmiera'),
('LV-DGV', 'id', 'Daugavpils'),
('LV-JEL', 'id', 'Jelgava'),
('LV-JUR', 'id', 'Jūrmala'),
('LV-LPX', 'id', 'Liepāja'),
('LV-REZ', 'id', 'Rēzekne'),
('LV-RIX', 'id', 'Riga'),
('LV-VEN', 'id', 'Ventspils');

SET FOREIGN_KEY_CHECKS=1;
