SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('KE-01', 'es', 'Condado de Baringo'),
('KE-02', 'es', 'Condado de Bomet'),
('KE-03', 'es', 'Condado de Bungoma'),
('KE-04', 'es', 'Condado de Busia'),
('KE-05', 'es', 'Condado de Elgeyo-Marakwet'),
('KE-06', 'es', 'Condado de Embu'),
('KE-07', 'es', 'Condado de Garissa'),
('KE-08', 'es', 'Condado de Homa Bay'),
('KE-09', 'es', 'Condado de Isiolo'),
('KE-10', 'es', 'Condado de Kajiado'),
('KE-11', 'es', 'Condado de Kakamega'),
('KE-12', 'es', 'Condado de Kericho'),
('KE-13', 'es', 'Condado de Kiambu'),
('KE-14', 'es', 'Distrito de Kilifi'),
('KE-15', 'es', 'Condado de Kirinyaga'),
('KE-16', 'es', 'Condado de Kisii'),
('KE-17', 'es', 'Condado de Kisumu'),
('KE-18', 'es', 'Condado de Kitui'),
('KE-19', 'es', 'Condado de Kwale'),
('KE-20', 'es', 'Condado de Laikipia'),
('KE-21', 'es', 'Lamu'),
('KE-22', 'es', 'Condado de Machakos'),
('KE-23', 'es', 'Condado de Makueni'),
('KE-24', 'es', 'Condado de Mandera'),
('KE-25', 'es', 'Marsabit'),
('KE-26', 'es', 'Condado de Meru'),
('KE-27', 'es', 'Condado de Migori'),
('KE-28', 'es', 'Condado de Mombasa'),
('KE-29', 'es', 'Condado de Muranga'),
('KE-30', 'es', 'Nairobi'),
('KE-31', 'es', 'Condado de Nakuru'),
('KE-32', 'es', 'Nandi'),
('KE-33', 'es', 'Condado de Narok'),
('KE-34', 'es', 'Condado de Nyamira'),
('KE-35', 'es', 'Condado de Nyandarua'),
('KE-36', 'es', 'Condado de Nyeri'),
('KE-37', 'es', 'Condado de Samburu'),
('KE-38', 'es', 'Distrito de Siaya'),
('KE-39', 'es', 'Taita-Taveta'),
('KE-40', 'es', 'Condado del Río Tana'),
('KE-41', 'es', 'Condado de Tharaka-Nithi'),
('KE-42', 'es', 'Condado de Trans-Nzoia'),
('KE-43', 'es', 'Condado de Turkana'),
('KE-44', 'es', 'Condado de Uasin Gishu'),
('KE-45', 'es', 'Condado de Vihiga'),
('KE-46', 'es', 'Condado de Wajir'),
('KE-47', 'es', 'Condado de West Pokot');

SET FOREIGN_KEY_CHECKS=1;
