SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions` (`key`, `country`, `name`, `native_name`, `capital`, `population`, `timezone_utc`, `timezone_iana`) VALUES
('GN-B', 'GN', 'Boke Region', 'Boké', 1692851, 1083147, 'UTC+0', 'Africa/Conakry'),
('GN-BE', 'GN', 'Beyla', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-BF', 'GN', 'Boffa', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-BK', 'GN', 'Boké', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-C', 'GN', 'Conakry Region', 'Région de Conakry', NULL, 1660973, 'UTC+0', 'Africa/Conakry'),
('GN-CO', 'GN', 'Coyah', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-D', 'GN', 'Kindia Region', 'Région de Kindia', 1690626, 1561374, 'UTC+0', 'Africa/Conakry'),
('GN-DB', 'GN', 'Dabola', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-DI', 'GN', 'Dinguiraye', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-DL', 'GN', 'Dalaba', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-DU', 'GN', 'Dubréka', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-F', 'GN', 'Faranah Region', 'Faranah', 1691779, 941554, 'UTC+0', 'Africa/Conakry'),
('GN-FA', 'GN', 'Faranah', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-FO', 'GN', 'Forécariah', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-FR', 'GN', 'Fria', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-GA', 'GN', 'Gaoual', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-GU', 'GN', 'Guékédou', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-K', 'GN', 'Kankan Region', 'Kankan', 1690928, 1972537, 'UTC+0', 'Africa/Conakry'),
('GN-KA', 'GN', 'Kankan', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-KB', 'GN', 'Koubia', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-KD', 'GN', 'Kindia', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-KE', 'GN', 'Kérouané', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-KN', 'GN', 'Koundara', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-KO', 'GN', 'Kouroussa', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-KS', 'GN', 'Kissidougou', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-L', 'GN', 'Labe Region', 'Labé', NULL, 994458, 'UTC+0', 'Africa/Conakry'),
('GN-LA', 'GN', 'Labé', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-LE', 'GN', 'Lélouma', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-LO', 'GN', 'Lola', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-M', 'GN', 'Mamou Region', 'région de Mamou', 1689561, 731188, 'UTC+0', 'Africa/Conakry'),
('GN-MC', 'GN', 'Macenta', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-MD', 'GN', 'Mandiana', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-ML', 'GN', 'Mali', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-MM', 'GN', 'Mamou', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-N', 'GN', 'Nzerekore Region', 'Nzérékoré', 1688989, 1578030, 'UTC+0', 'Africa/Conakry'),
('GN-NZ', 'GN', 'Nzérékoré', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-PI', 'GN', 'Pita', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-SI', 'GN', 'Siguiri', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-TE', 'GN', 'Télimélé', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-TO', 'GN', 'Tougué', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry'),
('GN-YO', 'GN', 'Yomou', NULL, NULL, NULL, 'UTC+0', 'Africa/Conakry');

SET FOREIGN_KEY_CHECKS=1;
