SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('DO-01', 'uz', 'Milli'),
('DO-02', 'uz', 'Azua viloyati'),
('DO-03', 'uz', 'Baoruco viloyati'),
('DO-04', 'uz', 'Barahona viloyati'),
('DO-05', 'uz', 'Dajabon'),
('DO-06', 'uz', 'Duarte viloyati'),
('DO-07', 'uz', 'Elias Pina'),
('DO-08', 'uz', 'El Seibo'),
('DO-09', 'uz', 'Espaillat viloyati'),
('DO-10', 'uz', 'Mustaqillik'),
('DO-11', 'uz', 'La Altagracia viloyati'),
('DO-12', 'uz', 'La Romana'),
('DO-13', 'uz', 'La Vega'),
('DO-14', 'uz', 'Maria Trinidad Sanchez'),
('DO-15', 'uz', 'Monte Kristi viloyati'),
('DO-16', 'uz', 'Pedernales viloyati'),
('DO-17', 'uz', 'Peraviya'),
('DO-18', 'uz', 'Puerto Plata'),
('DO-19', 'uz', 'Hermanas Mirabal'),
('DO-20', 'uz', 'Samana'),
('DO-21', 'uz', 'San-Kristobal'),
('DO-22', 'uz', 'San Juan viloyati'),
('DO-23', 'uz', 'San Pedro de Macoris'),
('DO-24', 'uz', 'Sanchez Ramirez'),
('DO-25', 'uz', 'Santiago viloyati'),
('DO-26', 'uz', 'Santyago Rodriges'),
('DO-27', 'uz', 'Valverde viloyati'),
('DO-28', 'uz', 'Monsenor Nouel'),
('DO-29', 'uz', 'Monte Plata viloyati'),
('DO-30', 'uz', 'Hato Mayor viloyati'),
('DO-31', 'uz', 'San Jose de Ocoa'),
('DO-32', 'uz', 'Santo Domingo viloyati'),
('DO-33', 'uz', 'Cibao Nordeste'),
('DO-34', 'uz', 'Cibao Noroeste'),
('DO-35', 'uz', 'Cibao Norte'),
('DO-36', 'uz', 'Cibao Sur'),
('DO-37', 'uz', 'El Valle'),
('DO-38', 'uz', 'Enriquillo'),
('DO-39', 'uz', 'Iguamo'),
('DO-40', 'uz', 'Ozama'),
('DO-41', 'uz', 'Valdeziya'),
('DO-42', 'uz', 'Yuma');

SET FOREIGN_KEY_CHECKS=1;
