SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('DO-01', 'et', 'Distrito Nacional'),
('DO-02', 'et', 'Azua'),
('DO-03', 'et', 'Bahoruco'),
('DO-04', 'et', 'Barahona'),
('DO-05', 'et', 'Dajabon'),
('DO-06', 'et', 'Duarte'),
('DO-07', 'et', 'Elias Pina'),
('DO-08', 'et', 'El Seibo'),
('DO-09', 'et', 'Espaillat'),
('DO-10', 'et', 'Independencia'),
('DO-11', 'et', 'La Altagracia'),
('DO-12', 'et', 'La Romana'),
('DO-13', 'et', 'La Vegas'),
('DO-14', 'et', 'Maria Trinidad Sanchez'),
('DO-15', 'et', 'Monte Cristi'),
('DO-16', 'et', 'Pedernales'),
('DO-17', 'et', 'Peravia'),
('DO-18', 'et', 'Puerto Plata'),
('DO-19', 'et', 'Hermanas Mirabal'),
('DO-20', 'et', 'Samana provints'),
('DO-21', 'et', 'San Cristóbal'),
('DO-22', 'et', 'San Juani'),
('DO-23', 'et', 'San Pedro de Macoris'),
('DO-24', 'et', 'Sanchez Ramirez'),
('DO-25', 'et', 'Santiago'),
('DO-26', 'et', 'Santiago Rodriguez'),
('DO-27', 'et', 'Valverde'),
('DO-28', 'et', 'Monsenor Nouel'),
('DO-29', 'et', 'Monte Plata'),
('DO-30', 'et', 'Hato Mayor'),
('DO-31', 'et', 'San Jose de Ocoa'),
('DO-32', 'et', 'Provincia de Santo Domingo'),
('DO-33', 'et', 'Cibao Nordeste'),
('DO-34', 'et', 'Cibao Noroeste'),
('DO-35', 'et', 'Cibao Norte'),
('DO-36', 'et', 'Cibao Sur'),
('DO-37', 'et', 'El Valle'),
('DO-38', 'et', 'Enriquillo'),
('DO-39', 'et', 'Higuamo'),
('DO-40', 'et', 'Ozama'),
('DO-41', 'et', 'Valdesias'),
('DO-42', 'et', 'Yuma');

SET FOREIGN_KEY_CHECKS=1;
