SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('GB-ABC', 'de', 'Armagh City, Banbridge und Craigavon'),
('GB-ABD', 'de', 'Aberdeenshire'),
('GB-ABE', 'de', 'Aberdeen City'),
('GB-AGB', 'de', 'Argyll und Bute'),
('GB-AGY', 'de', 'Insel Anglesey [Sir Ynys Môn GB-YNM]'),
('GB-AND', 'de', 'Ards und North Down'),
('GB-ANN', 'de', 'Antrim und Newtownabbey'),
('GB-ANS', 'de', 'Angus'),
('GB-BAS', 'de', 'Bath und Nordost-Somerset'),
('GB-BBD', 'de', 'Blackburn with Darwen'),
('GB-BCP', 'de', 'Bournemouth, Christchurch und Poole'),
('GB-BDF', 'de', 'Bedford'),
('GB-BDG', 'de', 'Barking und Dagenham'),
('GB-BEN', 'de', 'Brent'),
('GB-BEX', 'de', 'Bexley'),
('GB-BFS', 'de', 'Belfast City'),
('GB-BGE', 'de', 'Bridgend [Pen-y-bont ar Ogwr GB-POG]'),
('GB-BGW', 'de', 'Blaenau Gwent'),
('GB-BIR', 'de', 'Birmingham'),
('GB-BKM', 'de', 'Buckinghamshire'),
('GB-BNE', 'de', 'Barnet'),
('GB-BNH', 'de', 'Brighton und Hove'),
('GB-BNS', 'de', 'Barnsley'),
('GB-BOL', 'de', 'Bolton'),
('GB-BPL', 'de', 'Blackpool'),
('GB-BRC', 'de', 'Bracknell Forest'),
('GB-BRD', 'de', 'Bradford'),
('GB-BRY', 'de', 'Bromley'),
('GB-BST', 'de', 'Bristol, Stadt'),
('GB-BUR', 'de', 'Begraben'),
('GB-CAM', 'de', 'Cambridgeshire'),
('GB-CAY', 'de', 'Caerphilly [Caerffili GB-CAF]'),
('GB-CBF', 'de', 'Zentral-Bedfordshire'),
('GB-CCG', 'de', 'Causeway Coast und Glens'),
('GB-CGN', 'de', 'Ceredigion [Sir Ceredigion]'),
('GB-CHE', 'de', 'Cheshire East'),
('GB-CHW', 'de', 'Cheshire West und Chester'),
('GB-CLD', 'de', 'Calderdale'),
('GB-CLK', 'de', 'Clackmannanshire'),
('GB-CMA', 'de', 'Cumbria'),
('GB-CMD', 'de', 'Camden'),
('GB-CMN', 'de', 'Carmarthenshire [Sir Gaerfyrddin GB-GFY]'),
('GB-CON', 'de', 'Cornwall'),
('GB-COV', 'de', 'Coventry'),
('GB-CRF', 'de', 'Cardiff [Caerdydd GB-CRD]'),
('GB-CRY', 'de', 'Croydon'),
('GB-CWY', 'de', 'Conwy'),
('GB-DAL', 'de', 'Darlington'),
('GB-DBY', 'de', 'Derbyshire'),
('GB-DEN', 'de', 'Denbighshire [Sir Ddinbych GB-DDB]'),
('GB-DER', 'de', 'Derby'),
('GB-DEV', 'de', 'Devon'),
('GB-DGY', 'de', 'Dumfries und Galloway'),
('GB-DNC', 'de', 'Doncaster'),
('GB-DND', 'de', 'Dundee City'),
('GB-DOR', 'de', 'Dorset'),
('GB-DRS', 'de', 'Derry und Strabane'),
('GB-DUD', 'de', 'Dudley'),
('GB-DUR', 'de', 'Durham, Grafschaft'),
('GB-EAL', 'de', 'Ealing'),
('GB-EAY', 'de', 'East Ayrshire'),
('GB-EDH', 'de', 'Edinburgh, Stadt'),
('GB-EDU', 'de', 'Ost-Dunbartonshire'),
('GB-ELN', 'de', 'East Lothian'),
('GB-ELS', 'de', 'Eilean Siar'),
('GB-ENF', 'de', 'Enfield'),
('GB-ENG', 'de', 'England'),
('GB-ERW', 'de', 'East Renfrewshire'),
('GB-ERY', 'de', 'East Riding of Yorkshire'),
('GB-ESS', 'de', 'Essex'),
('GB-ESX', 'de', 'Ostsussex'),
('GB-FAL', 'de', 'Falkirk'),
('GB-FIF', 'de', 'Fife'),
('GB-FLN', 'de', 'Flintshire [Sir y Fflint GB-FFL]'),
('GB-FMO', 'de', 'Fermanagh und Omagh'),
('GB-GAT', 'de', 'Gateshead'),
('GB-GLG', 'de', 'Glasgow City'),
('GB-GLS', 'de', 'Gloucestershire'),
('GB-GRE', 'de', 'Greenwich'),
('GB-GWN', 'de', 'Gwynedd'),
('GB-HAL', 'de', 'Halton'),
('GB-HAM', 'de', 'Hampshire'),
('GB-HAV', 'de', 'Havering'),
('GB-HCK', 'de', 'Hackney'),
('GB-HEF', 'de', 'Herefordshire'),
('GB-HIL', 'de', 'Hillingdon'),
('GB-HLD', 'de', 'Hochland'),
('GB-HMF', 'de', 'Hammersmith und Fulham'),
('GB-HNS', 'de', 'Hounslow'),
('GB-HPL', 'de', 'Hartlepool'),
('GB-HRT', 'de', 'Hertfordshire'),
('GB-HRW', 'de', 'Egge'),
('GB-HRY', 'de', 'Haringey'),
('GB-IOS', 'de', 'Scilly-Inseln'),
('GB-IOW', 'de', 'Isle of Wight'),
('GB-ISL', 'de', 'Islington'),
('GB-IVC', 'de', 'Inverclyde'),
('GB-KEC', 'de', 'Kensington und Chelsea'),
('GB-KEN', 'de', 'Kent'),
('GB-KHL', 'de', 'Kingston upon Hull'),
('GB-KIR', 'de', 'Kirklees'),
('GB-KTT', 'de', 'Kingston upon Thames'),
('GB-KWL', 'de', 'Knowsley'),
('GB-LAN', 'de', 'Lancashire'),
('GB-LBC', 'de', 'Lisburn und Castlereagh'),
('GB-LBH', 'de', 'Lambeth'),
('GB-LCE', 'de', 'Leicester'),
('GB-LDS', 'de', 'Leeds'),
('GB-LEC', 'de', 'Leicestershire'),
('GB-LEW', 'de', 'Lewisham'),
('GB-LIN', 'de', 'Lincolnshire'),
('GB-LIV', 'de', 'Liverpool'),
('GB-LND', 'de', 'London, City of'),
('GB-LUT', 'de', 'Luton'),
('GB-MAN', 'de', 'Manchester'),
('GB-MDB', 'de', 'Middlesbrough'),
('GB-MDW', 'de', 'Medway'),
('GB-MEA', 'de', 'Mittleres und östliches Antrim'),
('GB-MIK', 'de', 'Milton Keynes'),
('GB-MLN', 'de', 'Midlothian'),
('GB-MON', 'de', 'Monmouthshire [Sir Fynwy GB-FYN]'),
('GB-MRT', 'de', 'Merton'),
('GB-MRY', 'de', 'Moray'),
('GB-MTY', 'de', 'Merthyr Tydfil [Merthyr Tudful GB-MTU]'),
('GB-MUL', 'de', 'Mitte Ulster'),
('GB-NAY', 'de', 'North Ayrshire'),
('GB-NBL', 'de', 'Northumberland'),
('GB-NEL', 'de', 'Nordost-Lincolnshire'),
('GB-NET', 'de', 'Newcastle upon Tyne'),
('GB-NFK', 'de', 'Norfolk'),
('GB-NGM', 'de', 'Nottingham'),
('GB-NIR', 'de', 'Nordirland'),
('GB-NLK', 'de', 'North Lanarkshire'),
('GB-NLN', 'de', 'Nord-Lincolnshire'),
('GB-NMD', 'de', 'Newry, Mourne und Down'),
('GB-NNH', 'de', 'Nord-Northamptonshire'),
('GB-NSM', 'de', 'Nord-Somerset'),
('GB-NTL', 'de', 'Unter Port Talbot [Castell-nedd Port Talbot GB-CTL]'),
('GB-NTT', 'de', 'Nottinghamshire'),
('GB-NTY', 'de', 'North Tyneside'),
('GB-NWM', 'de', 'Newham'),
('GB-NWP', 'de', 'Newport [Casnewydd GB-CNW]'),
('GB-NYK', 'de', 'Nord Yorkshire'),
('GB-OLD', 'de', 'Oldham'),
('GB-ORK', 'de', 'Orkney-Inseln'),
('GB-OXF', 'de', 'Oxfordshire'),
('GB-PEM', 'de', 'Pembrokeshire [Sir Benfro GB-BNF]'),
('GB-PKN', 'de', 'Perth und Kinross'),
('GB-PLY', 'de', 'Plymouth'),
('GB-POR', 'de', 'Portsmouth'),
('GB-POW', 'de', 'Powys'),
('GB-PTE', 'de', 'Peterborough'),
('GB-RCC', 'de', 'Redcar und Cleveland'),
('GB-RCH', 'de', 'Rochdale'),
('GB-RCT', 'de', 'Rhondda Cynon Taff [Rhondda CynonTaf]'),
('GB-RDB', 'de', 'Redbridge'),
('GB-RDG', 'de', 'Lesung'),
('GB-RFW', 'de', 'Renfrewshire'),
('GB-RIC', 'de', 'Richmond upon Thames'),
('GB-ROT', 'de', 'Rotherham'),
('GB-RUT', 'de', 'Rutland'),
('GB-SAW', 'de', 'Sandwell'),
('GB-SAY', 'de', 'Süd-Ayrshire'),
('GB-SCB', 'de', 'Schottische Grenzen'),
('GB-SCT', 'de', 'Schottland'),
('GB-SFK', 'de', 'Suffolk'),
('GB-SFT', 'de', 'Sefton'),
('GB-SGC', 'de', 'Süd-Gloucestershire'),
('GB-SHF', 'de', 'Sheffield'),
('GB-SHN', 'de', 'St. Helens'),
('GB-SHR', 'de', 'Shropshire'),
('GB-SKP', 'de', 'Stockport'),
('GB-SLF', 'de', 'Salford'),
('GB-SLG', 'de', 'Slough'),
('GB-SLK', 'de', 'Süd-Lanarkshire'),
('GB-SND', 'de', 'Sunderland'),
('GB-SOL', 'de', 'Solihull'),
('GB-SOM', 'de', 'Somerset'),
('GB-SOS', 'de', 'Southend-on-Sea'),
('GB-SRY', 'de', 'Surrey'),
('GB-STE', 'de', 'Stoke-on-Trent'),
('GB-STG', 'de', 'Stirling'),
('GB-STH', 'de', 'Southampton'),
('GB-STN', 'de', 'Sutton'),
('GB-STS', 'de', 'Staffordshire'),
('GB-STT', 'de', 'Stockton-on-Tees'),
('GB-STY', 'de', 'Süd-Tyneside'),
('GB-SWA', 'de', 'Swansea [Abertawe GB-ATA]'),
('GB-SWD', 'de', 'Swindon'),
('GB-SWK', 'de', 'Southwark'),
('GB-TAM', 'de', 'Tameside'),
('GB-TFW', 'de', 'Telford und Wrekin'),
('GB-THR', 'de', 'Thurrock'),
('GB-TOB', 'de', 'Torbay'),
('GB-TOF', 'de', 'Torfaen [Tor-faen]'),
('GB-TRF', 'de', 'Trafford'),
('GB-TWH', 'de', 'Tower Hamlets'),
('GB-VGL', 'de', 'Vale of Glamorgan, The [Bro Morgannwg GB-BMG]'),
('GB-WAR', 'de', 'Warwickshire'),
('GB-WBK', 'de', 'West Berkshire'),
('GB-WDU', 'de', 'West Dunbartonshire'),
('GB-WFT', 'de', 'Waltham Forest'),
('GB-WGN', 'de', 'Wigan'),
('GB-WIL', 'de', 'Wiltshire'),
('GB-WKF', 'de', 'Wakefield'),
('GB-WLL', 'de', 'Walsall'),
('GB-WLN', 'de', 'West Lothian'),
('GB-WLS', 'de', 'Wales'),
('GB-WLV', 'de', 'Wolverhampton'),
('GB-WND', 'de', 'Wandsworth'),
('GB-WNH', 'de', 'West Northamptonshire'),
('GB-WNM', 'de', 'Windsor und Maidenhead'),
('GB-WOK', 'de', 'Wokingham'),
('GB-WOR', 'de', 'Worcestershire'),
('GB-WRL', 'de', 'Wirral'),
('GB-WRT', 'de', 'Warrington'),
('GB-WRX', 'de', 'Wrexham [Wrecsam GB-WRC]'),
('GB-WSM', 'de', 'Westminster'),
('GB-WSX', 'de', 'West Sussex'),
('GB-YOR', 'de', 'York'),
('GB-ZET', 'de', 'Shetlandinseln');

SET FOREIGN_KEY_CHECKS=1;
