SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('JP-01', 'sl', 'Hokaido'),
('JP-02', 'sl', 'Prefektura Aomori'),
('JP-03', 'sl', 'Prefektura Ivate'),
('JP-04', 'sl', 'Prefektura Mijagi'),
('JP-05', 'sl', 'Prefektura Akita'),
('JP-06', 'sl', 'Jamagata'),
('JP-07', 'sl', 'prefektura Fukušima'),
('JP-08', 'sl', 'Prefektura Ibaraki'),
('JP-09', 'sl', 'Prefektura Točigi'),
('JP-10', 'sl', 'Prefektura Gunma'),
('JP-11', 'sl', 'Prefektura Saitama'),
('JP-12', 'sl', 'Prefektura Čiba'),
('JP-13', 'sl', 'Tokio'),
('JP-14', 'sl', 'Prefektura Kanagava'),
('JP-15', 'sl', 'Prefektura Nigata'),
('JP-16', 'sl', 'Prefektura Tojama'),
('JP-17', 'sl', 'Prefektura Išikava'),
('JP-18', 'sl', 'Prefektura Fukui'),
('JP-19', 'sl', 'Prefektura Jamanaši'),
('JP-20', 'sl', 'Prefektura Nagano'),
('JP-21', 'sl', 'Prefektura Gifu'),
('JP-22', 'sl', 'Prefektura Šizuoka'),
('JP-23', 'sl', 'Prefektura Aiči'),
('JP-24', 'sl', 'Prefektura Mie'),
('JP-25', 'sl', 'Prefektura Šiga'),
('JP-26', 'sl', 'Prefektura Kjoto'),
('JP-27', 'sl', 'Prefektura Osaka'),
('JP-28', 'sl', 'Prefektura Hjogo'),
('JP-29', 'sl', 'Prefektura Nara'),
('JP-30', 'sl', 'Prefektura Vakajama'),
('JP-31', 'sl', 'Prefektura Tottori'),
('JP-32', 'sl', 'Prefektura Šimane'),
('JP-33', 'sl', 'Prefektura Okajama'),
('JP-34', 'sl', 'Prefektura Hirošima'),
('JP-35', 'sl', 'Prefektura Jamaguči'),
('JP-36', 'sl', 'Prefektura Tokušima'),
('JP-37', 'sl', 'Prefektura Kagava'),
('JP-38', 'sl', 'Prefektura Ehime'),
('JP-39', 'sl', 'Prefektura Koči'),
('JP-40', 'sl', 'prefektura Fukuoka'),
('JP-41', 'sl', 'prefektura Saga'),
('JP-42', 'sl', 'prefektura Nagasaki'),
('JP-43', 'sl', 'prefektura Kumamoto'),
('JP-44', 'sl', 'Prefektura Ōita'),
('JP-45', 'sl', 'Prefektura Mijazaki'),
('JP-46', 'sl', 'Prefektura Kagošima'),
('JP-47', 'sl', 'prefektura Okinava');

SET FOREIGN_KEY_CHECKS=1;
