SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('DO-01', 'hu', 'Distrito Nacional'),
('DO-02', 'hu', 'Azua'),
('DO-03', 'hu', 'Bahoruco'),
('DO-04', 'hu', 'Barahona'),
('DO-05', 'hu', 'Dajabon'),
('DO-06', 'hu', 'Duarte'),
('DO-07', 'hu', 'Elias Pina'),
('DO-08', 'hu', 'El-Seybo'),
('DO-09', 'hu', 'Espaillat'),
('DO-10', 'hu', 'Independencia'),
('DO-11', 'hu', 'La Altagracia'),
('DO-12', 'hu', 'La Romana'),
('DO-13', 'hu', 'La Vega'),
('DO-14', 'hu', 'Maria Trinidad Sanchez'),
('DO-15', 'hu', 'Monte Cristi'),
('DO-16', 'hu', 'Pedernales'),
('DO-17', 'hu', 'Peravia'),
('DO-18', 'hu', 'Puerto Plata'),
('DO-19', 'hu', 'Hermanas'),
('DO-20', 'hu', 'Samana tartomány'),
('DO-21', 'hu', 'San Cristóbal'),
('DO-22', 'hu', 'San Juan'),
('DO-23', 'hu', 'San Pedro de Macoris'),
('DO-24', 'hu', 'Sanchez Ramirez'),
('DO-25', 'hu', 'Santiago'),
('DO-26', 'hu', 'Santiago Rodriguez'),
('DO-27', 'hu', 'Valverde'),
('DO-28', 'hu', 'Monsenor Nouel'),
('DO-29', 'hu', 'Monte Plata'),
('DO-30', 'hu', 'Hato Mayor'),
('DO-31', 'hu', 'San Jose de Ocoa'),
('DO-32', 'hu', 'Santo Domingo'),
('DO-33', 'hu', 'Cibao Nordeste'),
('DO-34', 'hu', 'Cibao Noroeste'),
('DO-35', 'hu', 'Cibao Norte'),
('DO-36', 'hu', 'Cibao Sur'),
('DO-37', 'hu', 'El Valle'),
('DO-38', 'hu', 'Enriquillo'),
('DO-39', 'hu', 'Higuamo'),
('DO-40', 'hu', 'Ozama'),
('DO-41', 'hu', 'Valdésia'),
('DO-42', 'hu', 'Yuma');

SET FOREIGN_KEY_CHECKS=1;
