SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('IN-AN', 'tl', 'Kapuluan ng Andaman at Nicobar'),
('IN-AP', 'tl', 'Andhra Pradesh'),
('IN-AR', 'tl', 'Arunachal Pradesh'),
('IN-AS', 'tl', 'Assam'),
('IN-BR', 'tl', 'Bihar'),
('IN-CG', 'tl', 'Chhattisgarh'),
('IN-CH', 'tl', 'Chandigarh'),
('IN-DH', 'tl', 'Dadra at Nagar Haveli at Daman at Diu'),
('IN-DL', 'tl', 'National Capital Territory of Delhi'),
('IN-GA', 'tl', 'Goa'),
('IN-GJ', 'tl', 'Gujarat'),
('IN-HP', 'tl', 'Himachal Pradesh'),
('IN-HR', 'tl', 'Haryana'),
('IN-JH', 'tl', 'Jharkhand'),
('IN-JK', 'tl', 'Jammu at Kashmir'),
('IN-KA', 'tl', 'Karnataka'),
('IN-KL', 'tl', 'Kerala'),
('IN-LA', 'tl', 'Ladakh'),
('IN-LD', 'tl', 'Lakshadweep'),
('IN-MH', 'tl', 'Maharashtra'),
('IN-ML', 'tl', 'Meghalaya'),
('IN-MN', 'tl', 'Manipur'),
('IN-MP', 'tl', 'Madhya Pradesh'),
('IN-MZ', 'tl', 'Mizoram'),
('IN-NL', 'tl', 'Nagaland'),
('IN-OD', 'tl', 'Odisha'),
('IN-PB', 'tl', 'Punjab, India'),
('IN-PY', 'tl', 'Puducherry'),
('IN-RJ', 'tl', 'Rajasthan'),
('IN-SK', 'tl', 'Sikkim'),
('IN-TN', 'tl', 'Tamil Nadu'),
('IN-TR', 'tl', 'Tripura'),
('IN-TS', 'tl', 'Telangana'),
('IN-UK', 'tl', 'Uttarakhand'),
('IN-UP', 'tl', 'Uttar Pradesh'),
('IN-WB', 'tl', 'Kanlurang Bengal');

SET FOREIGN_KEY_CHECKS=1;
