SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('MK-101', 'la', 'Veles'),
('MK-102', 'la', 'Stobi'),
('MK-103', 'la', 'Demir Kapija'),
('MK-104', 'la', 'Kavadarci'),
('MK-105', 'la', 'Lozovo'),
('MK-106', 'la', 'Negotino'),
('MK-107', 'la', 'Rosoman'),
('MK-108', 'la', 'Sveti Nikole'),
('MK-109', 'la', 'Caska'),
('MK-201', 'la', 'Berovo'),
('MK-202', 'la', 'Vinica'),
('MK-203', 'la', 'Delcevo'),
('MK-204', 'la', 'Zrnovci'),
('MK-205', 'la', 'Karbinci'),
('MK-206', 'la', 'Kocani'),
('MK-207', 'la', 'Makedonska Kamenica'),
('MK-208', 'la', 'Pehcevo'),
('MK-209', 'la', 'Probistip'),
('MK-210', 'la', 'Cesinovo-Oblesevo'),
('MK-211', 'la', 'Astibus'),
('MK-301', 'la', 'Vevcani'),
('MK-303', 'la', 'Debar'),
('MK-304', 'la', 'Debarca'),
('MK-307', 'la', 'Kicevo'),
('MK-308', 'la', 'Makedonski Brod'),
('MK-310', 'la', 'Ohrid'),
('MK-311', 'la', 'Plasnica'),
('MK-312', 'la', 'Struga'),
('MK-313', 'la', 'Centar Zupa'),
('MK-401', 'la', 'Bogdanci'),
('MK-402', 'la', 'Bosilovo'),
('MK-403', 'la', 'Valandovo'),
('MK-404', 'la', 'Vasilevo'),
('MK-405', 'la', 'Gevgelija'),
('MK-406', 'la', 'Opstina Dojran'),
('MK-407', 'la', 'Konce'),
('MK-408', 'la', 'Novo Selo'),
('MK-409', 'la', 'Radovis'),
('MK-410', 'la', 'Strumnitza'),
('MK-501', 'la', 'Bitola'),
('MK-502', 'la', 'Demir Hisar'),
('MK-503', 'la', 'Dolneni'),
('MK-504', 'la', 'Krivogastani'),
('MK-505', 'la', 'Krusevo'),
('MK-506', 'la', 'Mogila'),
('MK-507', 'la', 'Novaci'),
('MK-508', 'la', 'Prilep'),
('MK-509', 'la', 'Resen'),
('MK-601', 'la', 'Bogovine'),
('MK-602', 'la', 'Brvenica'),
('MK-603', 'la', 'Vrapciste'),
('MK-604', 'la', 'Draudacum'),
('MK-605', 'la', 'Zelino'),
('MK-606', 'la', 'Jegunovce'),
('MK-607', 'la', 'Mavrovo i Rostuse'),
('MK-608', 'la', 'Tearce'),
('MK-609', 'la', 'Tetovo'),
('MK-701', 'la', 'Kratovo'),
('MK-702', 'la', 'Kriva Palanka'),
('MK-703', 'la', 'Kumanovo'),
('MK-704', 'la', 'Opstina Lipkovo'),
('MK-705', 'la', 'Opstina Rankovce'),
('MK-706', 'la', 'Staro Nagoricane'),
('MK-801', 'la', 'Aerodrom †'),
('MK-802', 'la', 'Aracinovo'),
('MK-803', 'la', 'Butel †'),
('MK-804', 'la', 'Gazi Baba †'),
('MK-805', 'la', 'Gjorče Petrov †'),
('MK-806', 'la', 'Zelenikovo'),
('MK-807', 'la', 'Ilinden'),
('MK-808', 'la', 'Karpoš †'),
('MK-809', 'la', 'Kisela Voda †'),
('MK-810', 'la', 'Petrovec'),
('MK-811', 'la', 'Saraj †'),
('MK-812', 'la', 'Sopiste'),
('MK-813', 'la', 'Studenicani'),
('MK-814', 'la', 'Centar †'),
('MK-815', 'la', 'Čair †'),
('MK-816', 'la', 'Cucer-Sandevo'),
('MK-817', 'la', 'Suto Orizari †');

SET FOREIGN_KEY_CHECKS=1;
