SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_currencies_altnames` (`key`, `language_key`, `name`) VALUES
('AED', 'bs', 'Dirham Ujedinjenih Arapskih Emirata'),
('AFN', 'bs', 'Afganistanski afgan'),
('ALL', 'bs', 'Albanski lek'),
('AMD', 'bs', 'Armenski dram'),
('AOA', 'bs', 'Angolska kvanza'),
('ARS', 'bs', 'Argentinski pezos'),
('AUD', 'bs', 'Australijski dolar'),
('AWG', 'bs', 'Arubanski florin'),
('AZN', 'bs', 'Azerbejdžanski manat'),
('BAM', 'bs', 'Bosanskohercegovačka konvertibilna marka'),
('BBD', 'bs', 'Barbadoski dolar'),
('BDT', 'bs', 'Bangladeška taka'),
('BHD', 'bs', 'Bahreinski dinar'),
('BIF', 'bs', 'Burundski franak'),
('BMD', 'bs', 'Bermudski dolar'),
('BND', 'bs', 'Brunejski dolar'),
('BOB', 'bs', 'Bolivijski boliviano'),
('BOV', 'bs', 'Bolivijski mvdol'),
('BRL', 'bs', 'Brazilski real'),
('BSD', 'bs', 'Bahamski dolar'),
('BTN', 'bs', 'Butanski ngultrum'),
('BWP', 'bs', 'Bocvanska pula'),
('BYN', 'bs', 'Bjeloruska rublja'),
('BZD', 'bs', 'Belizeanski dolar'),
('CAD', 'bs', 'Kanadski dolar'),
('CDF', 'bs', 'Kongoanski franak'),
('CHE', 'bs', 'WIR Evro'),
('CHF', 'bs', 'Švicarski franak'),
('CHW', 'bs', 'WIR franak'),
('CLF', 'bs', 'Čileanski unidades de fomento'),
('CLP', 'bs', 'Čileanski pezos'),
('CNY', 'bs', 'Kineski juan'),
('COP', 'bs', 'Kolumbijski pezos'),
('COU', 'bs', 'Kolumbijski Unidade real de valor'),
('CRC', 'bs', 'Kostarikanski kolon'),
('CUP', 'bs', 'kubanski pezos'),
('CVE', 'bs', 'Zelenortski eskudo'),
('CZK', 'bs', 'Češka kruna'),
('DJF', 'bs', 'Džibutski franak'),
('DKK', 'bs', 'Danska kruna'),
('DOP', 'bs', 'Dominikanski pezos'),
('DZD', 'bs', 'Alžirski dinar'),
('EGP', 'bs', 'Egipatska funta'),
('ERN', 'bs', 'Eritrejska nakfa'),
('ETB', 'bs', 'Etiopski bir'),
('EUR', 'bs', 'Euro'),
('FJD', 'bs', 'Fidžijski dolar'),
('FKP', 'bs', 'Folklandska funta'),
('GBP', 'bs', 'Britanska funta'),
('GEL', 'bs', 'Gruzijski lari'),
('GHS', 'bs', 'Ganski cedi'),
('GIP', 'bs', 'Gibraltarska funta'),
('GMD', 'bs', 'Gambijski dalasi'),
('GNF', 'bs', 'Gvinejski franak'),
('GTQ', 'bs', 'Gvatemalski kecal'),
('GYD', 'bs', 'Gvajanski dolar'),
('HKD', 'bs', 'Honkonški dolar'),
('HNL', 'bs', 'Honduraška lempira'),
('HTG', 'bs', 'Haićanski gurd'),
('HUF', 'bs', 'Mađarska forinta'),
('IDR', 'bs', 'Indonežanska rupija'),
('ILS', 'bs', 'Izraelski novi šekel'),
('INR', 'bs', 'Indijska rupija'),
('IQD', 'bs', 'Irački dinar'),
('IRR', 'bs', 'Iranski rijal'),
('ISK', 'bs', 'Islandska kruna'),
('JMD', 'bs', 'Jamajčanski dolar'),
('JOD', 'bs', 'Jordanski dinar'),
('JPY', 'bs', 'Japanski jen'),
('KES', 'bs', 'Kenijski šiling'),
('KGS', 'bs', 'Kirgistanski som'),
('KHR', 'bs', 'Kambodžanski rijel'),
('KMF', 'bs', 'Komorski franak'),
('KPW', 'bs', 'Sjevernokorejski von'),
('KRW', 'bs', 'Južnokorejski von'),
('KWD', 'bs', 'Kuvajtski dinar'),
('KYD', 'bs', 'Kajmanski dolar'),
('KZT', 'bs', 'Kazahstanski tenge'),
('LAK', 'bs', 'Laoski kip'),
('LBP', 'bs', 'Libanska funta'),
('LKR', 'bs', 'Šrilankanska rupija'),
('LRD', 'bs', 'Liberijski dolar'),
('LSL', 'bs', 'Lesotski loti'),
('LYD', 'bs', 'Libijski dinar'),
('MAD', 'bs', 'Marokanski dirham'),
('MDL', 'bs', 'Moldavski lej'),
('MGA', 'bs', 'Malagaški arijari'),
('MKD', 'bs', 'Makedonski denar'),
('MMK', 'bs', 'Mijanmarski kjat'),
('MNT', 'bs', 'Mongolski tugrik'),
('MOP', 'bs', 'Makaonska pataka'),
('MRU', 'bs', 'mauritanijska ugvija'),
('MUR', 'bs', 'Mauricijska rupija'),
('MVR', 'bs', 'Maldivska rufija'),
('MWK', 'bs', 'Malavijska kvača'),
('MXN', 'bs', 'Meksički pezos'),
('MXV', 'bs', 'Meksijski unidad de inverzion'),
('MYR', 'bs', 'Malezijski ringit'),
('MZN', 'bs', 'Mozambijski metikal'),
('NAD', 'bs', 'Namibijski dolar'),
('NGN', 'bs', 'Nigerijska naira'),
('NIO', 'bs', 'Nikaragvanska kordoba'),
('NOK', 'bs', 'Norveška kruna'),
('NPR', 'bs', 'Nepalska rupija'),
('NZD', 'bs', 'Novozelandski dolar'),
('OMR', 'bs', 'Omanski rijal'),
('PAB', 'bs', 'Panamska balboa'),
('PEN', 'bs', 'Peruanski sol'),
('PGK', 'bs', 'Kina Papue Nove Gvineje'),
('PHP', 'bs', 'Filipinski pezos'),
('PKR', 'bs', 'Pakistanska rupija'),
('PLN', 'bs', 'Poljski zlot'),
('PYG', 'bs', 'Paragvajski gvarani'),
('QAR', 'bs', 'Katarski rijal'),
('RON', 'bs', 'Rumunski lej'),
('RSD', 'bs', 'Srpski dinar'),
('RUB', 'bs', 'Ruska rublja'),
('RWF', 'bs', 'Ruandski franak'),
('SAR', 'bs', 'Saudijski rijal'),
('SBD', 'bs', 'Solomonski dolar'),
('SCR', 'bs', 'Sejšelska rupija'),
('SDG', 'bs', 'Sudanska funta'),
('SEK', 'bs', 'Švedska kruna'),
('SGD', 'bs', 'Singapurski dolar'),
('SHP', 'bs', 'Svetohelenska funta'),
('SLE', 'bs', 'Sijeraleonski leone'),
('SOS', 'bs', 'Somalski šiling'),
('SRD', 'bs', 'Surinamski dolar'),
('SSP', 'bs', 'Južnosudanska funta'),
('STN', 'bs', 'Dobra Sao Toma i Principa'),
('SVC', 'bs', 'Salvadorski kolon'),
('SYP', 'bs', 'Sirijska funta'),
('SZL', 'bs', 'Svazilendski lilangeni'),
('THB', 'bs', 'Tajlandski baht'),
('TJS', 'bs', 'Tadžikistanski somoni'),
('TMT', 'bs', 'Turkmenistanski manat'),
('TND', 'bs', 'Tuniški dinar'),
('TOP', 'bs', 'Tonganska panga'),
('TRY', 'bs', 'Turska lira'),
('TTD', 'bs', 'Trinidadtobaški dolar'),
('TWD', 'bs', 'Novi tajvanski dolar'),
('TZS', 'bs', 'Tanzanijski šiling'),
('UAH', 'bs', 'Ukrajinska hrivnja'),
('UGX', 'bs', 'Ugandski šiling'),
('USD', 'bs', 'Američki dolar'),
('USN', 'bs', 'SAD dolar (sledeći dan)'),
('UYI', 'bs', 'Urugvajski pezo en unidades indeksades'),
('UYU', 'bs', 'Urugvajski pezos'),
('UYW', 'bs', 'Unidad Previsional'),
('UZS', 'bs', 'Uzbekistanski som'),
('VED', 'bs', 'Bolívar Soberano'),
('VES', 'bs', 'Venecuelanski bolivar'),
('VND', 'bs', 'Vijetnamski dong'),
('VUV', 'bs', 'Vanuatski vatu'),
('WST', 'bs', 'Samoanska tala'),
('XAD', 'bs', 'Arab Accounting Dinar'),
('XAF', 'bs', 'Centralnoafrički franak (CFA)'),
('XAG', 'bs', 'Srebro'),
('XAU', 'bs', 'Zlato'),
('XBA', 'bs', 'Evropska kompozitna jedinica'),
('XBB', 'bs', 'Evropska novčana jedinica'),
('XBC', 'bs', 'Evropska jedinica računa (XBC)'),
('XBD', 'bs', 'Evropska jedinica računa (XBD)'),
('XCD', 'bs', 'Istočnokaripski dolar'),
('XCG', 'bs', 'Caribbean Guilder'),
('XDR', 'bs', 'Posebna prava'),
('XOF', 'bs', 'Zapadnoafrički franak (CFA)'),
('XPD', 'bs', 'Paladijum'),
('XPF', 'bs', 'Franak (CFP)'),
('XPT', 'bs', 'Platina'),
('XSU', 'bs', 'Sucre'),
('XTS', 'bs', 'Kod testirane valute'),
('XUA', 'bs', 'ADB Unit of Account'),
('XXX', 'bs', 'Nepoznata valuta'),
('YER', 'bs', 'Jemenski rijal'),
('ZAR', 'bs', 'Južnoafrički rand'),
('ZMW', 'bs', 'Zambijska kvača'),
('ZWG', 'bs', 'Zimbabwe Gold');

SET FOREIGN_KEY_CHECKS=1;
