SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('SI-001', 'lb', 'Gemeng vun Ajdovscina'),
('SI-002', 'lb', 'Gemeng Beltinci'),
('SI-003', 'lb', 'Bled'),
('SI-004', 'lb', 'Gemeng Bohinj'),
('SI-005', 'lb', 'Gemeng vun Borovnica'),
('SI-006', 'lb', 'Gemeng Bovec'),
('SI-007', 'lb', 'Gemeng Brda'),
('SI-008', 'lb', 'Gemeng Brezovica'),
('SI-009', 'lb', 'Gemeng Brezice'),
('SI-010', 'lb', 'Gemeng vun Tisina'),
('SI-011', 'lb', 'Urban Gemeng vun Celje'),
('SI-012', 'lb', 'Gemeng Cerklje na Gorenjskem'),
('SI-013', 'lb', 'Gemeng Cerknica'),
('SI-014', 'lb', 'Gemeng Cerkno'),
('SI-015', 'lb', 'Gemeng Crensovci'),
('SI-016', 'lb', 'Gemeng Crna na Koroskem'),
('SI-017', 'lb', 'Gemeng Crnomelj'),
('SI-018', 'lb', 'Gemeng vun Destrnik'),
('SI-019', 'lb', 'Gemeng Divaca'),
('SI-020', 'lb', 'Gemeng Dobrepolje'),
('SI-021', 'lb', 'Gemeng Dobrova-Polhov Gradec'),
('SI-022', 'lb', 'Gemeng Dol pri Ljubljani'),
('SI-023', 'lb', 'Gemeng vun Domzale'),
('SI-024', 'lb', 'Gemeng Dornava'),
('SI-025', 'lb', 'Gemeng Dravograd'),
('SI-026', 'lb', 'Gemeng Duplek'),
('SI-027', 'lb', 'Gemeng Gorenja Vas-Poljane'),
('SI-028', 'lb', 'Gemeng Gorisnica'),
('SI-029', 'lb', 'Gemeng Gornja Radgona'),
('SI-030', 'lb', 'Gemeng Gornji Grad'),
('SI-031', 'lb', 'Gemeng Gornji Petrovci'),
('SI-032', 'lb', 'Gemeng Grosuplje'),
('SI-033', 'lb', 'Gemeng vun Salovci'),
('SI-034', 'lb', 'Gemeng Hrastnik'),
('SI-035', 'lb', 'Gemeng Hrpelje-Kozina'),
('SI-036', 'lb', 'Gemeng vun Idria'),
('SI-037', 'lb', 'Gemeng Ig'),
('SI-038', 'lb', 'Gemeng vun Ilirska Bistrica'),
('SI-039', 'lb', 'Gemeng vun Ivancna Gorica'),
('SI-040', 'lb', 'Gemeng vun Izola'),
('SI-041', 'lb', 'Gemeng Jesenice'),
('SI-042', 'lb', 'Gemeng Jursinci'),
('SI-043', 'lb', 'Gemeng Kamnik'),
('SI-044', 'lb', 'Gemeng Kanal ob Soci'),
('SI-045', 'lb', 'Gemeng Kidricevo'),
('SI-046', 'lb', 'Gemeng Kobarid'),
('SI-047', 'lb', 'Gemeng Kobilje'),
('SI-048', 'lb', 'Gemeng Kocevje'),
('SI-049', 'lb', 'Gemeng Komen'),
('SI-050', 'lb', 'Urban Gemeng Koper'),
('SI-051', 'lb', 'Gemeng Kozje'),
('SI-052', 'lb', 'Urban Gemeng Kranj'),
('SI-053', 'lb', 'Gemeng Kranjska Gora'),
('SI-054', 'lb', 'Urban Gemeng Krsko'),
('SI-055', 'lb', 'Gemeng Kungota'),
('SI-056', 'lb', 'Gemeng Kuzma'),
('SI-057', 'lb', 'Gemeng Lasko'),
('SI-058', 'lb', 'Gemeng Lenart'),
('SI-059', 'lb', 'Gemeng Lendava'),
('SI-060', 'lb', 'Gemeng Litija'),
('SI-061', 'lb', 'Urban Gemeng Ljubljana'),
('SI-062', 'lb', 'Gemeng Ljubno'),
('SI-063', 'lb', 'Gemeng Ljutomer'),
('SI-064', 'lb', 'Gemeng Logatec'),
('SI-065', 'lb', 'Obcina Loska Dolina'),
('SI-066', 'lb', 'Gemeng vun Loski Potok'),
('SI-067', 'lb', 'Gemeng Luce'),
('SI-068', 'lb', 'Gemeng Lukovica'),
('SI-069', 'lb', 'Gemeng Majsperk'),
('SI-070', 'lb', 'Urban Gemeng Maribor'),
('SI-071', 'lb', 'Gemeng vun Medvode'),
('SI-072', 'lb', 'Gemeng Menges'),
('SI-073', 'lb', 'Gemeng Metlika'),
('SI-074', 'lb', 'Gemeng Mezica'),
('SI-075', 'lb', 'Gemeng Miren-Kostanjevica'),
('SI-076', 'lb', 'Gemeng vun Mislinja'),
('SI-077', 'lb', 'Gemeng Moravce'),
('SI-078', 'lb', 'Gemeng vun Moravske Toplice'),
('SI-079', 'lb', 'Gemeng Mozirje'),
('SI-080', 'lb', 'Urban Gemeng Murska Sobota'),
('SI-081', 'lb', 'Gemeng Muta'),
('SI-082', 'lb', 'Gemeng vun Naklo'),
('SI-083', 'lb', 'Gemeng vun Nazarje'),
('SI-084', 'lb', 'Urban Gemeng vun Nova Gorica'),
('SI-085', 'lb', 'Urban Gemeng vun Novo Mesto'),
('SI-086', 'lb', 'Gemeng Odranci'),
('SI-087', 'lb', 'Gemeng Ormoz'),
('SI-088', 'lb', 'Gemeng Osilnica'),
('SI-089', 'lb', 'Gemeng Pesnica'),
('SI-090', 'lb', 'Piran'),
('SI-091', 'lb', 'Gemeng Pivka'),
('SI-092', 'lb', 'Gemeng Podcetrtek'),
('SI-093', 'lb', 'Gemeng Podvelka'),
('SI-094', 'lb', 'Gemeng Postojna'),
('SI-095', 'lb', 'Gemeng Preddvor'),
('SI-096', 'lb', 'Urban Gemeng Ptuj'),
('SI-097', 'lb', 'Gemeng Puconci'),
('SI-098', 'lb', 'Gemeng Race-Fram'),
('SI-099', 'lb', 'Gemeng Radece'),
('SI-100', 'lb', 'Gemeng Radenci'),
('SI-101', 'lb', 'Gemeng Radlje ob Dravi'),
('SI-102', 'lb', 'Gemeng Radovljica'),
('SI-103', 'lb', 'Gemeng Ravne na Koroskem'),
('SI-104', 'lb', 'Gemeng Ribnica'),
('SI-105', 'lb', 'Gemeng Rogasovci'),
('SI-106', 'lb', 'Gemeng Rogaska Slatina'),
('SI-107', 'lb', 'Gemeng vun Rogatec'),
('SI-108', 'lb', 'Gemeng Ruse'),
('SI-109', 'lb', 'Gemeng vun Semic'),
('SI-110', 'lb', 'Gemeng Sevnica'),
('SI-111', 'lb', 'Gemeng Sezana'),
('SI-112', 'lb', 'Urban Gemeng Slovenj Gradec'),
('SI-113', 'lb', 'Gemeng Slovenska Bistrica'),
('SI-114', 'lb', 'Gemeng Slovenske Konjice'),
('SI-115', 'lb', 'Gemeng Starse'),
('SI-116', 'lb', 'Gemeng Sveti Jurij ob Scavnici'),
('SI-117', 'lb', 'Gemeng Sencur'),
('SI-118', 'lb', 'Gemeng Sentilj'),
('SI-119', 'lb', 'Gemeng Sentjernej'),
('SI-120', 'lb', 'Gemeng Sentjur'),
('SI-121', 'lb', 'Gemeng Skocjan'),
('SI-122', 'lb', 'Gemeng Skofja Loka'),
('SI-123', 'lb', 'Gemeng Skofljica'),
('SI-124', 'lb', 'Gemeng Smarje pri Jelsah'),
('SI-125', 'lb', 'Gemeng vun Smartno ob Paki'),
('SI-126', 'lb', 'Gemeng Sostanj'),
('SI-127', 'lb', 'Gemeng vum Store'),
('SI-128', 'lb', 'Gemeng Tolmin'),
('SI-129', 'lb', 'Gemeng Trbovlje'),
('SI-130', 'lb', 'Gemeng vun Trebnje'),
('SI-131', 'lb', 'Gemeng Trzic'),
('SI-132', 'lb', 'Gemeng vun Turnisce'),
('SI-133', 'lb', 'Urban Gemeng Velenje'),
('SI-134', 'lb', 'Gemeng Velike Lasce'),
('SI-135', 'lb', 'Gemeng Videm'),
('SI-136', 'lb', 'Gemeng Vipava'),
('SI-137', 'lb', 'Gemeng Vitanje'),
('SI-138', 'lb', 'Gemeng Vodice'),
('SI-139', 'lb', 'Gemeng Vojnik'),
('SI-140', 'lb', 'Gemeng Vrhnika'),
('SI-141', 'lb', 'Gemeng Vuzenica'),
('SI-142', 'lb', 'Gemeng Zagorje ob Savi'),
('SI-143', 'lb', 'Gemeng Zavrc'),
('SI-144', 'lb', 'Gemeng Zrece'),
('SI-146', 'lb', 'Gemeng Zelezniki'),
('SI-147', 'lb', 'Gemeng vun Ziri'),
('SI-148', 'lb', 'Benedikt'),
('SI-149', 'lb', 'Gemeng Bistrica ob Sotli'),
('SI-150', 'lb', 'Gemeng Bloke'),
('SI-151', 'lb', 'Gemeng vun Braslovce'),
('SI-152', 'lb', 'Gemeng Cankova'),
('SI-153', 'lb', 'Gemeng Cerkvenjak'),
('SI-154', 'lb', 'Gemeng Dobje'),
('SI-155', 'lb', 'Gemeng Dobrna'),
('SI-156', 'lb', 'Gemeng vun Dobrovnik'),
('SI-157', 'lb', 'Gemeng Dolenjske Toplice'),
('SI-158', 'lb', 'Gemeng Grad'),
('SI-159', 'lb', 'Gemeng Hajdina'),
('SI-160', 'lb', 'Gemeng Hoce-Slivnica'),
('SI-161', 'lb', 'Gemeng Hodos'),
('SI-162', 'lb', 'Gemeng vun Horjul'),
('SI-163', 'lb', 'Gemeng Jezersko'),
('SI-164', 'lb', 'Komenda'),
('SI-165', 'lb', 'Gemeng Kostel'),
('SI-166', 'lb', 'Gemeng Krizevci'),
('SI-167', 'lb', 'Gemeng Lovrenc na Pohorju'),
('SI-168', 'lb', 'Gemeng vun Markovci'),
('SI-169', 'lb', 'Gemeng Miklavz na Dravskem Polju'),
('SI-170', 'lb', 'Gemeng Mirna Pec'),
('SI-171', 'lb', 'Gemeng vun Oplotnica'),
('SI-172', 'lb', 'Gemeng Podlehnik'),
('SI-173', 'lb', 'Gemeng Polzela'),
('SI-174', 'lb', 'Gemeng Prebold'),
('SI-175', 'lb', 'Gemeng Prevalje'),
('SI-176', 'lb', 'Gemeng Razkrizje'),
('SI-177', 'lb', 'Gemeng Ribnica na Pohorju'),
('SI-178', 'lb', 'Gemeng Selnica ob Dravi'),
('SI-179', 'lb', 'Gemeng Sodrazica'),
('SI-180', 'lb', 'Gemeng Solcava'),
('SI-181', 'lb', 'Gemeng vun Sveta Ana'),
('SI-182', 'lb', 'Obcina Sveti Andraz v Slovenskih goricah'),
('SI-183', 'lb', 'Gemeng Sempeter-Vrtojba'),
('SI-184', 'lb', 'Gemeng Tabor'),
('SI-185', 'lb', 'Gemeng Trnovska Vas'),
('SI-186', 'lb', 'Gemeng vun Trzin'),
('SI-187', 'lb', 'Gemeng vun Velika Polana'),
('SI-188', 'lb', 'Gemeng Verzej'),
('SI-189', 'lb', 'Gemeng Vransko'),
('SI-190', 'lb', 'Gemeng vun Zalec'),
('SI-191', 'lb', 'Gemeng Zetale'),
('SI-192', 'lb', 'Gemeng vun Zirovnica'),
('SI-193', 'lb', 'Gemeng Zuzemberk'),
('SI-194', 'lb', 'Gemeng vun Smartno pri Litiji'),
('SI-195', 'lb', 'Obcina Apace'),
('SI-196', 'lb', 'Gemeng Cirkulane'),
('SI-197', 'lb', 'Gemeng Kostanjevica na Krki'),
('SI-198', 'lb', 'Gemeng Makole'),
('SI-199', 'lb', 'Gemeng Mokronog-Trebelno'),
('SI-200', 'lb', 'Obcina Poljcane'),
('SI-201', 'lb', 'Obcina Rence-Vogrsko'),
('SI-202', 'lb', 'Obcina Sredisce ob Dravi'),
('SI-203', 'lb', 'Obcina Straza'),
('SI-204', 'lb', 'Obcina Sveta Trojica v Slovenskih goricah'),
('SI-205', 'lb', 'Obcina Sveti Tomaz'),
('SI-206', 'lb', 'Gemeng Smarjeske Toplice'),
('SI-207', 'lb', 'Gemeng Gorje'),
('SI-208', 'lb', 'Gemeng Log-Dragomer'),
('SI-209', 'lb', 'Obcina Recica ob Savinji'),
('SI-210', 'lb', 'Obcina Sveti Jurij v Slovenskih goricah'),
('SI-211', 'lb', 'Obcina Sentrupert'),
('SI-212', 'lb', 'Mirna'),
('SI-213', 'lb', 'Ankaran');

SET FOREIGN_KEY_CHECKS=1;
