SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('TH-10', 'zu', 'i-Bangkok'),
('TH-11', 'zu', 'I-Changwat Samut Prakan'),
('TH-12', 'zu', 'I-Changwat Nonthaburi'),
('TH-13', 'zu', 'pthumthani'),
('TH-14', 'zu', 'Phra Nakhon Si Ayutthaya'),
('TH-15', 'zu', 'I-Changwat Ang Thong'),
('TH-16', 'zu', 'I-Changwat Lop Buri'),
('TH-17', 'zu', 'I-Changwat Sing Buri'),
('TH-18', 'zu', 'Changwat Chai Nat'),
('TH-19', 'zu', 'sraburi'),
('TH-20', 'zu', 'Changwat Chon Buri'),
('TH-21', 'zu', 'Rayong'),
('TH-22', 'zu', 'canthburi'),
('TH-23', 'zu', 'I-Changwat Trat'),
('TH-24', 'zu', 'I-Changwat Chachoengsao'),
('TH-25', 'zu', 'pracinburi'),
('TH-26', 'zu', 'I-Changwat Nakhon Nayok'),
('TH-27', 'zu', 'I-Changwat Sa Kaeo'),
('TH-30', 'zu', 'I-Changwat Nakhon Ratchasima'),
('TH-31', 'zu', 'buriramy'),
('TH-32', 'zu', 'I-Changwat Surin'),
('TH-33', 'zu', 'I-Changwat Si Sa Ket'),
('TH-34', 'zu', 'I-Changwat Ubon Ratchathani'),
('TH-35', 'zu', 'I-Changwat Yasothon'),
('TH-36', 'zu', 'I-Changwat Chaiyaphum'),
('TH-37', 'zu', 'I-Changwat Amnat Charoen'),
('TH-38', 'zu', 'Changwat Bueng Kan'),
('TH-39', 'zu', 'I-Changwat Nong Bua Lamphu'),
('TH-40', 'zu', 'I-Changwat Khon Kaen'),
('TH-41', 'zu', 'I-Changwat Udon Thani'),
('TH-42', 'zu', 'Changwat Loei'),
('TH-43', 'zu', 'I-Changwat Nong Khai'),
('TH-44', 'zu', 'mhasarkham'),
('TH-45', 'zu', 'I-Changwat Roi Et'),
('TH-46', 'zu', 'I-Changwat Kalasin'),
('TH-47', 'zu', 'I-Changwat Sakon Nakhon'),
('TH-48', 'zu', 'I-Changwat Nakhon Phanom'),
('TH-49', 'zu', 'I-Changwat Mukdahan'),
('TH-50', 'zu', 'I-Changwat Chiang Mai'),
('TH-51', 'zu', 'laphun'),
('TH-52', 'zu', 'lapang'),
('TH-53', 'zu', 'I-Changwat Uttaradit'),
('TH-54', 'zu', 'I-Changwat Phrae'),
('TH-55', 'zu', 'nan'),
('TH-56', 'zu', 'I-Changwat Phayao'),
('TH-57', 'zu', 'I-Changwat Chiang Rai'),
('TH-58', 'zu', 'I-Changwat Mae Hong Son'),
('TH-60', 'zu', 'I-Changwat Nakhon Sawan'),
('TH-61', 'zu', 'I-Changwat Uthai Thani'),
('TH-62', 'zu', 'I-Changwat Kamphaeng Phet'),
('TH-63', 'zu', 'tak'),
('TH-64', 'zu', 'I-Changwat Sukhothai'),
('TH-65', 'zu', 'phis''nulok'),
('TH-66', 'zu', 'I-Changwat Phichit'),
('TH-67', 'zu', 'I-Changwat Phetchabun'),
('TH-70', 'zu', 'I-Changwat Ratchaburi'),
('TH-71', 'zu', 'I-Changwat Kanchanaburi'),
('TH-72', 'zu', 'Changwat Suphan Buri'),
('TH-73', 'zu', 'I-Changwat Nakhon Pathom'),
('TH-74', 'zu', 'I-Changwat Samut Sakhon'),
('TH-75', 'zu', 'I-Changwat Samut Songkhram'),
('TH-76', 'zu', 'I-Changwat Phetchaburi'),
('TH-77', 'zu', 'I-Changwat Prachuap Khiri Khan'),
('TH-80', 'zu', 'Changwat Nakhon Si Thammarat'),
('TH-81', 'zu', 'krabi'),
('TH-82', 'zu', 'phangnga'),
('TH-83', 'zu', 'phuket'),
('TH-84', 'zu', 'I-Changwat Surat Thani'),
('TH-85', 'zu', 'I-Changwat Ranong'),
('TH-86', 'zu', 'I-Changwat Chumphon'),
('TH-90', 'zu', 'sngkhla'),
('TH-91', 'zu', 'I-Changwat Satun'),
('TH-92', 'zu', 'trang'),
('TH-93', 'zu', 'phathlung'),
('TH-94', 'zu', 'pattani'),
('TH-95', 'zu', 'yala'),
('TH-96', 'zu', 'I-Changwat Narathiwat'),
('TH-S', 'zu', 'I-Phatthaya');

SET FOREIGN_KEY_CHECKS=1;
