SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('MT-01', 'ro', 'Attard'),
('MT-02', 'ro', 'Balzan'),
('MT-03', 'ro', 'Birgu'),
('MT-04', 'ro', 'Birkirkara'),
('MT-05', 'ro', 'Birżebbuġa'),
('MT-06', 'ro', 'Bormla'),
('MT-07', 'ro', 'Dingli'),
('MT-08', 'ro', 'Fgura'),
('MT-09', 'ro', 'Il-Furjana'),
('MT-10', 'ro', 'Fontana'),
('MT-11', 'ro', 'Gudja'),
('MT-12', 'ro', 'Gzira'),
('MT-13', 'ro', 'Ghajnsielem'),
('MT-14', 'ro', 'L-Gharb'),
('MT-15', 'ro', 'Hal Gharghur'),
('MT-16', 'ro', 'Ghasri'),
('MT-17', 'ro', 'Ghaxaq'),
('MT-18', 'ro', 'Ħamrun'),
('MT-19', 'ro', 'L-Iklin'),
('MT-20', 'ro', 'L-Isla'),
('MT-21', 'ro', 'Kalkara'),
('MT-22', 'ro', 'Kercem'),
('MT-23', 'ro', 'Kirkop'),
('MT-24', 'ro', 'Lija'),
('MT-25', 'ro', 'Luqa'),
('MT-26', 'ro', 'Marsa'),
('MT-27', 'ro', 'Marsaskala'),
('MT-28', 'ro', 'Marsaxlokk'),
('MT-29', 'ro', 'Mdina'),
('MT-30', 'ro', 'Mellieħa'),
('MT-31', 'ro', 'Imgarr'),
('MT-32', 'ro', 'Mosta'),
('MT-33', 'ro', 'Imqabba'),
('MT-34', 'ro', 'Imsida'),
('MT-35', 'ro', 'Imtarfa'),
('MT-36', 'ro', 'Munxar'),
('MT-37', 'ro', 'Nadur'),
('MT-38', 'ro', 'Naxxar'),
('MT-39', 'ro', 'Paola'),
('MT-40', 'ro', 'Pembroke'),
('MT-41', 'ro', 'Pieta'),
('MT-42', 'ro', 'Qala'),
('MT-43', 'ro', 'Qormi'),
('MT-44', 'ro', 'Qrendi'),
('MT-45', 'ro', 'Victoria'),
('MT-46', 'ro', 'Rabat'),
('MT-47', 'ro', 'Safi'),
('MT-48', 'ro', 'St. Julian''s'),
('MT-49', 'ro', 'San Gwann'),
('MT-50', 'ro', 'Sfântul Lawrence'),
('MT-51', 'ro', 'Golful Sfântul Paul'),
('MT-52', 'ro', 'Sannat'),
('MT-53', 'ro', 'Santa Lucija'),
('MT-54', 'ro', 'Santa Venera'),
('MT-55', 'ro', 'Siggiewi'),
('MT-56', 'ro', 'Sliema'),
('MT-57', 'ro', 'Swieqi'),
('MT-58', 'ro', 'Tarxien'),
('MT-59', 'ro', 'Ta'' Xbiex'),
('MT-60', 'ro', 'Valletta'),
('MT-61', 'ro', 'Xaghra'),
('MT-62', 'ro', 'Xewkija'),
('MT-63', 'ro', 'Xghajra'),
('MT-64', 'ro', 'Zabbar'),
('MT-65', 'ro', 'Iz-Zebbug'),
('MT-66', 'ro', 'Zebbug'),
('MT-67', 'ro', 'Żejtun'),
('MT-68', 'ro', 'Zurrieq');

SET FOREIGN_KEY_CHECKS=1;
