SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('KE-01', 'rw', 'Baringo'),
('KE-02', 'rw', 'Bomet County'),
('KE-03', 'rw', 'Bungoma County'),
('KE-04', 'rw', 'Busia County'),
('KE-05', 'rw', 'Marakwet District'),
('KE-06', 'rw', 'Embu County'),
('KE-07', 'rw', 'Garissa County'),
('KE-08', 'rw', 'Homa Bay County'),
('KE-09', 'rw', 'Isiolo County'),
('KE-10', 'rw', 'Kajiado County'),
('KE-11', 'rw', 'Kakamega County'),
('KE-12', 'rw', 'Kericho County'),
('KE-13', 'rw', 'Kiambu County'),
('KE-14', 'rw', 'Kilifi County'),
('KE-15', 'rw', 'Kirinyaga County'),
('KE-16', 'rw', 'Kisii County'),
('KE-17', 'rw', 'Kisumu County'),
('KE-18', 'rw', 'Kitui County'),
('KE-19', 'rw', 'Kwale County'),
('KE-20', 'rw', 'Laikipia'),
('KE-21', 'rw', 'Lamu old town'),
('KE-22', 'rw', 'Machakos County'),
('KE-23', 'rw', 'Makueni County'),
('KE-24', 'rw', 'Mandera County'),
('KE-25', 'rw', 'Marsabit County'),
('KE-26', 'rw', 'Meru County'),
('KE-27', 'rw', 'Migori County'),
('KE-28', 'rw', 'Mombasa County'),
('KE-29', 'rw', 'Muranga County'),
('KE-30', 'rw', 'Nairobi County'),
('KE-31', 'rw', 'Nakuru County'),
('KE-32', 'rw', 'Nandi'),
('KE-33', 'rw', 'Narok County'),
('KE-34', 'rw', 'Nyamira county'),
('KE-35', 'rw', 'Nyandarua County'),
('KE-36', 'rw', 'Nyeri County'),
('KE-37', 'rw', 'Samburu County'),
('KE-38', 'rw', 'Siaya County'),
('KE-39', 'rw', 'Taita-Taveta County'),
('KE-40', 'rw', 'Tana River County'),
('KE-41', 'rw', 'Tharaka Nithi County'),
('KE-42', 'rw', 'Trans-Nzoia county'),
('KE-43', 'rw', 'Turkana County'),
('KE-44', 'rw', 'Uasin Gishu County'),
('KE-45', 'rw', 'Vihiga County'),
('KE-46', 'rw', 'Wajir County'),
('KE-47', 'rw', 'West Pokot County');

SET FOREIGN_KEY_CHECKS=1;
