SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('DO-01', 'fr', 'Distrito Nacional'),
('DO-02', 'fr', 'Azua'),
('DO-03', 'fr', 'Baoruco'),
('DO-04', 'fr', 'Barahona'),
('DO-05', 'fr', 'Dajabón'),
('DO-06', 'fr', 'Duarte'),
('DO-07', 'fr', 'Elías Piña'),
('DO-08', 'fr', 'El Seibo'),
('DO-09', 'fr', 'Espaillat'),
('DO-10', 'fr', 'Independencia'),
('DO-11', 'fr', 'La Altagracia'),
('DO-12', 'fr', 'La Romana'),
('DO-13', 'fr', 'La Vega'),
('DO-14', 'fr', 'María Trinidad Sánchez'),
('DO-15', 'fr', 'Monte Cristi'),
('DO-16', 'fr', 'Pedernales'),
('DO-17', 'fr', 'Peravia'),
('DO-18', 'fr', 'Puerto Plata'),
('DO-19', 'fr', 'Hermanas Mirabal'),
('DO-20', 'fr', 'Samaná'),
('DO-21', 'fr', 'San Cristóbal'),
('DO-22', 'fr', 'San Juan'),
('DO-23', 'fr', 'San Pedro de Macorís'),
('DO-24', 'fr', 'Sánchez Ramírez'),
('DO-25', 'fr', 'Santiago'),
('DO-26', 'fr', 'Santiago Rodríguez'),
('DO-27', 'fr', 'Valverde'),
('DO-28', 'fr', 'Monseñor Nouel'),
('DO-29', 'fr', 'Monte Plata'),
('DO-30', 'fr', 'Hato Mayor'),
('DO-31', 'fr', 'San José de Ocoa'),
('DO-32', 'fr', 'Santo Domingo'),
('DO-33', 'fr', 'Cibao Nordeste'),
('DO-34', 'fr', 'Cibao Noroeste'),
('DO-35', 'fr', 'Cibao Norte'),
('DO-36', 'fr', 'Cibao Sur'),
('DO-37', 'fr', 'El Valle'),
('DO-38', 'fr', 'Enriquillo'),
('DO-39', 'fr', 'Higuamo'),
('DO-40', 'fr', 'Ozama'),
('DO-41', 'fr', 'Valdesia'),
('DO-42', 'fr', 'Yuma');

SET FOREIGN_KEY_CHECKS=1;
