SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_countries_altnames` (`key`, `language_key`, `name`) VALUES
('MP', 'aa', NULL),
('MP', 'am', 'የሰሜናዊ ማሪያና ደሴቶች'),
('MP', 'ar', 'جزر ماريانا الشمالية'),
('MP', 'az', 'Şimali Marian adaları'),
('MP', 'be', 'Паўночныя Марыянскія астравы'),
('MP', 'bg', 'Северни Мариански острови'),
('MP', 'bn', 'উত্তরাঞ্চলীয় মারিয়ানা দ্বীপপুঞ্জ'),
('MP', 'bs', 'Sjeverna Marijanska ostrva'),
('MP', 'ca', 'Illes Marianes del Nord'),
('MP', 'cs', 'Severní Mariany'),
('MP', 'da', 'Nordmarianerne'),
('MP', 'de', 'Nördliche Marianen'),
('MP', 'dv', 'އުތުރު މެރިއާނާ ޖަޒީރާ'),
('MP', 'dz', 'བྱང་ཕྱོགས་ཀྱི་མ་ར་ཡ་ན་གླིང་ཚོམ'),
('MP', 'el', 'Νήσοι Βόρειες Μαριάνες'),
('MP', 'en', 'Northern Mariana Islands'),
('MP', 'es', 'Islas Marianas del Norte'),
('MP', 'et', 'Põhja-Mariaanid'),
('MP', 'fa', 'جزایر ماریانای شمالی'),
('MP', 'fi', 'Pohjois-Mariaanit'),
('MP', 'fo', 'Norðaru Mariuoyggjar'),
('MP', 'fr', 'Îles Mariannes du Nord'),
('MP', 'he', 'איי מריאנה הצפוניים'),
('MP', 'hr', 'Sjevernomarijanski Otoci'),
('MP', 'ht', 'Îles Mariannes du Nord'),
('MP', 'hu', 'Északi Mariana-szigetek'),
('MP', 'hy', 'Հյուսիսային Մարիանյան կղզիներ'),
('MP', 'id', 'Kepulauan Mariana Utara'),
('MP', 'is', 'Norður-Maríanaeyjar'),
('MP', 'it', 'Isole Marianne Settentrionali'),
('MP', 'ja', '北マリアナ諸島'),
('MP', 'ka', 'ჩრდილოეთ მარიანას კუნძულები'),
('MP', 'kk', 'Солтүстік Мариана аралдары'),
('MP', 'kl', NULL),
('MP', 'km', 'កោះ​ម៉ារីណា​ខាង​ជើង'),
('MP', 'ko', '북마리아나제도'),
('MP', 'ky', 'Түндүк Мариана аралдары'),
('MP', 'la', 'Insulae Marianae Septentrionales'),
('MP', 'lb', 'Nërdlech Marianen'),
('MP', 'lt', 'Marianos Šiaurinės Salos'),
('MP', 'lv', 'Ziemeļu Marianas salas'),
('MP', 'mh', NULL),
('MP', 'mk', 'Северни Маријански Острови'),
('MP', 'mn', 'Хойд Марианы арлууд'),
('MP', 'ms', 'Kepulauan Mariana Utara'),
('MP', 'mt', 'Ġżejjer Mariana tat-Tramuntana'),
('MP', 'my', 'မြောက်ပိုင်းမာရီအာနာကျွန်းစု'),
('MP', 'ne', 'उत्तरी मारिआना टापु'),
('MP', 'nl', 'Noordelijke Marianen'),
('MP', 'no', 'Nord-Marianene'),
('MP', 'ny', 'Zilumba za Northern Mariana'),
('MP', 'pl', 'Mariany Północne'),
('MP', 'pt', 'Ilhas Marianas do Norte'),
('MP', 'ro', 'Insulele Mariane de Nord'),
('MP', 'ru', 'Северные Марианские о-ва'),
('MP', 'rw', 'Ibirwa bya Mariyana y’Amajyaruguru'),
('MP', 'si', 'උතුරු මරියානා දූපත්'),
('MP', 'sk', 'Severné Mariány'),
('MP', 'sl', 'Severni Marianski otoki'),
('MP', 'sm', 'North Mariana Islands'),
('MP', 'so', 'Jasiiradda Waqooyiga Mariaana'),
('MP', 'sq', 'Ishujt e Marianës Veriore'),
('MP', 'sr', 'Северна Маријанска Острва'),
('MP', 'sv', 'Nordmarianerna'),
('MP', 'sw', 'Visiwa vya Mariana vya Kaskazini'),
('MP', 'tg', 'Ҷазираҳои Марианаи Шимолӣ'),
('MP', 'th', 'หมู่เกาะนอร์เทิร์นมาเรียนา'),
('MP', 'tk', 'Demirgazyk Mariana adalary'),
('MP', 'tl', 'Hilagang Kapuluang Mariana'),
('MP', 'to', 'ʻOtumotu Maliana tokelau'),
('MP', 'tr', 'Kuzey Mariana Adaları'),
('MP', 'uk', 'Північні Маріанські Острови'),
('MP', 'ur', 'شمالی ماریانا آئلینڈز'),
('MP', 'uz', 'Shimoliy Mariana orollari'),
('MP', 'vi', 'Quần đảo Bắc Mariana'),
('MP', 'zh', '北马里亚纳群岛'),
('MP', 'zu', 'i-Northern Mariana Islands');

SET FOREIGN_KEY_CHECKS=1;
