SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('EE-130', 'sv', 'Alutaguse'),
('EE-141', 'sv', 'Anija'),
('EE-142', 'sv', 'Antsla'),
('EE-171', 'sv', 'Elva'),
('EE-184', 'sv', 'Haapsalu'),
('EE-191', 'sv', 'Haljala'),
('EE-198', 'sv', 'Harku'),
('EE-205', 'sv', 'Hiiumaa'),
('EE-214', 'sv', 'Häädemeeste'),
('EE-245', 'sv', 'Jõelähtme'),
('EE-247', 'sv', 'Jõgeva'),
('EE-251', 'sv', 'Jõhvi'),
('EE-255', 'sv', 'Järva'),
('EE-272', 'sv', 'Kadrina'),
('EE-283', 'sv', 'Kambja'),
('EE-284', 'sv', 'Kanepi'),
('EE-291', 'sv', 'Kastre'),
('EE-293', 'sv', 'Kehtna'),
('EE-296', 'sv', 'Keila'),
('EE-303', 'sv', 'Kihnu'),
('EE-305', 'sv', 'Kiili'),
('EE-317', 'sv', 'Kohila'),
('EE-321', 'sv', 'Kohtla-Järve'),
('EE-338', 'sv', 'Köse'),
('EE-353', 'sv', 'Kuusalu'),
('EE-37', 'sv', 'Harju län'),
('EE-39', 'sv', 'Dagö län'),
('EE-424', 'sv', 'Loksa'),
('EE-430', 'sv', 'Lääneranna'),
('EE-431', 'sv', 'Lääne-Harju'),
('EE-432', 'sv', 'Luunja'),
('EE-441', 'sv', 'Lääne-Nigula'),
('EE-442', 'sv', 'Lüganuse'),
('EE-446', 'sv', 'Maardu'),
('EE-45', 'sv', 'Ida-Viru län'),
('EE-478', 'sv', 'Muhu'),
('EE-480', 'sv', 'Mulgi'),
('EE-486', 'sv', 'Mustvee'),
('EE-50', 'sv', 'Jõgeva län'),
('EE-503', 'sv', 'Märjamaa'),
('EE-511', 'sv', 'Narva'),
('EE-514', 'sv', 'Narva-Jõesuu'),
('EE-52', 'sv', 'Järva län'),
('EE-528', 'sv', 'Nõo'),
('EE-557', 'sv', 'Otepää'),
('EE-56', 'sv', 'Lääne län'),
('EE-567', 'sv', 'Paide'),
('EE-586', 'sv', 'Peipsiääre'),
('EE-60', 'sv', 'Lääne-Viru län'),
('EE-615', 'sv', 'Põhja-Sakala'),
('EE-618', 'sv', 'Põltsamaa'),
('EE-622', 'sv', 'Põlva'),
('EE-624', 'sv', 'Pärnu'),
('EE-638', 'sv', 'Põhja-Pärnumaa'),
('EE-64', 'sv', 'Põlva län'),
('EE-651', 'sv', 'Raasiku'),
('EE-653', 'sv', 'Rae'),
('EE-661', 'sv', 'Rakvere'),
('EE-663', 'sv', 'Rakvere'),
('EE-668', 'sv', 'Rapla'),
('EE-68', 'sv', 'Pärnu län'),
('EE-689', 'sv', 'Ruhnu'),
('EE-698', 'sv', 'Rouge'),
('EE-708', 'sv', 'Räpina'),
('EE-71', 'sv', 'Rapla län'),
('EE-712', 'sv', 'Saarde'),
('EE-714', 'sv', 'Saaremaa'),
('EE-719', 'sv', 'Saku'),
('EE-726', 'sv', 'Saue'),
('EE-732', 'sv', 'Setomaa'),
('EE-735', 'sv', 'Sillamäe'),
('EE-74', 'sv', 'Saare län'),
('EE-784', 'sv', 'Tallinn'),
('EE-79', 'sv', 'Tartu län'),
('EE-792', 'sv', 'Tapa'),
('EE-793', 'sv', 'Tartu'),
('EE-796', 'sv', 'Tartu'),
('EE-803', 'sv', 'Toila'),
('EE-809', 'sv', 'Tori'),
('EE-81', 'sv', 'Valga län'),
('EE-824', 'sv', 'Tõrva'),
('EE-834', 'sv', 'Türi'),
('EE-84', 'sv', 'Viljandi län'),
('EE-855', 'sv', 'Valga'),
('EE-87', 'sv', 'Võru län'),
('EE-890', 'sv', 'Viimsi'),
('EE-897', 'sv', 'Viljandi'),
('EE-899', 'sv', 'Viljandi'),
('EE-901', 'sv', 'Vinni'),
('EE-903', 'sv', 'Viru-Nigula'),
('EE-907', 'sv', 'Vormsi'),
('EE-917', 'sv', 'Võru'),
('EE-919', 'sv', 'Võru'),
('EE-928', 'sv', 'Väike-Maarja');

SET FOREIGN_KEY_CHECKS=1;
