SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_currencies_altnames` (`key`, `language_key`, `name`) VALUES
('AED', 'dz', 'ཡུ་ནཱའི་ཊེཌ་ ཨ་རབ་ ཨེ་མེ་རེཊས་ཀྱི་དངུལ་ ཌིར་ཧཱམ'),
('AFN', 'dz', 'ཨཕ་གཱན་གྱི་དངུལ་ ཨཕ་ག་ནི'),
('ALL', 'dz', 'Lek'),
('AMD', 'dz', 'Armenian Dram'),
('AOA', 'dz', 'Kwanza'),
('ARS', 'dz', 'Argentine Peso'),
('AUD', 'dz', 'ཨཱོས་ཊྲེ་ལི་ཡ་གི་དངུལ་ ཌོ་ལར'),
('AWG', 'dz', 'Aruban Florin'),
('AZN', 'dz', 'Azerbaijan Manat'),
('BAM', 'dz', 'Convertible Mark'),
('BBD', 'dz', 'Barbados Dollar'),
('BDT', 'dz', 'བྷང་ལ་དེཤ་གི་དངུལ་ ཏ་ཀ'),
('BHD', 'dz', 'Bahraini Dinar'),
('BIF', 'dz', 'Burundi Franc'),
('BMD', 'dz', 'བར་མུ་ཌ་གི་དངུལ་ ཌོ་ལར'),
('BND', 'dz', 'Brunei Dollar'),
('BOB', 'dz', 'Boliviano'),
('BOV', 'dz', 'Mvdol'),
('BRL', 'dz', 'བྲ་ཛིལ་གྱི་དངུལ་ རེ་ཡལ'),
('BSD', 'dz', 'Bahamian Dollar'),
('BTN', 'dz', 'དངུལ་ཀྲམ'),
('BWP', 'dz', 'Pula'),
('BYN', 'dz', 'Belarusian Ruble'),
('BZD', 'dz', 'Belize Dollar'),
('CAD', 'dz', 'ཀེ་ན་ཌ་གི་དངུལ་ ཌོ་ལར'),
('CDF', 'dz', 'Congolese Franc'),
('CHE', 'dz', 'WIR Euro'),
('CHF', 'dz', 'སུ་ཡིས་ཀྱི་དངུལ་ ཕྲངཀ'),
('CHW', 'dz', 'WIR Franc'),
('CLF', 'dz', 'Unidad de Fomento'),
('CLP', 'dz', 'ཅི་ལི་གི་དངུལ་ པེ་སོ'),
('CNY', 'dz', 'རྒྱ་ནག་གི་དངུལ་ ཡུ་ཝཱན'),
('COP', 'dz', 'ཀོ་ལོམ་བྷི་ཡ་གི་དངུལ་ པེ་སོ'),
('COU', 'dz', 'Unidad de Valor Real'),
('CRC', 'dz', 'Costa Rican Colon'),
('CUP', 'dz', 'ཀིའུ་བྷ་གི་དངུལ་ པེ་སོ'),
('CVE', 'dz', 'Cabo Verde Escudo'),
('CZK', 'dz', 'Czech Koruna'),
('DJF', 'dz', 'Djibouti Franc'),
('DKK', 'dz', 'ཌེན་མཱཀ་གི་དངུལ་ ཀྲོན'),
('DOP', 'dz', 'Dominican Peso'),
('DZD', 'dz', 'ཨཱལ་ཇི་རི་ཡ་གི་དངུལ་ ཌའི་ནར'),
('EGP', 'dz', 'ཨི་ཇིབཊ་གི་དངུལ་ པ་འུནཌ'),
('ERN', 'dz', 'Nakfa'),
('ETB', 'dz', 'Ethiopian Birr'),
('EUR', 'dz', 'ཡུ་རོ༌དངུལ་'),
('FJD', 'dz', 'Fiji Dollar'),
('FKP', 'dz', 'Falkland Islands Pound'),
('GBP', 'dz', 'བྲི་ཊིཤ་ པ་འུནཌ་ ཨིས་ཊར་ལིང'),
('GEL', 'dz', 'Lari'),
('GHS', 'dz', 'Ghana Cedi'),
('GIP', 'dz', 'Gibraltar Pound'),
('GMD', 'dz', 'Dalasi'),
('GNF', 'dz', 'Guinean Franc'),
('GTQ', 'dz', 'Quetzal'),
('GYD', 'dz', 'Guyana Dollar'),
('HKD', 'dz', 'ཧོང་ཀོང་གི་དངུལ་ ཌོ་ལར'),
('HNL', 'dz', 'Lempira'),
('HTG', 'dz', 'Gourde'),
('HUF', 'dz', 'Forint'),
('IDR', 'dz', 'ཨིན་ཌོ་ནེ་ཤི་ཡ་གི་དངུལ་ རུ་པི་ཡ'),
('ILS', 'dz', 'ཨིས་རེལ་གྱི་དངུལ་གསརཔ་ ཤེ་ཀེལ'),
('INR', 'dz', 'རྒྱ་གར་གྱི་དངུལ་ རུ་པི'),
('IQD', 'dz', 'ཨི་རཱཀ་གི་དངུལ་ ཌི་ན'),
('IRR', 'dz', 'ཨི་རཱན་གྱི་དངུལ་ རི་ཨཱལ'),
('ISK', 'dz', 'ཨཱཡིས་ལེནཌ་གི་དངུལ་ ཀྲོ་ན'),
('JMD', 'dz', 'ཇཱ་མཻ་ཀ་གི་དངུལ་ ཌོ་ལར'),
('JOD', 'dz', 'ཇོར་ཌན་གྱི་དངུལ་ ཌི་ན'),
('JPY', 'dz', 'ཇཱ་པཱན་གྱི་དངུལ་ ཡེན'),
('KES', 'dz', 'ཀེན་ཡ་གི་དངུལ་ ཤི་ལིང'),
('KGS', 'dz', 'Som'),
('KHR', 'dz', 'ཀེམ་བྷོ་ཌི་ཡ་གི་དངུལ་ རི་ཨཱལ'),
('KMF', 'dz', 'Comorian Franc'),
('KPW', 'dz', 'ནོརཐ་ ཀོ་རི་ཡ་གི་དངུལ་ ཝོན'),
('KRW', 'dz', 'སཱའུཐ་ ཀོ་རི་ཡ་གི་དངུལ་ ཝོན'),
('KWD', 'dz', 'ཀུ་ཝེཊ་གི་དངུལ་ ཌི་ན'),
('KYD', 'dz', 'Cayman Islands Dollar'),
('KZT', 'dz', 'ཀ་ཛགས་ཏཱན་གྱི་དངུལ་ ཏེང་གེ'),
('LAK', 'dz', 'ལཱ་ཝོས་ཀྱི་དངུལ་ ཀིཔ'),
('LBP', 'dz', 'ལེ་བ་ནོན་གྱི་དངུལ་ པ་འུནཌ'),
('LKR', 'dz', 'ཤྲི་ ལང་ཀ་གི་དངུལ་ རུ་པི'),
('LRD', 'dz', 'ལཱའི་བེ་རི་ཡ་གི་དངུལ་ ཌོ་ལར'),
('LSL', 'dz', 'Loti'),
('LYD', 'dz', 'ལི་བི་ཡ་གི་དངུལ་ ཌི་ན'),
('MAD', 'dz', 'མོ་རོ་ཀོ་གི་དངུལ་ ཌིར་ཧཱམ'),
('MDL', 'dz', 'Moldovan Leu'),
('MGA', 'dz', 'Malagasy Ariary'),
('MKD', 'dz', 'Denar'),
('MMK', 'dz', 'མི་ཡཱན་མར་གྱི་དངུལ་ ཅཱཏ'),
('MNT', 'dz', 'སོག་པོའི་དངུལ་ ཏུ་གྲིཀ'),
('MOP', 'dz', 'Pataca'),
('MRU', 'dz', 'Ouguiya'),
('MUR', 'dz', 'Mauritius Rupee'),
('MVR', 'dz', 'མཱལ་དིབས་ཀྱི་དངུལ་ རུ་ཕི་ཡ'),
('MWK', 'dz', 'Malawi Kwacha'),
('MXN', 'dz', 'མེཀ་སི་ཀོ་གི་དངུལ་ པེ་སོ'),
('MXV', 'dz', 'Mexican Unidad de Inversion (UDI)'),
('MYR', 'dz', 'མ་ལེ་ཤི་ཡ་གི་དངུལ་ རིང་གིཊ'),
('MZN', 'dz', 'Mozambique Metical'),
('NAD', 'dz', 'Namibia Dollar'),
('NGN', 'dz', 'Naira'),
('NIO', 'dz', 'Cordoba Oro'),
('NOK', 'dz', 'ནོར་ཝེ་གི་དངུལ་ ཀྲོ་ན'),
('NPR', 'dz', 'བལ་པོའི་དངུལ་ རུ་པི'),
('NZD', 'dz', 'ནིའུ་ཛི་ལེནཌ་གི་དངུལ་ ཌོ་ལར'),
('OMR', 'dz', 'ཨོ་མཱན་གྱི་དངུལ་ རི་ཨཱལ'),
('PAB', 'dz', 'པ་ན་མ་གི་དངུལ་ བཱལ་བོ་ཝ'),
('PEN', 'dz', 'པ་རུ་གི་དངུལ་ ནུ་བོ་ སཱོལ'),
('PGK', 'dz', 'Kina'),
('PHP', 'dz', 'ཕི་ལི་པིནས་གྱི་དངུལ་ པེ་སོ'),
('PKR', 'dz', 'པ་ཀིས་ཏཱན་གྱི་དངུལ་ རུ་པི'),
('PLN', 'dz', 'པོ་ལེནཌ་ཀྱི་དངུལ ཛ྄ལོ་ཊི'),
('PYG', 'dz', 'Guarani'),
('QAR', 'dz', 'ཀ་ཊར་གྱི་དངུལ་ རི་ཨཱལ'),
('RON', 'dz', 'Romanian Leu'),
('RSD', 'dz', 'Serbian Dinar'),
('RUB', 'dz', 'ཨུ་རུ་སུ་གི་དངུལ་ རུ་བཱལ'),
('RWF', 'dz', 'Rwanda Franc'),
('SAR', 'dz', 'སཱཝ་དིའི་དངུལ་ རི་ཡཱལ'),
('SBD', 'dz', 'Solomon Islands Dollar'),
('SCR', 'dz', 'སེ་ཤཱལས་ཀྱི་དངུལ་ རུ་པི'),
('SDG', 'dz', 'Sudanese Pound'),
('SEK', 'dz', 'སུའི་ཌེན་གྱི་དངུལ་ ཀྲོ་ན'),
('SGD', 'dz', 'སིང་ག་པོར་གྱི་དངུལ་ ཌོ་ལར'),
('SHP', 'dz', 'Saint Helena Pound'),
('SLE', 'dz', 'Leone'),
('SOS', 'dz', 'Somali Shilling'),
('SRD', 'dz', 'Surinam Dollar'),
('SSP', 'dz', 'South Sudanese Pound'),
('STN', 'dz', 'Dobra'),
('SVC', 'dz', 'El Salvador Colon'),
('SYP', 'dz', 'སི་རི་ཡ་གི་དངུལ་ པ་འུནཌ'),
('SZL', 'dz', 'Lilangeni'),
('THB', 'dz', 'ཐཱའི་ལེནཌ་གི་དངུལ་ བཱཏ'),
('TJS', 'dz', 'ཏ་ཇི་ཀིས་ཏཱན་གྱི་དངུལ་ སོ་མོ་ནི'),
('TMT', 'dz', 'Turkmenistan New Manat'),
('TND', 'dz', 'Tunisian Dinar'),
('TOP', 'dz', 'Pa’anga'),
('TRY', 'dz', 'ཊཱར་ཀི་གི་དངུལ་ ལི་ར'),
('TTD', 'dz', 'Trinidad and Tobago Dollar'),
('TWD', 'dz', 'ཊཱའི་ཝཱན་གི་དངུལ ཌོ་ལར'),
('TZS', 'dz', 'ཊཱན་ཛཱ་ནི་ཡ་གི་དངུལ་ ཤི་ལིང'),
('UAH', 'dz', 'Hryvnia'),
('UGX', 'dz', 'ཡུ་གྷེན་ཌ་གི་དངུལ་ ཤི་ལིང'),
('USD', 'dz', 'ཡུ་ཨེས་ ཌོ་ལར'),
('USN', 'dz', 'US Dollar (Next day)'),
('UYI', 'dz', 'Uruguay Peso en Unidades Indexadas (UI)'),
('UYU', 'dz', 'ཡུ་རུ་གུ་ཝའི་གི་དངུལ་ པེ་སོ'),
('UYW', 'dz', 'Unidad Previsional'),
('UZS', 'dz', 'ཨུས་བེ་ཀིས་ཏཱན་གྱི་དངུལ་ སོམ'),
('VED', 'dz', 'Bolívar Soberano'),
('VES', 'dz', 'བེ་ནི་ཛུ་ཝེ་ལ་གི་དངུལ་ བོ་ལི་བར'),
('VND', 'dz', 'བེཊ་ནཱམ་གྱི་དངུལ་ ཌོང'),
('VUV', 'dz', 'Vatu'),
('WST', 'dz', 'Tala'),
('XAD', 'dz', 'Arab Accounting Dinar'),
('XAF', 'dz', 'CFA Franc BEAC'),
('XAG', 'dz', 'Silver'),
('XAU', 'dz', 'Gold'),
('XBA', 'dz', 'Bond Markets Unit European Composite Unit (EURCO)'),
('XBB', 'dz', 'Bond Markets Unit European Monetary Unit (E.M.U.-6)'),
('XBC', 'dz', 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)'),
('XBD', 'dz', 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)'),
('XCD', 'dz', 'East Caribbean Dollar'),
('XCG', 'dz', 'Caribbean Guilder'),
('XDR', 'dz', 'SDR (Special Drawing Right)'),
('XOF', 'dz', 'CFA Franc BCEAO'),
('XPD', 'dz', 'Palladium'),
('XPF', 'dz', 'CFP Franc'),
('XPT', 'dz', 'Platinum'),
('XSU', 'dz', 'Sucre'),
('XTS', 'dz', 'Codes specifically reserved for testing purposes'),
('XUA', 'dz', 'ADB Unit of Account'),
('XXX', 'dz', 'མ་ཤེས་པའི་དངུལ'),
('YER', 'dz', 'Yemeni Rial'),
('ZAR', 'dz', 'སཱའུཐ་ ཨཕ་རི་ཀ་གི་དངུལ་ རཱནད'),
('ZMW', 'dz', 'Zambian Kwacha'),
('ZWG', 'dz', 'Zimbabwe Gold');

SET FOREIGN_KEY_CHECKS=1;
