SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions_altnames` (`key`, `language_key`, `name`) VALUES
('LV-002', 'hu', 'Aizkraukle'),
('LV-007', 'hu', 'Aluksnes novads'),
('LV-011', 'hu', 'Adazi'),
('LV-015', 'hu', 'Balvu'),
('LV-016', 'hu', 'Bauskas novads'),
('LV-022', 'hu', 'Cesu'),
('LV-026', 'hu', 'Dobeles novads'),
('LV-033', 'hu', 'Gulbenes novads'),
('LV-041', 'hu', 'Jelgavas novads'),
('LV-042', 'hu', 'Jekabpils novads'),
('LV-047', 'hu', 'Krāslava'),
('LV-050', 'hu', 'Kuldīga'),
('LV-052', 'hu', 'Kekavas'),
('LV-054', 'hu', 'Limbazu novads'),
('LV-056', 'hu', 'Līvāni'),
('LV-058', 'hu', 'Ludza'),
('LV-059', 'hu', 'Madonas novads'),
('LV-062', 'hu', 'Mārupe'),
('LV-067', 'hu', 'Ogre'),
('LV-068', 'hu', 'Olaines'),
('LV-073', 'hu', 'Preilu'),
('LV-077', 'hu', 'Rēzekne'),
('LV-080', 'hu', 'Ropazu novads'),
('LV-087', 'hu', 'Salaspils'),
('LV-088', 'hu', 'Saldus'),
('LV-089', 'hu', 'Saulkrastu'),
('LV-091', 'hu', 'Sigulda'),
('LV-094', 'hu', 'Smiltenes novads'),
('LV-097', 'hu', 'Talsu novads'),
('LV-099', 'hu', 'Tukums község'),
('LV-101', 'hu', 'Valkas novads'),
('LV-102', 'hu', 'Varaklanu novads'),
('LV-106', 'hu', 'Ventspils novads'),
('LV-111', 'hu', 'Augsdaugavas novads'),
('LV-112', 'hu', 'Dienvidkurzemes novads'),
('LV-113', 'hu', 'Valmiera'),
('LV-DGV', 'hu', 'Daugavpils'),
('LV-JEL', 'hu', 'Jelgava'),
('LV-JUR', 'hu', 'Jūrmala'),
('LV-LPX', 'hu', 'Liepāja'),
('LV-REZ', 'hu', 'Rēzekne'),
('LV-RIX', 'hu', 'Riga'),
('LV-VEN', 'hu', 'Ventspils');

SET FOREIGN_KEY_CHECKS=1;
