SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `geo_regions` (`key`, `country`, `name`, `native_name`, `capital`, `population`, `timezone_utc`, `timezone_iana`) VALUES
('ES-A', 'ES', 'Alicante', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-AB', 'ES', 'Albacete', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-AL', 'ES', 'Almería', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-AN', 'ES', 'Andalusia', 'Andalucía', 1480032, 8302923, 'UTC+1', 'Europe/Madrid'),
('ES-AR', 'ES', 'Aragon', 'Comunidad Autónoma de Aragón', 1485741, 1345473, 'UTC+1', 'Europe/Madrid'),
('ES-AS', 'ES', 'Principality of Asturias', 'Principado de Asturias', 1493814, 1085289, 'UTC+0, UTC+1', 'Europe/Lisbon, Europe/Madrid'),
('ES-AV', 'ES', 'Ávila', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-B', 'ES', 'Barcelona [Barcelona]', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-BA', 'ES', 'Badajoz', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-BI', 'ES', 'Bizkaia', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-BU', 'ES', 'Burgos', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-C', 'ES', 'A Coruña [La Coruña]', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-CA', 'ES', 'Cádiz', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-CB', 'ES', 'Cantabria', 'Comunidad Autónoma de Cantabria', 1490020, 589235, 'UTC+1', 'Europe/Madrid'),
('ES-CC', 'ES', 'Cáceres', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-CE', 'ES', 'Ceuta', 'Ciudad Autónoma de Ceuta', 1506648, 78674, 'UTC+1', 'Europe/Madrid'),
('ES-CL', 'ES', 'Castilla y Leon', 'Comunidad Autónoma de Castilla y León', 1487712, 2563521, 'UTC+1', 'Europe/Madrid'),
('ES-CM', 'ES', 'Castilla-La Mancha', 'Comunidad Autónoma de Castilla-La Mancha', 1479823, 2081313, 'UTC+1', 'Europe/Madrid'),
('ES-CN', 'ES', 'Canary Islands', 'Comunidad Autónoma de Canarias', 1482000, 2103992, 'UTC+0', 'Atlantic/Canary'),
('ES-CO', 'ES', 'Córdoba', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-CR', 'ES', 'Ciudad Real', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-CS', 'ES', 'Castellón', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-CT', 'ES', 'Catalunya', 'Comunidad Autónoma de Cataluña', 1504582, 7475420, 'UTC+1', 'Europe/Madrid, Europe/Paris'),
('ES-CU', 'ES', 'Cuenca', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-EX', 'ES', 'Extremadura', 'Comunidad Autónoma de Extremadura', 1481184, 1102410, 'UTC+1', 'Europe/Madrid'),
('ES-GA', 'ES', 'Galicia', 'Comunidad Autónoma de Galicia', 1489960, 2796089, 'UTC+0, UTC+1', 'Europe/Lisbon, Europe/Madrid'),
('ES-GC', 'ES', 'Las Palmas', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-GI', 'ES', 'Girona [Gerona]', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-GR', 'ES', 'Granada', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-GU', 'ES', 'Guadalajara', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-H', 'ES', 'Huelva', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-HU', 'ES', 'Huesca', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-IB', 'ES', 'Comunitat Autonoma de les Illes Balears', 'Comunidad Autónoma de las Islas Baleares', 1480835, 1095426, 'UTC+1', 'Europe/Madrid'),
('ES-J', 'ES', 'Jaén', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-L', 'ES', 'Lleida [Lérida]', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-LE', 'ES', 'León', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-LO', 'ES', 'La Rioja', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-LU', 'ES', 'Lugo [Lugo]', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-M', 'ES', 'Madrid', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-MA', 'ES', 'Málaga', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-MC', 'ES', 'Region de Murcia', 'Región de Murcia', 1481000, 1446520, 'UTC+1', 'Europe/Madrid'),
('ES-MD', 'ES', 'Comunidad de Madrid', 'Comunidad Autónoma de Madrid', NULL, 6386932, 'UTC+1', 'Europe/Madrid'),
('ES-ML', 'ES', 'Melilla', 'Ciudad Autónoma de Melilla', 1481193, 73460, 'UTC+1', 'Africa/Ceuta'),
('ES-MU', 'ES', 'Murcia', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-NA', 'ES', 'Navarra', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-NC', 'ES', 'Navarra', 'Comunidad Foral de Navarra', 1493635, 630578, 'UTC+1', 'Europe/Madrid'),
('ES-O', 'ES', 'Asturias', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-OR', 'ES', 'Ourense [Orense]', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-P', 'ES', 'Palencia', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-PM', 'ES', 'Illes Balears [Islas Baleares]', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-PO', 'ES', 'Pontevedra [Pontevedra]', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-PV', 'ES', 'Euskal Autonomia Erkidegoa', 'Comunidad Autónoma del País Vasco', 1485864, 2172175, 'UTC+1', 'Europe/Madrid'),
('ES-RI', 'ES', 'La Rioja', 'Comunidad Autónoma de La Rioja', 1496443, 321702, 'UTC+1', 'Europe/Madrid'),
('ES-S', 'ES', 'Cantabria', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-SA', 'ES', 'Salamanca', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-SE', 'ES', 'Sevilla', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-SG', 'ES', 'Segovia', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-SO', 'ES', 'Soria', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-SS', 'ES', 'Gipuzkoa', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-T', 'ES', 'Tarragona [Tarragona]', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-TE', 'ES', 'Teruel', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-TF', 'ES', 'Santa Cruz de Tenerife', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-TO', 'ES', 'Toledo', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-V', 'ES', 'Valencia', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-VA', 'ES', 'Valladolid', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-VC', 'ES', 'Comunitat Valenciana', 'Comunidad Valenciana', 1479626, 5094675, 'UTC+1', 'Europe/Madrid'),
('ES-VI', 'ES', 'Álava', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-Z', 'ES', 'Zaragoza', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid'),
('ES-ZA', 'ES', 'Zamora', NULL, NULL, NULL, 'UTC+1, UTC+0', 'Africa/Ceuta, Atlantic/Canary, Europe/Madrid');

SET FOREIGN_KEY_CHECKS=1;
